<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">Seguiminto de Creditos </h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>*Programa de Financiamiento:</label>
                            <select name="plan" id="plan" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->programa) && count($this->programa)): ?>
                            <?php foreach ($this->programa as $val): ?>
                                <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['rubro'] .' - '.$val['ciclo'])  ?></option>        
                            
                            <?php endforeach; ?>
                            <?php endif; ?>    

                            
                        </select> 
                        </div>
                        

                    </div>
                    <div class="card-footer">
                        <button class="btn btn-default imprimir"  data-toggle="modal" data-target="#modal-xl">Generar Reporte</button>
                    </div>

                
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">Resumen  de Programa de Financiamiento </h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>*Programa de Financiamiento:</label>
                            <select name="plan1" id="plan1" class="form-control" >
                                <option value="0">-Seleccione-</option>
                                <?php if(isset($this->programa) && count($this->programa)): ?>
                                <?php foreach ($this->programa as $val): ?>
                                    <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['rubro'] .' - '.$val['ciclo'])  ?></option>        
                                
                                <?php endforeach; ?>
                                <?php endif; ?>    

                            
                            </select> 
                        </div>
                        

                    </div>
                    <div class="card-footer">
                        <button class="btn btn-default imprimir-resumen"  data-toggle="modal" data-target="#modal-default">Generar Reporte</button>
                        
                    </div>

                
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">Resumen de Cosecha </h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>*Programa de Financiamiento:</label>
                            <select name="plan2" id="plan2" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->programa) && count($this->programa)): ?>
                            <?php foreach ($this->programa as $val): ?>
                                <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['rubro'] .' - '.$val['ciclo'])  ?></option>        
                            
                            <?php endforeach; ?>
                            <?php endif; ?>    

                            
                        </select> 
                        </div>
                        <div class="form-group">
                            <label>*Convenio:</label>
                            <select name="convenio1" id="convenio1" class="form-control" >
                                <option value="0">-Seleccione-</option>
                                <?php if(isset($this->convenio) && count($this->convenio)): ?>
                                <?php foreach ($this->convenio as $con): ?>
                                    <option value="<?php echo $con['nombre']  ?>"><?php echo strtoupper($con['nombre'])  ?></option>        
                                
                                <?php endforeach; ?>
                                <?php endif; ?>    
                                
                            </select> 
                        </div>

                    </div>
                    <div class="card-footer">
                        <button class="btn btn-default imprimir-resumen-cosecha"  data-toggle="modal" data-target="#modal-default">Generar Reporte</button>
                    </div>

                
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title"><button type="button" class="btn btn-primary" id="imprimir" ><i class="fa fa-print"></i></button></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div class="row" id="nota" >

                </div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
               
                <button type="button" class="btn btn-primary" id="imprimir" ><i class="fa fa-print"></i></button>
                <button type="button" id="go_ini_nota" class="btn btn-info" >Ir al Inicio</button>
            </div>
        </div>

    </div>

</div>
<div class="modal fade" id="modal-default" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Informacion</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="visor" style="width:100%; box-sizing: border-box; justify-content:space-between; align-items:center ">
                <p id="animacion">Generando Reporte ........ </p>
                <a href="<?php echo BASE_URL ?>application/public/excel/MetaResumenGirasol2024-2025.xls" id="btn-descarga" ><button id="reporte" class="btn btn-default" style="visibility: hidden;" >Descargar Reporte</button></a>             
            </div>
        </div>
        <div class="modal-footer justify-content-between">
            
        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>