<div class="row">
<div class="col-lg-12">
	<form name="form_credito_agregar" method="post" id="form_credito_agregar" action="<?php echo BASE_URL ?>creditos/credito/agregar/"  >
	<input name="guardar" id="guardar" type="hidden" value="1" />
	
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title"><i class="fas fa-info"></i> Información de Solicitud</span>
           
		</div>
		<div class="card-body">
            <div class="callout callout-info"> 
                <div class="row">
                        <div class="form-group col-md-2">
                            <label>*Fecha de Solicitud:</label>
                            <input type="date" class="form-control "  name="fechaSolicitud" id="fechaSolicitud"   />
                        </div>
                        
                        <div class="form-group col-md-2">
                        <label>*Id Fiscal:</label>
                        <div class="input-group">
                            <input type="text"   class="form-control "  name="idFiscal" id="idFiscal"  />
                            <span class="input-group-append">
                                <button type="button" class="btn btn-info "  data-toggle="modal" data-target=".bs-example-modal-lg"  data-id=""  ><i class="fa  fa-search"></i></button>
                            </span>
                        </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label>*Productor :</label>
                            <input type="text"   class="form-control "  name="nombProductor" id="nombProductor" readonly  />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Evaluación :</label>
                            <input type="text"   class="form-control "  name="evaluacionProductor" id="evaluacionProductor" readonly  />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Deudas :</label>
                            <input type="text"   class="form-control "  name="deuda" id="deuda" readonly  />
                        </div>
                       
                </div>
            </div>
            <hr>
			
            <div class="callout callout-warning"> 
                <div class="row">   
                    <div class="form-group col-md-4">
                        <label>*Programa de Financiamiento :</label>
                        <select name="plan" id="plan" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->programa) && count($this->programa)): ?>
                            <?php foreach ($this->programa as $val): ?>
                            
                            <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['nombre'])  ?></option>
                           <?php endforeach; ?>
                            <?php endif; ?>    

                            
                        </select>  
                    </div>                    
                    
                    <div class="form-group col-md-2">
                        <label>*Inicio del Programa:</label>
                        <input type="date" class="form-control "  name="fechaInicio" id="fechaInicio"  disabled />
                    </div>
                    <div class="form-group col-md-2">
                        <label>*Final del Programa:</label>
                        <input type="date" class="form-control "  name="fechaFinal" id="fechaFinal"  disabled />
                    </div>
                    <div class="form-group col-md-2">
                        <label>*Ha Máximas :</label>
                        <input type="number" class="form-control "  name="haMax" id="haMax" disabled />
                    </div>
                    <div class="form-group col-md-1">
                        <label>*Interés:</label>
                        <input type="number" class="form-control "  name="tasaInteres" id="tasaInteres"  disabled /> 
                    </div>
                    <div class="form-group col-md-1"> 
                        <label>*Moneda  :</label>
                        <input type="text" class="form-control "  name="moneda" id="moneda" disabled  />  
                    </div>
                </div>
            </div>
            <hr>
            <div class="callout callout-danger"> 
                <div class="row">
                        <div class="form-group col-md-4">
                            <label>*Unidad de Producción :</label>
                            					
						    <select class="form-control select2" style="width: 100%;" name="finca" id="finca" >
                            <?php if(isset($this->finca) && count($this->finca)): ?>
                                <?php foreach ($this->finca as $val): ?>
                                
                                <option value="<?php echo $val['id']  ?>"><?php echo strtoupper(utf8_encode($val['nombre']).' - ') .utf8_encode($val['dirSector']).'   ('.utf8_encode($val['nombrePropietario']).') '  ?></option>
                                
                                <?php endforeach; ?>
                                <?php endif; ?>

                            </select>
					    </div>  
                        
                        <div class="form-group col-md-2">
                            <label>*Superficie(Ha) Solicitada :</label>
                            <input type="number"   class="form-control "  name="superfSolicitada" id="superfSolicitada"  />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Plan de Trabajo :</label>
                            <select class="form-control " style="width: 100%;" name="planTrabajo" id="planTrabajo" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->planTrabajo) && count($this->planTrabajo)): ?>
                                <?php foreach ($this->planTrabajo as $val): ?>
                                
                                <option value="<?php echo $val['plan']  ?>"><?php echo strtoupper(utf8_encode($val['plan']))  ?></option>
                            
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label>*Comentarios :</label>
                            <textarea   class="form-control "  name="observacion" id="observacion"  ></textarea>
                        </div>
                       
                </div>
            </div> 
            <hr>
            <div class="callout callout-success"> 
                <div class="row"> 
                    <div class="form-group col-md-2">
                        <label>*Fecha Estimada de Cosecha:</label>
                        <input type="date" class="form-control "  name="fechaCosecha" id="fechaCosecha"   value="" />
                    </div> 
                    <div class="form-group col-md-2">
                        <label>Producción Estimda Kg:</label>
                        <input type="number" class="form-control "  name="prodEstimada" id="prodEstimada" value="" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>Ha. Sembradas:</label>
                        <input type="number" class="form-control "  name="haSembrada" id="haSembrada"   value="" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>Ha. Efectivas:</label>
                        <input type="number" class="form-control "  name="haEfectivas" id="haEfectivas"   value="" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>Cant. de Visitas:</label>
                        <input type="number" class="form-control "  name="cantVisitas" id="cantVisitas"   value="" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>Cant. de Imagenes:</label>
                        <input type="number" class="form-control "  name="cantImagenes" id="cantImagenes"  disabled value="" />
                    </div>                
                </div>
            </div>           
            
            			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>creditos/credito/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      
      <div class="modal-body">
          <div class="card">
              <div class="card-header">
                <h3></h3>
                <div class="card-tools">
                    <div class="input-group input-group-sm">
                        <input type="text" id="search_productor" name="search_productor" class="form-control float-right search" />
                        <div class="input-group-append">
                            <button type="button" name="search" id="search" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
              </div>                      
              <div class="card-body table-responsive p-0">
                    
                        
                          <table class="table table-hover text-nowrap" id="tabla">
                              <thead>
                                  <tr class="bg-light-blue-active" >
                                      <th width='80'>Id Fiscal</th>
                                      <th width='400'>Nombre</th>
                                      <th width='100'>Teléfono</th>
                                      <th></th>
                                  </tr>
                              </thead>
                              <tbody>

                              </tbody>
                            </table>          
                    
                  
                </div>
               <div class="card-footer">
                    <div>
                      <button><i class="fa fa-print"></i></button>
                  </div>
               </div> 
          </div>
      </div>
    </div>
  </div>
</div>