<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">

            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <select class="custom-select"  data-sortorder="" id="programa" name="programa">
                        <option value="0">-Seleccione-</option>
                        <?php if(isset($this->programa) && count($this->programa)): ?>
                        <?php foreach ($this->programa as $val): ?>
                        
                        <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['rubro']). ' - ' .strtoupper($val['ciclo']).' - '.date('Y',strtotime($val['fechaInicio']))  ?></option>
                        
                        <?php endforeach; ?>
                        <?php endif; ?>     
                        </select>
                    </div>
                    <div class="col-md-9">
                        <div class="card card-secondary  card-outline">
                            <div class="card-header">
                                <h4><span class="card-title"><i class="fas fa-navicon"> </i> Créditos por aprobación</span></h4>
                            </div>
                            <div class="card-body p-0">
                                <table class="table table-striped" id="tabla_creditos">
                                    <thead>
                                        <tr >
                                            <th style="width: 10px" >Id</th>
                                            <th>Solicitante</th>
                                            <th>Unidad de producción</th>
                                            <th>Rubro</th>
                                            <th>Superficie Solicitada</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>

                                </table>
                            </div>
                        </div>    
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<div id="modal-xl" class="modal fade" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
        <form name="form_aprobacion" id="form_aprobacion" method="post" action="<?php echo BASE_URL ?>creditos/credito/aprobacion">
            <input name="guardar" id="guardar" type="hidden" value="3" />
            <input name="idCredito"   id="idCredito" type="hidden" value="0">
            <div class="modal-body">
                   <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-2">
                                    <label>*Fecha de Solicitud:</label>
                                    <input type="date" class="form-control form-control-sm "  name="fechaSolicitud" id="fechaSolicitud" readonly  />
                                </div>
                                <div class="form-group col-md-2">
                                    <label>*Id Fiscal:</label>
                                    <input type="text" class="form-control form-control-sm "  name="idFiscal" id="idFiscal"  readonly />
                                </div>
                                <div class="form-group col-md-4">
                                    <label>*Productor :</label>
                                    <input type="text"   class="form-control form-control-sm"  name="nombProductor" id="nombProductor" readonly  />
                                </div>
                                <div class="form-group col-md-4">
                                    <label>*Unidad de Producción :</label>
                                    <input type="text"   class="form-control form-control-sm"  name="unidadProduccion" id="unidadProduccion" readonly  />
                                </div>
                                <div class="form-group col-md-2">
                                    <label>*Superficie Solicitada :</label>
                                    <input type="text"   class="form-control form-control-sm"  name="superficieSolicitada" id="superficieSolicitada" readonly  />
                                </div>
                                <div class="form-group col-md-2">
                                    <label>*Superficie Aprobada :</label>
                                    <input type="text"   class="form-control form-control-sm"  name="superficieAprobada" id="superficieAprobada"   />
                                </div>
                                <div class="form-group col-md-2">
                                    <label>*Fecha Aprobación :</label>
                                    <input type="date"   class="form-control form-control-sm"  name="fechaAprobacion" id="fechaAprobacion"   />
                                </div>
                                <div class="form-group col-md-4">
                                    <label>*Técnico Asignado :</label>
                                    <select class="form-control form-control-sm"   id="tecnico" name="tecnico">
                                    <option value="0">-Seleccione-</option>
                                   
                                    <?php if(isset($this->tecnico) && count($this->tecnico)): ?>
                                    <?php foreach ($this->tecnico as $val): ?>
                                    
                                    <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['nombre']). ' -  Tlf:' .strtoupper($val['telefonos'])  ?></option>
                                    
                                    <?php endforeach; ?>
                                    <?php endif; ?> 
                                    </select>     
                                </div>
                                <div class="form-group col-md-2">
                                    <label>Estado:</label>    
                                        <select name="estado" id="estado" class="form-control form-control-sm">
                                            <option value="-">-Seleccione-</option>
                                            <option value="APROBADO">APROBADO</option>
                                            <option value="RECHAZADO">RECHAZADO</option>
                                        </select>
                                </div>
                                <div class="form-group col-md-12">
                                    <label>Comentario :</label>
                                    <textarea name="comentario" id="comentario" class="form-control form-control-sm" rows="2"></textarea>
                                </div>
                            </div>
                        </div>  
                   </div> 
                   <div class="" style="overflow-y:scroll;padding:10px;" id="accordion">
                        <div class="row">                
                        <div class="col-md-6">                
                        <div class="card card-defauld" >
                                <div class="card-header ">
                                    <h5 class="card-title" ><a class="d-block w-100 collapsed" data-toggle="collapse" href="#collapseOne" aria-expanded="false">Fase Preparacion</a></h5>          
                                </div>
                                <div class="collapse" id="collapseOne" data-parent="#accordion">              
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="card card-info">
                                                <div class="card-header">Programado</div>
                                                <div class="card-body" id="preparacion">

                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="card card-warning">
                                                <div class="card-header">Real</div>
                                                <div class="card-body" id="preparacionReal">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </div> 
                        </div>
                        </div>
                        <div class="col-md-6">   
                        <div class="card card-defauld" >
                            <div class="card-header">
                                <h3 class="card-title"><a class="d-block w-100 collapsed" data-toggle="collapse" href="#collapsetwo" aria-expanded="false">Fase Siembra</a></h3>          
                            </div>
                            <div class="collapse" id="collapsetwo" data-parent="#accordion">              
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="card card-info">
                                            <div class="card-header">Programado</div>
                                            <div class="card-body" id="siembra">

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="card card-warning">
                                            <div class="card-header">Real</div>
                                            <div class="card-body" id="siembraReal">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div> 
                        </div>
                        </div>
                        </div>
                        <div class="row">
                        <div class="col-md-6">
                        <div class="card card-default" >
                            <div class="card-header">
                                <h4 class="card-title"><a class="d-block w-100 collapsed" data-toggle="collapse" href="#collapsethree" aria-expanded="false">Fase Mantenimiento</a></h4>          
                            </div> 
                            <div class="collapse" id="collapsethree" data-parent="#accordion">             
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="card card-info">
                                            <div class="card-header">Programado</div>
                                            <div class="card-body" id="mantenimiento">

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="card card-warning">
                                            <div class="card-header">Real</div>
                                            <div class="card-body" id="mantenimientoReal">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div> 
                        </div>
                        </div> 
                        <div class="col-md-6">               
                        <div class="card card-default" >
                            <div class="card-header">
                                <h3 class="card-title"><a class="d-block w-100 collapsed" data-toggle="collapse" href="#collapsefour" aria-expanded="false">Fase Cosecha</a></h3>          
                            </div>
                            <div class="collapse" id="collapsefour" data-parent="#accordion">              
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="card card-info">
                                            <div class="card-header">Programado</div>
                                            <div class="card-body" id="cosecha">

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="card card-warning">
                                            <div class="card-header">Real</div>
                                            <div class="card-body" id="cosechaReal">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div> 
                        </div>
                        </div>
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
             <button type="button" class="btn btn-xs btn-app bg-danger" data-dismiss="modal"><i class="fa fa-reply"></i>Close</button>
             <button type="button" class="btn btn-xs btn-app bg-olive disabled color-palette" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
            </div>
        </form>                                
        </div>
    </div>                            

</div>