<div class="row" bis_skin_checked="1">    
    <div class="col-md-3" bis_skin_checked="1">

        <div class="card card-secondary card-outline" bis_skin_checked="1">
            <div class="card-body box-profile" bis_skin_checked="1">
                <div class="text-center" bis_skin_checked="1">
                    
                </div>
                <h3 class="profile-username text-center"><?php echo $this->credito[0]['productores_nombreProductor'] ?></h3>
                <p class="text-muted text-center">Productor</p>
                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b>Despachos de Insumos</b> <button class="btn btn-secondary imprimir-despacho float-right" data-toggle="modal" data-target="#modal-xl-desp" value="<?php echo $this->credito[0]['id'] ?>" > <?php echo $this->totales['despachos'] ?>  <i class="fa-regular fa-file"></i></button>
                    </li>
                    <li class="list-group-item">
                        <b>Recepciones de Cosecha</b><button class="btn btn-secondary imprimir-recepcion float-right" data-toggle="modal" data-target="#modal-xl-desp" value="<?php echo $this->credito[0]['id'] ?>" > <?php echo $this->totRecepCos ?>  <i class="fa-regular fa-file"></i></button>
                    </li>
                    
                </ul>
                
                <h4 class="h4">Operaciones Especiales</h4>
                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b>Extensiones de Crédito</b> <a class="float-right"><?php echo $this->totExtCred ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>Inspecciones Técnicas</b> <a class="float-right"><?php echo $this->credito[0]['cantVisitas'] ?></a>
                    </li>
                    
                </ul>

                <a href="#" class="btn btn-secondary" data-toggle="modal" data-target="#modal-lg-ext" title="Agregar solicitud de extencion de credito"><i class="fa-solid fa-layer-group"></i></a>
            </div>

        </div>   
        <div class="card card-secondary" bis_skin_checked="1">
        <div class="card-header" bis_skin_checked="1">
            <h3 class="card-title"><i class="fa  fa-sitemap"></i> <?php echo $this->credito[0]['fincas_nombre'] ?></h3>
        </div>

        <div class="card-body" bis_skin_checked="1">
                 <strong><i class="fas fa-map-marker-alt mr-1"></i> Locación</strong>
            <p class="text-muted"><?php echo $this->finca[0]['dirSector'].' - '.$this->finca[0]['direccion'] ?></p>
            <hr>
            <strong><i class="fas fa-book mr-1"></i> Propietario:</strong>
            <p class="text-muted"><?php echo $this->finca[0]['nombrePropietario'] ?></p>
            <hr>
            <strong><i class="fa fa-map-o"></i> Superficie Registrada:</strong>
            <p class="text-muted"><?php echo $this->finca[0]['superficie'] ?> Ha</p>
            <hr>
            
            <strong><i class="far fa-file-alt mr-1"></i> Notas</strong >
            <p class="text-muted"><?php echo $this->finca[0]['comentarios'] ?></p>
        </div>

</div>
        

</div>


    <div class="col-md-9">
        <div class="card card-secondary card-outline" >
            <div class="card-header">
                 <h3 class="card-title"><strong> <i class="fa  fa-calendar-o"></i> Programa de Financiamiento </strong><?php echo $this->credito[0]['ProgFinanc'] ?> | <strong> <i class="fa fa-check-circle"></i> Aprobado el </strong>: <?php echo date('d-m-Y',strtotime($this->credito[0]['creditos_fechaAprobacion'])) ?>  |  <strong> <i class="fa-solid fa-signal"></i> Estado Actual </strong>: <?php echo $this->credito[0]['estado'] ?></h3>
                 <div class="card-tools">
                    <button class="btn btn-default" value="<?php echo $this->credito[0]['id'] ?>" data-toggle="modal" data-target="#modal-lg" title="Agregar Cuenta por Cobrar"><i class="fa fa-plus"></i></button>
                    <button class="btn btn-default imprimir" value="<?php echo $this->credito[0]['id'] ?>" data-toggle="modal" data-target="#modal-xl"><i class="fa fa-print"></i></button>
                    <a href="https://simind.iot-ve.com/php/expEdoCtaXls.php?IdCredito=<?php echo $this->credito[0]['id'] ?>" ><button class="btn btn-default" value="<?php echo $this->credito[0]['id'] ?>" title="Exportar dato a Excel" ><i class="fa-regular fa-file-excel"></i></button></a>
                </div>   
            </div>
            <div class="card-body">
                <table class="table table-sm" id="ecCredito" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Id</th>
                        <th width="120">Emisión</th>
                        <th>Concepto</th>
                        <th width="120" class="text-center">Débito</th>
                        <th width="120" class="text-center">Crédito</th>
                        <th width="120" class="text-center">Saldo</th>
                        
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id'] ?></td>
                            
                            <td><?php echo date('d-m-Y',strtotime($val['emision'])) ?></td>
                
                            <td><?php echo strtoupper($val['concepto']) ?></td>
                            <td class="text-right"><span><?php echo number_format($val['debito'],2,'.',',') ?></span></td>
                            <td class="text-right"><span><?php echo number_format($val['credito'],2,'.',',') ?></span></td>
                            <td class="text-right"><span ><?php echo number_format($val['saldo'],2,'.',',') ?></span>
                            
                            </td>
                                
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                    
                    </tfoot>
                </table>
            </div>
            <div class="card-footer">
                <?php if($this->credito[0]['estado']!='LIQUIDADO'): ?>
                <div class="callout callout-warning" bis_skin_checked="1">
                  <h5>Intereses generados a la fecha (<?php echo date('d-m-Y')  ?>)</h5>

                  <p class="text-right h3 text-warning"> <?php echo $this->intereses ?> $</p>
                </div>
                <?php endif ?>
            </div>

            
        </div>   
        
        <div class="row">
            <?php if($this->configCal): ?>
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-info elevation-1"><i class="fa-solid fa-seedling"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Semillas Disponible</span>
                            <span class="info-box-number">
                            <?php echo number_format($this->cupos['semillaDisponible']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-warning elevation-1"><i class="fa-solid fa-flask-vial"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Agroquimicos Disponibles</span>
                            <span class="info-box-number">
                                <?php echo number_format($this->cupos['agroquimicoDisponible']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-primary elevation-1"><i class="fa-solid fa-bottle-droplet"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Fertilizantes Disponibles</span>
                            <span class="info-box-number">
                            <?php echo number_format($this->cupos['fertilizanteDisponible']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-success elevation-1"><i class="fa-solid fa-comments-dollar"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Otros Gastos Disponibles</span>
                            <span class="info-box-number">
                            <?php echo number_format($this->cupos['otrosDisponibles']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                    
                </div>
            <?php else:  ?>
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-info elevation-1"><i class="fa-solid fa-credit-card"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Total Aprobado</span>
                            <span class="info-box-number">
                            <?php echo number_format($this->cupos['totalAprobado']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-danger elevation-1"><i class="fa-solid fa-comments-dollar"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Total Consumido</span>
                            <span class="info-box-number">
                                <?php echo number_format($this->cupos['totalConsumido']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="info-box" bis_skin_checked="1">
                        <span class="info-box-icon bg-success elevation-1"><i class="fa-solid fa-file-invoice-dollar"></i></span>
                        <div class="info-box-content" bis_skin_checked="1">
                            <span class="info-box-text">Total Disponibles</span>
                            <span class="info-box-number">
                            <?php echo number_format($this->cupos['montoDisponible']/1000,2,".",",") ?>
                            <strong>$</strong>
                            </span>
                        </div>

                    </div>
                </div>

            <?php endif ?>    
        </div>

    </div>      
        
</div>


<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title" id="cab_titulo"> <button type="button" class="btn btn-primary" id="imprimir" title="Click para Imprimir"><i class="fa fa-print"></i></button></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div id="cxc" ></div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
               
                <button type="button" class="btn btn-primary" id="imprimir" title="Click para Imprimir"><i class="fa fa-print"></i></button>
                <button type="button" id="go_ini_cxc" class="btn btn-info" >Ir al Inicio</button>
            </div>
        </div>

    </div>

</div>



<div class="modal fade" id="modal-lg" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-lg" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title">Agregar Cuenta por Cobrar</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div class="card card-secondary">
                    <div class="card-body">
                        <form name="form-cxc" id="form-cxc" method="post" action="<?php echo BASE_URL ?>creditos/credito/cxc/">
                        <input name="guardar_cxc" id="guardar_cxc" type="hidden" value="1" />
                        <input name="credito_id" id="credito_id" type="hidden" value="<?php echo $this->credito[0]['id'] ?>" />
                        <div>
                            <label>Fecha</label>
                            <div class="input-group mb-3" bis_skin_checked="1">
                                <div class="input-group-prepend" bis_skin_checked="1">
                                    <span class="input-group-text"><i class="fa-solid fa-calendar-days"></i></span>
                                </div>
                                <input type="date" class="form-control" placeholder="--/--/----" name="fechacxc" id="fechacxc">
                            </div>
                        </div>
                        <div>
                            <div class="form-group" bis_skin_checked="1">
                                <label>Tipo Documento</label>
                                <select class="custom-select" name="tipocxc" id="tipocxc">
                                    <option value="0">-Seleccione-</option>
                                    <option value="DEB">Nota de Debito</option>
                                    <option value="CRE">Nota de Credito</option>
                                </select>
                            </div>
                        </div>
                        <div>
                            <label>Concepto</label>
                            <div class="input-group mb-3" bis_skin_checked="1">
                                <div class="input-group-prepend" bis_skin_checked="1">
                                    <span class="input-group-text"><i class="fa-solid fa-file-prescription"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Concepto" name="conceptocxc" id="conceptocxc">
                            </div>
                        </div>
                        <div>
                            <label>Monto</label>
                            <div class="input-group mb-3" bis_skin_checked="1">
                                <div class="input-group-prepend" bis_skin_checked="1">
                                    <span class="input-group-text"><i class="fa-solid fa-money-bill"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Monto" name="montocxc" id="montocxc" value="00.0" >
                            </div>

                        </div>
                        <hr>
                        <div>
                            <div class="custom-control custom-checkbox" bis_skin_checked="1">
                                <input class="custom-control-input" type="checkbox" id="customCheckbox2" name="aplicar_cupo" value="1">
                                <label for="customCheckbox2" class="custom-control-label">Descontar monto al cupo disponible del credito</label>
                            </div>
                        </div>
                        </form>
                    </div>

                </div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
                <button type="button" class="btn btn-default"  data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="agregarcxc" >Guardar</button>
            </div>
        </div>

    </div>

</div>







<div class="modal fade" id="modal-lg-ext" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-lg" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title">Agregar Extencion de Credito</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div class="card card-secondary">
                    <div class="card-body">
                        <form name="form-ext" id="form-ext" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL ?>creditos/credito/adicional/">
                        <input name="guardar_adicional" id="guardar_adicional" type="hidden" value="1" />
                        <input name="credito_id" id="credito_id" type="hidden" value="<?php echo $this->credito[0]['id'] ?>" />
                        <div>
                            <label>Fecha Solicitud</label>
                            <div class="input-group mb-3" bis_skin_checked="1">
                                <div class="input-group-prepend" bis_skin_checked="1">
                                    <span class="input-group-text"><i class="fa-solid fa-calendar-days"></i></span>
                                </div>
                                <input type="date" class="form-control" placeholder="--/--/----" name="fechaext" id="fechaext">
                            </div>
                        </div>
                        <div>
                            <div class="form-group" bis_skin_checked="1">
                                <label>Técnico</label>
                                <select class="custom-select" name="tecnico" id="tecnico">
                                    <option value="0">-Seleccione-</option>
                                    <?php if(isset($this->tecnico) && count($this->tecnico)): ?>
                                    <?php foreach ($this->tecnico as $val): ?>
                                    
                                    <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['nombre']). ' -  Tlf:' .strtoupper($val['telefonos'])  ?></option>
                                    
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div>
                            <div class="form-group" bis_skin_checked="1">
                                <label>Motivo de la Solicitud</label>
                                <select class="custom-select" name="motivo" id="motivo">
                                    <option value="0">-Seleccione-</option>
                                    <?php if(isset($this->motExt) && count($this->motExt)): ?>
                                    <?php foreach ($this->motExt as $val): ?>
                                    
                                    <option value="<?php echo strtoupper($val) ?>"><?php echo strtoupper($val)  ?></option>
                                    
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div>
                            <label>Comentarios</label>
                            <textarea class="form-control" rows="3" name="informe" id="informe"></textarea> 
                        </div>

                        <div class="form-group" bis_skin_checked="1">
                            <label for="exampleInputFile">Imagen Informe</label>
                            <div class="input-group" bis_skin_checked="1">
                                <div class="custom-file" bis_skin_checked="1">
                                    <input type="file" class="custom-file-input" id="exampleInputFile" name="imagen">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                            </div>
                        </div>
                        <div>
                            <label>Hectareas Adicionales</label>
                            <div class="input-group mb-3" bis_skin_checked="1">
                                <div class="input-group-prepend" bis_skin_checked="1">
                                    <span class="input-group-text"><i class="fa-solid fa-money-bill"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ha" name="hectareasAdicionales" id="hectareasAdicionales" value="00.0" disabled >
                            </div>
                        </div>                
                        <div>
                            <label>Monto</label>
                            <div class="input-group mb-3" bis_skin_checked="1">
                                <div class="input-group-prepend" bis_skin_checked="1">
                                    <span class="input-group-text"><i class="fa-solid fa-money-bill"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Monto" name="montoext" id="montoext" value="00.0" disabled >
                            </div>
                        </div>

                        </form>
                    </div>

                </div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
                <button type="button" class="btn btn-default"  data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="agregarext" >Solicitar Aprobacion</button>
            </div>
        </div>

    </div>
</div>


<div class="modal fade" id="modal-xl-desp" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title"> <button type="button" class="btn btn-primary" id="imprimir-dsp" title="Click para Imprimir" ><i class="fa fa-print"></i></button></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div id="despacho" ></div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
               
                <button type="button" class="btn btn-primary" id="imprimir-dsp" title="Click para Imprimir"><i class="fa fa-print"></i></button>
            </div>
        </div>

    </div>

</div>
