<div class="row">
<div class="col-lg-12">
	<form name="form_credito_editar" method="post" id="form_credito_editar" action="<?php echo BASE_URL ?>creditos/credito/editar/"  >
	<input name="guardar" id="guardar" type="hidden" value="2" />
    <input name="tecnico" id="tecnico" type="hidden" value="<?php echo (!empty($this->credito[0]['idTecnico']))?$this->credito[0]['idTecnico']:"" ?>"" />
    <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->credito[0]['id']))?$this->credito[0]['id']:"" ?>" />
	
	<div class="card card-default">
		<div class="card-header">
            <span class="card-title">Informacion de Solicitud</span>
           
		</div>
		<div class="card-body">
            <div class="callout callout-info"> 
                <div class="row">
                        <?php if(strtoupper($this->credito[0]['estado'])=='RECHAZADO'): ?>
                        <div class="ribbon-wrapper ribbon-xl" bis_skin_checked="1">
                            <div class="ribbon bg-danger text-xl" bis_skin_checked="1"> RECHAZADO </div>
                        </div>
                        <?php endif ?> 
                        <div class="form-group col-md-2">
                            <label>*Fecha de Solicitud:</label>
                            <input type="date" class="form-control "  name="fechaSolicitud" id="fechaSolicitud" value="<?php echo (!empty($this->credito[0]['fechaSolicitud']))?$this->credito[0]['fechaSolicitud']:"" ?>"  />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Id Fiscal:</label>
                            <input type="text"   class="form-control "  name="idFiscal" id="idFiscal"  value="<?php echo (!empty($this->credito[0]['idFiscalProductor']))?$this->credito[0]['idFiscalProductor']:"" ?>"  />
                        </div>
                        <div class="form-group col-md-4">
                            <label>*Productor :</label>
                            <input type="text"   class="form-control "  name="nombProductor" id="nombProductor" readonly  value="<?php echo (!empty($this->credito[0]['productores_nombreProductor']))?$this->credito[0]['productores_nombreProductor']:"" ?>" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Evaluación :</label>
                            <input type="text"   class="form-control "  name="evaluacionProductor" id="evaluacionProductor" readonly value="<?php echo (!empty($this->credito[0]['']))?$this->credito[0]['']:"" ?>" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Deudas :</label>
                            <input type="text"   class="form-control "  name="deuda" id="deuda" readonly value="<?php echo (!empty($this->credito[0]['']))?$this->credito[0]['']:"" ?>" />
                        </div>
                       
                </div>
            </div>
            <hr>
			
            <div class="callout callout-warning"> 
                <div class="row">   
                    <div class="form-group col-md-4">
                        <label>*Plan de Financiamiento :</label>
                        <select name="plan" id="plan" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->programa) && count($this->programa)): ?>
                            <?php foreach ($this->programa as $val): ?>
                            <?php if($val['id']== $this->credito[0]['idProgFinanc']): ?>
                            <option value="<?php echo $val['id']  ?>" selected><?php echo strtoupper($val['nombre'])  ?></option>
                            <?php else: ?>
                            <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['nombre'])  ?></option>        
                            <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>    

                            
                        </select>  
                    </div>                    
                    
                    <div class="form-group col-md-2">
                        <label>*Inicio del Programa:</label>
                        <input type="date" class="form-control "  name="fechaInicio" id="fechaInicio"  disabled value="<?php echo (!empty($this->progFi[0]['fechaInicio']))?$this->progFi[0]['fechaInicio']:"" ?>" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>*Final del Programa:</label>
                        <input type="date" class="form-control "  name="fechaFinal" id="fechaFinal"  disabled value="<?php echo (!empty($this->progFi[0]['fechaFinal']))?$this->progFi[0]['fechaFinal']:"" ?>" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>*Ha Máximas :</label>
                        <input type="number" class="form-control "  name="haMax" id="haMax" disabled  value="<?php echo (!empty($this->progFi[0]['hectMax']))?$this->progFi[0]['hectMax']:"" ?>" />
                    </div>
                    <div class="form-group col-md-1">
                        <label>*Interés %:</label>
                        <input type="number" class="form-control "  name="tasaInteres" id="tasaInteres"  disabled value="<?php echo (!empty($this->progFi[0]['tasaInteres']))?$this->progFi[0]['tasaInteres']:"" ?>" /> 
                    </div>
                    <div class="form-group col-md-1"> 
                        <label>*Moneda  :</label>
                        <input type="text" class="form-control "  name="moneda" id="moneda" disabled  value="<?php echo (!empty($this->progFi[0]['moneda']))?$this->progFi[0]['moneda']:"" ?>" />  
                    </div>
                </div>
            </div>
            <hr>
            <div class="callout callout-danger"> 
                <div class="row">
                        <div class="form-group col-md-4">
                            <label>*Unidad de Producción :</label>
                            <select class="form-control select2" style="width: 100%;" name="finca" id="finca" >
                                <option value="0">-Seleccione-</option>
                                <?php if(isset($this->finca) && count($this->finca)): ?>
                                <?php foreach ($this->finca as $val): ?>
                                <?php if($val['id'] == $this->credito[0]['idFinca']): ?>
                                    <option value="<?php echo $val['id']  ?>" selected ><?php echo strtoupper(utf8_encode($val['nombre']).' - ') .utf8_encode($val['dirSector']).'   ('.utf8_encode($val['nombrePropietario']).') '  ?></option>
                                <?php else: ?>    
                                    <option value="<?php echo $val['id']  ?>"><?php echo strtoupper(utf8_encode($val['nombre']).' - ') .utf8_encode($val['dirSector']).'   ('.utf8_encode($val['nombrePropietario']).') '  ?></option>
                                <?php endif ?>
                                <?php endforeach; ?>
                                <?php endif; ?>                            
                            </select>  
                        </div>
                        
                        <div class="form-group col-md-2">
                            <label>*Superficie(Ha) Solicitada :</label>
                            <input type="number"   class="form-control "  name="superfSolicitada" id="superfSolicitada" value="<?php echo (!empty($this->credito[0]['creditos_superficieSolicitada']))?$this->credito[0]['creditos_superficieSolicitada']:"" ?>" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>*Plan de Trabajo :</label>
                            <select class="form-control " style="width: 100%;" name="planTrabajo" id="planTrabajo" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->planTrabajo) && count($this->planTrabajo)): ?>
                                <?php foreach ($this->planTrabajo as $val): ?>
                                    <?php if($val['plan'] == $this->credito[0]['planTrabajo']): ?>
                                        <option value="<?php echo $val['plan']  ?>" selected><?php echo strtoupper(utf8_encode($val['plan']))  ?></option>
                                    <?php else: ?>
                                        <option value="<?php echo $val['plan']  ?>"><?php echo strtoupper(utf8_encode($val['plan']))  ?></option>    
                                    <?php endif; ?>    
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </select>
                        </div>
                        
                        <div class="form-group col-md-4">
                            <label>*Comentarios :</label>
                            <textarea   class="form-control "  name="observacion" id="observacion"   ><?php echo (!empty($this->credito[0]['comentario']))?$this->credito[0]['comentario']:"" ?></textarea>
                        </div>
                       
                </div>
            </div>
            <hr>
            <div class="callout callout-success"> 
                <div class="row"> 
                    <div class="form-group col-md-2">
                        <label>*Fecha de Cosecha:</label>
                        <input type="date" class="form-control "  name="fechaCosecha" id="fechaCosecha"   value="<?php echo (!empty($this->credito[0]['fechaEstCosecha']))?$this->credito[0]['fechaEstCosecha']:"" ?>" />
                    </div> 
                    <div class="form-group col-md-2">
                        <label>Producción Estimda Kg:</label>
                        <input type="number" class="form-control "  name="prodEstimada" id="prodEstimada" value="<?php echo (!empty($this->credito[0]['produccionEstimada']))?$this->credito[0]['produccionEstimada']:"" ?>" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>*Ha Aprobada :</label>
                        <input type="number"   class="form-control "  name="superfAprobada" id="superfAprobada" value="<?php echo (!empty($this->credito[0]['creditos_superficieAprobada']))?$this->credito[0]['creditos_superficieAprobada']:"" ?>" />
                        <input type="hidden"   class="form-control "  name="superfCosechada" id="superfCosechada" value="<?php echo (!empty($this->credito[0]['creditos_superficieCosechada']))?$this->credito[0]['creditos_superficieCosechada']:"" ?>" />        
                    </div>
                    <div class="form-group col-md-1">
                        <label>Ha. Sembrada:</label>
                        <input type="number" class="form-control "  name="haSembrada" id="haSembrada"   value="<?php echo (!empty($this->credito[0]['creditos_superficieSembrada']))?$this->credito[0]['creditos_superficieSembrada']:"0" ?>" />
                    </div>
                    <div class="form-group col-md-1">
                        <label>Ha. Efectivas:</label>
                        <input type="number" class="form-control "  name="haEfectivas" id="haEfectivas"   value="<?php echo (!empty($this->credito[0]['creditos_superficieEfectiva']))?$this->credito[0]['creditos_superficieEfectiva']:"0" ?>" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>Cantidad de Visitas:</label>
                        <input type="number" class="form-control "  name="cantVisitas" id="cantVisitas"   value="<?php echo (!empty($this->credito[0]['cantVisitas']))?$this->credito[0]['cantVisitas']:"" ?>" />
                    </div>
                    <div class="form-group col-md-2">
                        <label>Cantidad de Imagenes:</label>
                        <input type="number" class="form-control "  name="cantImagenes" id="cantImagenes"  disabled value="<?php echo (!empty($this->credito[0]['fechaFinal']))?$this->credito[0]['fechaFinal']:"" ?>" />
                    </div>                
                </div>
            </div>
            
            			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar" <?php echo (strtoupper($this->credito[0]['estado'])=='RECHAZADO')?'disabled':"" ?>><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>creditos/credito/index/""><button type="button" class="btn btn-xs btn-app" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
