<div class="row">
    <div class="col-12">
        <form name="form_credito_eliminar" method="post" id="form_credito_eliminar" action="<?php echo BASE_URL ?>creditos/credito/eliminar/">
        <input name="eliminar" id="eliminar" type="hidden" value="1" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))? $this->datos[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Eliminacion de Credito</h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta seguro de eliminar el registro de Credito:</h3>
                        <dl class="row">
                            <dt class="col-sm-4">Nombre Productor :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['productores_nombreProductor']))?$this->datos[0]['productores_nombreProductor']:"" ?></dd>
                            <dt class="col-sm-4">Id Fiscal :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['idFiscalProductor']))?$this->datos[0]['idFiscalProductor']:"" ?></dd>
                            <dt class="col-sm-4">Fecha Solicitud  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['fechaSolicitud']))?$this->datos[0]['fechaSolicitud']:"" ?></dd>
                            <dt class="col-sm-4">Id Credito  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['id']))?$this->datos[0]['id']:"" ?></dd>
                            <dt class="col-sm-4">Unidad de Produccion :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['fincas_nombre']))?$this->datos[0]['fincas_nombre']:"" ?></dd>
                            <dt class="col-sm-4">Superficie Solicitada :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['superficieSolicitada']))?$this->datos[0]['superficieSolicitada']:"" ?></dd>
                        </dl>
                </div>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>creditos/credito/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
