<div class="row">
<div class="col-lg-12">
	<form name="form_producto_agregar" method="post" id="form_producto_agregar" action="<?php echo BASE_URL ?>almacen/producto/agregar/"  >
	<input name="guardar" id="guardar" type="hidden" value="1" />
	
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Introduzca información para el nuevo  Producto</span>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="form-group col-md-2">
					<label>*Clasificacion:</label>
					<select name="clasificacion" id="clasificacion" class="form-control">
						<option value="-">-Seleccione-</option>
					<?php if(isset($this->clasificacion) && count($this->clasificacion)): ?>
					<?php foreach ($this->clasificacion as $val): ?>
						<option value="<?php echo $val['grupo']  ?>"><?php echo strtoupper($val['grupo'])  ?></option>
					<?php endforeach; ?>
					<?php endif; ?>
            		</select> 
				</div>
			<div class="form-group col-md-2">
				<label>*Codigo :</label>
				<input name="codigo"  maxlength="100" type="text" class="form-control" id="codigo"  />  
			</div>
			<div class="form-group col-md-2">
				<label title="Esta información será utilizada para los titulos en los reportes en Excel">*Etiqueta Excel:</label>
				<input type="text"  maxlength="100" class="form-control "  name="etiquetaExcel" id="etiquetaExcel" placeholder="Para reportes en Excel "   />
			</div>
          <div class="form-group col-md-6">
				<label>*Descripción:</label>
				<input type="text"  maxlength="100" class="form-control "  name="descripcion" id="descripcion"   />
			</div>
			<div class="form-group col-md-2">
				<label>*Unidad de Medida:</label>
				<input type="text"  maxlength="100" class="form-control "  name="unidadMedida" id="unidadMedida" />
			</div>
          <div class="form-group col-md-2">
				<label>*Presentación:</label>
				<input type="text"  maxlength="100" class="form-control "  name="presentacion" id="presentacion"   />
			</div>
          <div class="form-group col-md-2">
				<label>*Stock Minimo:</label>
				<input type="number"  maxlength="20" class="form-control "  name="exiMinima" id="exiMinima"   />
			</div>
			
			<div class="form-group col-md-5">
				<label>*Comentarios:</label>
				<textarea class="form-control" name="comentarios" id="comentarios" size="100"></textarea>
			</div>
			<div class="form-group col-md-1">
				<label>*Es Consignado:</label>
				<input type="checkbox"   class="form-control "  name="consignado" id="consignado" value="1" />
			</div>
		</div>
      </br>
		
		<div class="row">				
			<div class="col-md-9">
				<div class="card card-secondary">
					<div class="card-header">
						
							<div class="custom-control custom-switch">
								<input type="checkbox" class="custom-control-input" id="customSwitch1">
								<label class="custom-control-label" for="customSwitch1">Gestionar Costos / Precio</label>
							</div>
						
					</div>
					<div class="card-body">
						<div class="row">
							<div class="form-group col-md-2">
								<label>*Costo Ult Compra:</label>
								<input type="text"  maxlength="100" class="form-control text-right"  name="costoUltcpra" id="costoUltcpra"  readonly="true" />
							</div>
							<div class="form-group col-md-2">
								<label>*Costo Promedio:</label>
								<input type="text"  maxlength="100" class="form-control text-right"  name="costoPromedio" id="costoPromedio"  readonly="true" />
							</div>
							<div class="form-group col-md-2">
								<label>*Costo Prorrateado:</label>
								<input type="text"  maxlength="100" class="form-control text-right"  name="costoProrrateado" id="costoProrrateado"  readonly="true" />
							</div>
							<div class="form-group col-md-2">
								<label>*Costo Alcual:</label>
								<input type="text"  maxlength="100" class="form-control text-right"  name="costoActual" id="costoActual"  readonly="true" />
							</div>
							<div class="form-group col-md-2">
								<label>*Costo Actual Mercado:</label>
								<input type="text"  maxlength="100" class="form-control text-right"  name="costoActualMercado" id="costoActualMercado"  readonly="true" />
							</div>

							
							<div class="form-group col-md-2">
								<label>Utilidad:</label>
								<input type="number"  maxlength="20" class="form-control text-right"  name="utilidad" id="utilidad" readonly="true"  />
							</div>
							<div class="form-group col-md-2">
								<label>Utilidad Min:</label>
								<input type="number"  maxlength="20" class="form-control text-right"  name="utilidadMin" id="utilidadMin"  readonly="true" />
							</div>
							<div class="form-group col-md-2">
								<label>Pvp1:</label>
								<input type="number"  maxlength="20" class="form-control text-right"  name="pvp1" id="pvp1"  readonly="true" />
							</div>
							<div class="form-group col-md-2">
								<label>Pvp2:</label>
								<input type="number"  maxlength="20" class="form-control text-right"  name="pvp2" id="pvp2"  readonly="true" />
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card card-secondary">
					<div class="card-header">
						
							<div class="custom-control custom-switch">
								<input type="checkbox" class="custom-control-input" id="customSwitch2">
								<label class="custom-control-label" for="customSwitch2">Gestionar Impuesto</label>
							</div>
						
					</div>
					<div class="card-body">
						<div class="row">
							<div class="form-group col-md-12">
								<label>*IVA <strong>%</strong>:</label>
								<input type="text"  maxlength="100" class="form-control "  name="tasaIva" id="tasaIva"  readonly="true" />
							</div>
													
						</div>
					</div>
				</div>	
			</div>			
		</div>	


		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>almacen/producto/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
  </div>
		  
</div>
    
</form>
</div>
