<div class="row-fluid">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="<?php echo BASE_URL ?>archivo/producto/index/" title="Regresar a Producto"><button ><i class="fa fa-undo"></i></button></a>
                            <span class="navbar-brand" id="agregar"  title="Agregar Nueva Presentación del Producto"><button ><i class="fa fa-plus"></i></button></span>  
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" maxlength="100" name="busqueda" class="form-control" placeholder="Filtrar nombre">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>                        
                        <th width="300">Nombre</th>
                        <th>Unidades</th>
                        <th>Cont. X Unidad</td>
                        <th>Medida</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        
                        <tr>                            
                            <td><?php echo strtoupper($val['nombre_presentacion']) ?></td>
                            <td><?php echo strtoupper($val['cantidad_presentacion']) ?></td>                            
                            <td><?php echo $val['cantidad_uni_med'] ?></td>
                            <td></td>
                            <td>
                                <?php if($val['estatus_det_producto']==1): ?>
                                <a href="<?php echo BASE_URL ?>archivo/producto/desactivarDetalleProducto/<?php echo $val['id_det_producto'] ?>/<?php echo $this->producto['id_producto'] ?>" >   
                                    <button class="eliminar" title="Presione aquí para Desactivar" ><i class="fa fa-toggle-on"></i></button>
                                </a>
                                <?php else: ?>
                                <a href="<?php echo BASE_URL ?>archivo/producto/activarDetalleProducto/<?php echo $val['id_det_producto'] ?>/<?php echo $this->producto['id_producto'] ?>" >    
                                    <button class="eliminar" title="Presione aquí para Activar" ><i class="fa fa-toggle-off"></i></button>
                                </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Agregar Presentación</div>
            <div class="panel-body">
                <form name="relacion" id="relacion" method="post" autocomplete="off" action="">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                     <input name="producto" type="hidden" value="<?php echo $this->producto['id_producto'] ?>" id="prducto">
                    <div class="form-group">
                        <label>*Nombre:</label>
                        <select name="nombre" id="nombre" title="Seleccion la Presentación del Producto" class="form-control" disabled="true" >
                            <option value=""> Seleccione </option>
                            <?php if(count($this->presentacion)): ?>
                                <?php foreach ($this->presentacion as $val): ?>
                                    <option value="<?php echo $val['id_presentacion'] ?>"><?php echo strtoupper($val['nombre_presentacion']) ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>    
                    </div>
                     <button type="submit" class="btn btn-primary" title="Presione Aquí para guardar la Presentación del Producto" disabled="true" id="enviar"><i class="fa fa-floppy-o"></i> Guardar</button>
                     <button type="reset" class="btn btn-danger" title="Presione Aquí para Cancelar" disabled="true" id="cancelar"><i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>