<div class="row">
    <div class="col-12">
        <div class="card">	
			    <div class="card-header">
                    <h3 class="card-title"> Producto:  <?php echo strtoupper($this->productos[0]['descripcion']) ?></h3>
                    <div class="card-tools">
                    <a  href="<?php echo BASE_URL ?>almacen/producto/" title="Presione aquí para AGREGAR un nuevo registro" class=""><button class="btn btn-default btn-sm" ><i class="fa-solid fa-arrow-rotate-left"></i></button></a>
                    </div>
				      
                      
			    </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-bordered table-striped" id="example1" >
                                <thead>
                                    <tr class="bg-secondary color-palette" >
                                    
                                    <th>Almacen</th>
                                    <th>Existencia Actual</th>
                                    <th>Existencia Bloqueada</th>
                                    <th>Existencia Por Entregar</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php if(isset($this->productos) && count($this->productos)) :?>
                                    <?php foreach ($this->productos as $pro) :?>
                                    <tr>
                                        
                                        <td><?php echo strtoupper($pro['nombre_almacen']) ?></td>
                                        <td><?php echo $pro['existenciaActual'] ?></td>
                                        <td><?php echo $pro['existenciaBloqueada'] ?></td>
                                        <td><?php echo $pro['existenciaPorEntregar'] ?></td>
                                        <td><button class="btn btn-default" type="button"><i class="fa-solid fa-right-left"></i></button></td>
                                    </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>    
                                </tbody>
                                <tfoot>
                                
                                </tfoot>
                            </table>
                        </div> 
                        <div class="col-md-6">
                                      

                        </div>
                    </div>       
                    <hr>
                    <p>
                            <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                    </p>
                
                </div>

        </div>
    </div>
        
</div>
