<div class="row">
    <div class="col-12">
        <div class="card">	
			    <div class="card-header">
				    <a  href="<?php echo BASE_URL ?>almacen/producto/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
			    </div>
          <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Codigo</th>
                        <th>Cod-Alterno</th>
                        <th>Grupo</th>
                        <th>Sub-Grupo</th>
                        <th>Descripcion</th>
                        <th>Existencia</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['codigo'] ?></td>          
                            <td><?php echo $val['codigoAlterno'] ?></td>
                  
                            <td><?php echo $val['grupo'] ?></td>
                            <td><?php echo strtoupper($val['subGrupo']) ?></td>
                            <td><?php echo strtoupper($val['descripcion']) ?></td>
                            <td><?php echo $val['ExistenciaTotal'] ?></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>almacen/producto/editar/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>almacen/producto/eliminar/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para eliminar registro"> <i class="fa fa-trash"></i></button></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>almacen/producto/existencia/<?php echo $val['codigo'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para Ver Existencia por Depositos"><i class="fa-solid fa-boxes-packing"></i></i></button>
                            </td>
                            <td>
                                <button class="btn btn-default btn-sm imprimir" title="Presione aquí para imprimir Despacho" value="<?php echo $val['codigo'] ?>" data-toggle="modal" data-target="#modal-xl"> <i class="fa fa-print"></i></button>
                            </td>    
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                <p>
                        <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            
          </div>

        </div>
    </div>


    <div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-xl" bis_skin_checked="1">
            <div class="modal-content" bis_skin_checked="1">
                <div class="modal-header" bis_skin_checked="1">
                    
                    <div class="col-md-11">
                        <div class="row justify-content-start">
                            <div class="col-2">
                                <label>Fecha Inicio:</label>
                                <input type="date" name="inicio" id="inicio" class="form-control"  />
                            </div>
                            <div class="col-2">
                                <label>Fecha Final:</label>
                                <input type="date" name="final" id="final" class="form-control"  />
                            </div>
                            <div class="col-5">
                               <div class="form-group">
                                    <label>Almacen:</label>
                                    <select class="select2 select2-hidden-accessible" multiple="" data-placeholder="Select a State" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true" id="almacen">
                                        <?php foreach($this->almacenes as $almacen): ?>
                                            <option value="<?php echo $almacen['id'] ?>"><?php echo strtoupper($almacen['nombre']) ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                    
                                </div>
                            </div>
                            <div class="col-1 align-middle" style="margin-top:32px;">
                                <button type="button" class="btn btn-primary" id="generarNota" value="0">Recargar</button>
                             </div>
                           
                        </div>
                       
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" bis_skin_checked="1">
                    <div id="nota" ></div>
                </div>
                <div class="modal-footer justify-content-between" bis_skin_checked="1">
                
                    <button type="button" class="btn btn-primary" id="imprimir"><i class="fa fa-print"></i></button>
                </div>
            </div>

        </div>

    </div> 
        
</div>
