<?php //print_r($_layoutParams['argumentos']) ?>
<div class="row">
        <div class="col-lg-12 col-md-6">
        <div class="card card-default">
            <div class="card-header">
                <a href="<?php echo BASE_URL ?>configuracion/empresa/agregar" class=""> <button class=" btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
				<div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                      </button>
                    </div>
                  </div>
                </div>
			</div>        
          <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-light-blue disabled color-palette">
                        <th>Código</th>
                        <th>Creado</th>
                        <th>Nombre</th>
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>Correo Electronico</th>
                        
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr >
                            <td><?php echo $val['id'] ?></td>
                            <td><?php echo date('d-m-Y',strtotime($val['fecha_creacion'])) ?></td>
                            <td><?php echo $val['nombre_empresa'] ?></td>
                            <td><?php echo $val['direccion_empresa'] ?></td>
                            <td><?php echo $val['telefono_empresa'] ?></td>
                            <td><?php echo $val['correo_empresa'] ?></td>
                            
                            <td>
                                <?php if($val['estatus_empresa']==1): ?>
					            <a href="<?php echo BASE_URL ?>configuracion/empresa/editar/<?php echo $val['id'] ?>"><button class="editar btn btn-default" title="Presione aquí para EDITAR" value="" ><i  class="fa fa-pencil-square-o"></i></button></a>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_empresa']==1): ?>
					            <a href="<?php echo BASE_URL ?>configuracion/empresa/personal/<?php echo $val['id'] ?>"><button class="editar btn btn-default" title="Presione aquí para EDITAR" value="" ><i  class="fa fa-wrench"></i></button></a>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_empresa']==1): ?>
                                    <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>

</div>