<div class="row">
        <div class="col-md-3">

            <div class="card card-secondary card-outline"  bis_skin_checked="1">
              <div class="card-body box-profile" bis_skin_checked="1">
                <div class="text-center" bis_skin_checked="1">
                  <img class="profile-user-img img-fluid img-circle" src="<?php echo BASE_IMG ?>usuarioh.jpg" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center"><?php if(isset($this->usuario['alias_usuario'])) echo $this->usuario['alias_usuario']; ?></h3>

                <p class="text-muted text-center"><?php if(isset($this->usuario['nombre_role'])) echo $this->usuario['nombre_role']; ?></p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Fecha de Creacion</b> <a class="float-right"><?php echo (isset($this->usuario['fec_crea_usuario']))? date('d-m-Y',strtotime($this->usuario['fec_crea_usuario'])):"0000-00-00"  ?></a>
                  </li>
                  <li class="list-group-item">
                    <b>Condición Actual</b> <a class="float-right"><?php if(isset($this->usuario['condicion_usuario'])) echo $this->usuario['condicion_usuario']; ?></a>
                  </li>
                  <li class="list-group-item">
                    <b>Mensajes</b> <a class="float-right">13,287</a>
                  </li>
                </ul>

                <a href="#" data-toggle="modal" data-target="#modal-xl" class="btn btn-secondary btn-block"><b><i class="fa fa-light fa-key"></i> Cambiar Clave</b></a>

              </div>
              <!-- /.card-body -->
            </div>

            <div class="card card-secondary" bis_skin_checked="1">
              <div class="card-header" bis_skin_checked="1">
                <h3 class="card-title">Aprobaciones</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body" bis_skin_checked="1">
                <strong><i class="fas fa-book mr-1"></i> Education</strong>

                <p class="text-muted">
                  B.S. in Computer Science from the University of Tennessee at Knoxville
                </p>

                <hr>

                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                <p class="text-muted">Malibu, California</p>

                <hr>

                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>

                <p class="text-muted">
                  <span class="tag tag-danger">UI Design</span>
                  <span class="tag tag-success">Coding</span>
                  <span class="tag tag-info">Javascript</span>
                  <span class="tag tag-warning">PHP</span>
                  <span class="tag tag-primary">Node.js</span>
                </p>

                <hr>

                <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
              </div>
              <!-- /.card-body -->
            </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9" bis_skin_checked="1">
          
        </div>
        <!-- /.col -->
</div>
      
<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title">Cambiar Clave <span id="tecnico"></span></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div class="row">

                    <form name="form-clave" id="form-clave" method="post" action="<?php echo BASE_URL ?>seguridad/usuario/cambiarClave/">
                        <input name="guardar" id="guardar" type="hidden" value="1" />
                        <input name="usuario_id" id="usuario_id" type="hidden" value="<?php echo $this->usuario['id'] ?>" />
                        <div class="card-body" bis_skin_checked="1">
                            <div class="form-group row" bis_skin_checked="1">
                                <label  class="col-sm-3 col-form-label">Password</label>
                                <div class="col-sm-9" bis_skin_checked="1">
                                <input type="password" class="form-control" id="inputPassword1" name="inputPassword1" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group row" bis_skin_checked="1">
                                <label class="col-sm-3 col-form-label">Retype Password</label>
                                <div class="col-sm-9" bis_skin_checked="1">
                                <input type="password" class="form-control" id="inputPassword2" name="inputPassword2" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group row" bis_skin_checked="1">
                                <button class="btn btn-default" type="button" id="enviarClave" > Enviar</button>
                            </div>
                        </div>

                    </form>
                    
                </div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1"> 
                
            </div>
        </div>

    </div>

</div>


