<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">

            </div>
            <div class="card-body">
                <table class="table table-condensed">
                    <thead>
                        <tr class="bg-secondary color-palette" >
                            <th>Id</th>
                            <th>Fecha</th>
                            <th>Tecnico</th>
                            <th>Credito</th>
                            <th>Rubro</th>
                            <th>Productor</th>
                            <th>Finca</th>
                            <th>Etapa</th>
                            <th>Estado</th>
                            <th>Cant. Productos</th>
                            <th>Cant. Imagenes</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                            <?php if(isset($this->lista) && count($this->lista)) :?>
                            <?php $i = 1 ?>
                            <?php foreach ($this->lista as $val) :?>
                                
                            <tr data-toggle="collapse" data-widget="expandable-table" data-target="#demo<?php echo $i ?>" aria-expanded="false" class="accordion-toggle">

                                <td ><?php echo $val['id'] ?> <i class="expandable-table-caret fas fa-caret-right fa-fw"></i></td>
                                <td><?php echo $val['fecha'] ?></td>
                                <td><?php echo strtoupper($val['tecnico']) ?></td>
                                <td><?php echo $val['credito'] ?></td>
                                <td><?php echo $val['rubro'] ?></td>
                                <td><?php echo strtoupper($val['productor']) ?></td>
                                <td><?php echo strtoupper($val['finca']) ?></td>
                                <td><?php echo strtoupper($val['etapa']) ?></td>
                                <td><?php echo strtoupper($val['estado']) ?></td>
                                <td class="text-right"><?php echo number_format($val['cantidadProductos'],2,".",",") ?></td>
                                <td class="text-right"><?php echo $val['cantidadImagenes'] ?></td>
                                
                                    
                            </tr>   
                            <?php if(isset($val['detalles']) && count($val['detalles'])>0): ?>
                            <?php $det = $val['detalles'] ?>    
                            <tr>
                                <td colspan="13" class="hiddenRow">
                                    <div class="accordian-body collapse" id="demo<?php echo $i ?>"> 
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="bg-lightblue disabled color-palette">
                                                    <th>Productos</th>
                                                    <th>Fondos</th>
                                                    <th>Imagenes</th>
                                                    <th>Videos</th>		
                                                    <th>Comentarios</th>		
                                                </tr>
                                                
                                            </thead>
                                            <body>
                                                <tr>
                                                    <td><?php echo $det['productos'] ?></td>
                                                    <td><?php echo $det['fondos'].'$ / Motivo:'.$det['motivo'] ?></td>
                                                    <td><?php echo $det['imagenes'] ?></td>
                                                    <td><?php echo $det['videos'] ?></td>
                                                    <td><?php echo $det['comentarios'] ?></td>
                                                </tr>
                                            </body>
                                        </table>    	
                                    </div>
                                </td>
                            </tr>      
                            <?php endif; ?>
                            <?php $i = $i+1 ?>
                            <?php endforeach; ?>
                            <?php endif; ?>    
                            <tr> 
                        </td>
                        </tr>
                    </tbody>
                </table>
                
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
                
            </div>
                     
        </div>
                   
    </div>
        
</div>

<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title">Detalle de Visita <span id="tecnico"></span></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div class="row">
                    <div id="nota" >
                        <div class="slide" id="slide" style="width:700px;height:370px;border-radius:15px;margin: 10px 10px;padding: 10px 10px; ">
                            
                        </div>
                        <div id="map" style="height:350px;width:700px ;border-color: black 1px; border-radius:15px;margin: 10px 10px;padding: 10px 10px; ">

                        </div>        

                    </div>
                    <div class="col-md-4" bis_skin_checked="1">
                        <div class="card card-secondary" bis_skin_checked="1">
                           <div class="card-header" bis_skin_checked="1">
                                <h3 class="card-title"><i class="fa-solid fa-map-location-dot"></i>  <span id="finca"></span></h3>
                            </div>   
                        </div>
                        
                        <div class="card-body" bis_skin_checked="1">
                            <strong><i class="fas fa-map-marker-alt mr-1"></i> Locación</strong>
                            <p class="text-muted"><span id="locacion"></span></p>
                            <hr>
                            <strong><i class="fa-solid fa-hat-cowboy-side"></i> Propietario:</strong>
                            <p class="text-muted"><span id="productor"></span></p>
                            <hr>
                            <strong><i class="fa-solid fa-money-bill-trend-up"></i> Plan de Financiamiento:</strong>
                            <p class="text-muted"><span id="financiamiento"></span></p>
                            <hr>
                            <strong><i class="far fa-file-alt mr-1"></i> Notas:</strong >
                            <p class="text-muted"><span id="notas"></span></p>
                            <hr>
                            <strong><i class="fa-solid fa-dolly"></i> Productos:</strong >
                            <p class="text-muted"><span id="productos"></span></p>
                            <hr>
                            <strong><i class="fa-regular fa-comment-dots"></i> Comentarios:</strong >
                            <p class="text-muted"><span id="comentarios"></span></p>

                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1"> 
                
            </div>
        </div>

    </div>

</div>


<div class="modal fade" id="modal-lg" bis_skin_checked="1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-lg" bis_skin_checked="1">
          <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
              <h4 class="modal-title"><span id="titulo_video"></span></h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                  <div id="visor" style="width:700px;height:390px;border-radius:15px;margin: 10px 10px;padding: 10px 10px; " >

                  </div>              
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
             
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>

