<div class="row">
<div class="col-lg-12">
	<form name="form_deposito_editar" method="post" id="form_deposito_editar" action="<?php echo BASE_URL ?>almacen/deposito/editar/"  >
	<input name="guardar" id="guardar" type="hidden" value="2" />
	<input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))? $this->datos[0]['id']:''  ?>" />
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Editar Deposito</span>
		</div>
		<div class="card-body">
			<div class="row">
					<div class="form-group col-md-6">
						<label>*Nombre :</label>
						<input name="nombAlmacen"  maxlength="100" type="text" class="form-control " id="nombAlmacen"  value="<?php echo (!empty($this->datos[0]['nombre']))? $this->datos[0]['nombre']:''  ?>"   />  
					</div>
					<div class="form-group col-md-6">
						<label>*Direccion:</label>
						<input type="text"  maxlength="100" class="form-control "  name="direcAlmacen" id="direcAlmacen" value="<?php echo (!empty($this->datos[0]['direccion']))? $this->datos[0]['direccion']:''  ?>"  />
					</div>
                    <div class="form-group col-md-6">
						<label>*Descripcion:</label>
						<input type="text"  maxlength="100" class="form-control "  name="descAlmacen" id="descAlmacen" value="<?php echo (!empty($this->datos[0]['descripcion']))? $this->datos[0]['descripcion']:''  ?>"   />
					</div>
                    <div class="form-group col-md-6">
						<label>*Proveedor:</label>
						<select class="form-control select2" style="width: 100%;" name="provAlmacen" id="provAlmacen" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->proveedor) && count($this->proveedor)): ?>
                            <?php foreach ($this->proveedor as $val): ?>
                            <?php if($val['id'] == $this->datos[0]['proveedor']): ?>
                                <option value="<?php echo $val['id']  ?>" selected><?php echo strtoupper($val['razonSocial'])  ?></option>
                            <?php else: ?>
                                <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['razonSocial'])  ?></option>
                            <?php endif; ?>    
                            <?php endforeach; ?>
                            <?php endif; ?>

                        </select>
					</div>
			</div>
            </br>
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true">Contacto Almacen</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false">Otra Informacion</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue contactos para el Almacen</span></div>
                                <div class="card-body">
                                <div class="row">
                                        <div class="form-group col-md-4">
                                            <label>*Telefono Oficina:</label>
                                            <input name="tlf_alm_ofi"  maxlength="100" type="text" class="form-control form-control-sm" id="tlf_alm_ofi" value="<?php echo (!empty($this->datos[0]['mediosContacto_Telefonos_Oficina']))? $this->datos[0]['mediosContacto_Telefonos_Oficina']:''  ?>"  />  
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Telefono Encargado:</label>
                                            <input name="tlf_alm_enc"  maxlength="100" type="text" class="form-control form-control-sm" id="tlf_alm_enc" value="<?php echo (!empty($this->datos[0]['mediosContacto_Telefonos_Encargado']))? $this->datos[0]['mediosContacto_Telefonos_Encargado']:''  ?>" />  
                                        </div>
                            
                                        <div class="form-group col-md-4">
                                            <label>*Whatsapp</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="tlf_wsp" id="tlf_wsp" placeholder="" value="<?php echo (!empty($this->datos[0]['mediosContacto_Whatsapp']))? $this->datos[0]['mediosContacto_Whatsapp']:''  ?>" />
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>*Correo Oficina</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_ofi" id="correo_ofi" placeholder="Ej.: micorreo@hotmail.com" value="<?php echo (!empty($this->datos[0]['mediosContacto_Correos_Oficina']))? $this->datos[0]['mediosContacto_Correos_Oficina']:''  ?>" />
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>*Correo Encargado</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_enc" id="correo_enc" placeholder="Ej.: micorreo@hotmail.com"  value="<?php echo (!empty($this->datos[0]['mediosContacto_Correos_Encargado']))? $this->datos[0]['mediosContacto_Correos_Encargado']:''  ?>" />
                                        </div>
                                                                                   
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title"></span></div>
                                <div class="card-body">
                                    
                                    <div class="row">
                                        <div class="form-group col-md-12">
                                            <label>*Comentarios</label>
                                            <textarea class="form-control" id="observacion" name="observacion" rows="3" ><?php echo (!empty($this->datos[0]['comentarios']))? $this->datos[0]['comentarios']:''  ?></textarea>
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                        
                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>almacen/deposito/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
