<div class="row">
    <div class="col-12">
        <form name="form_almacen_eliminar" method="post" id="form_almacen_eliminar" action="<?php echo BASE_URL ?>almacen/deposito/eliminar/">
        <input name="eliminar" id="eliminar" type="hidden" value="1" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))? $this->datos[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Eliminacion de Almacen</h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta se guro de eliminar el registro de Almacen:</h3>
                        

                        <dl class="row">
                            <dt class="col-sm-4">Nombre Almacen :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['nombre']))?$this->datos[0]['nombre']:"" ?></dd>
                            <dt class="col-sm-4">Descripcion :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['descripcion']))?$this->datos[0]['descripcion']:"" ?></dd>
                            <dt class="col-sm-4">Direccion  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['direccion']))?$this->datos[0]['direccion']:"" ?></dd>
                            <dt class="col-sm-4">Telefono  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['mediosContacto_Telefonos_Oficina']))?$this->datos[0]['mediosContacto_Telefonos_Oficina']:"" ?></dd>
                            <dt class="col-sm-4">Correo :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['mediosContacto_Correos_Oficina']))?$this->datos[0]['mediosContacto_Correos_Oficina']:"" ?></dd>
                            
                        </dl>
                        

                </div>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>almacen/deposito/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
