<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="card card-default">   
            <div class="card-header">
                <a  href="<?php echo BASE_URL ?>almacen/deposito/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
            </div>  
            <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                    <tr class="bg-secondary color-palette">
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Ubicación</th>
                        <th>Teléfonos</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id'] ?></td>
                            <td><?php echo ucwords($val['nombre']) ?></td>
                            <td><?php echo ucwords($val['direccion']) ?></td>
                            <td><?php echo $val['mediosContacto_Telefonos_Oficina'] .' - '.$val['mediosContacto_Telefonos_Encargado']  ?></td>
                            <td><a href="<?php echo BASE_URL ?>almacen/deposito/editar/<?php echo $val['id'] ?>" >
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id'] ?>" ><i  class="fa fa-pencil-square-o"></i></a></button>
                            </td>
                            <td><a href="<?php echo BASE_URL ?>almacen/deposito/eliminar/<?php echo $val['id'] ?>" >
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id'] ?>" ><i  class="fa fa-trash-o"></i></a></button>
                            </td>
                            <td><a href="<?php echo BASE_URL ?>almacen/deposito/productosDepositos/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default" title="Presione aquí para ver Productos en Deposito "><i class="fa fa-inbox"></i></button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                
            
          </div>

        </div>
    </div>
        
</div>
