<div class="col-lg-12">
    <form name="form_recurso_editar" id="form_recurso_editar" method="post" autocomplete="off" action="">    
<div class="panel panel-default">
    <div class="panel-heading">Información del Recurso</div>
    <div class="panel-body">
        <input name="guardar" id="guardar" type="hidden" value="2" /> 
        <input name="id" id="id" type="hidden" value="<?php echo $this->recurso['id_recurso'] ?>" /> 
          <div class="form-group ">
            <div class="form-inline">
              <label class="control-label">*Nombre:</label>
              <input name="nombre" type="text" maxlength="60" value="<?php if(isset($this->recurso['nombre_recurso'])) echo $this->recurso['nombre_recurso'] ?>" class="form-control alfa_desc"  id="nombre" placeholder="Ingrese nombre del recurso" required />
             </div>
          </div>
            <hr>
          <div class="form-group col-xs-6">
            <label>*Descripción:</label>
            <input name="descripcion" maxlength="100" value="<?php if(isset($this->recurso['descripcion_recurso'])) echo $this->recurso['descripcion_recurso'] ?>" required type="text" class="form-control alfa_desc" id="descripcion" placeholder="Ingrese descripción del recurso" >            
          </div>
          <div class="form-group col-xs-6">
            <label>*Url:</label>
            <input name="url" type="text" maxlength="100" value="<?php if(isset($this->recurso['url_recurso'])) echo $this->recurso['url_recurso'] ?>" class="form-control" id="url" placeholder="Ingrese dirección url del recurso" required >  
          </div>
          <div class="form-group col-xs-6">
            <label>*Icono:</label>
            <input type="text" class="form-control" maxlength="60" value="<?php if(isset($this->recurso['icon_recurso'])) echo $this->recurso['icon_recurso'] ?>" name="icono" id="icono" placeholder="Ingrese icono del recurso" required  />
          </div>
          <div class="form-group col-xs-6">
            <label>*Posición:</label>
            <input type="text" class="form-control num" maxlength="2" value="<?php if(isset($this->recurso['posicion_recurso'])) echo $this->recurso['posicion_recurso'] ?>" name="posicion" id="posicion" placeholder="Ingrese la posición" required  />
          </div>
          <div class="form-group col-xs-4">
            <label>*Módulo:</label>
            <select name="modulo" id="modulo" class="form-control" required >
                <option value="0" >-Seleccione-</option>
                <?php if(isset($this->modulos) && count($this->modulos)): ?>
                      <?php foreach ($this->modulos as $val): ?>

                          
                        <?php if($val['id_modulo']== $this->recurso['modulo_id']): ?>
                        <option value="<?php echo $val['id_modulo']  ?>" selected><?php echo $val['nombre_modulo'] ?></option>
                        <?php else: ?>
                        <option value="<?php echo $val['id_modulo']  ?>" ><?php echo $val['nombre_modulo'] ?></option>
                        <?php endif; ?>  
                          
                          
                          
                          
                          
                      <?php endforeach; ?>
                <?php endif; ?>
            </select>
          </div>
    </div>
  </div>        
        <br/>
        <button type="button" name="agregar" id="agregar" title="Presione aquí para Guardar el registro" class="btn btn-primary" ><i class="fa fa-floppy-o"></i>Guardar</button>
        <a href="<?php echo BASE_URL ?>configuracion/recurso/index">
        <button type="button" title="Presione aquí para SALIR Y CANCELAR el registro" class="btn btn-danger"><i class="fa fa-undo"></i>Cancelar</button>
        </a>
          <br/>
          <br/>
        </form> 
</div>