<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
            <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="<?php echo BASE_URL ?>desarrollo/recurso/agregar/"> <button  title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>                        
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" name="busqueda" class="form-control" placeholder="Filtrar nombre de Recurso">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
            </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Módulo</th>
                        <th>Url</th>
                        <th>Posición</th>
                        <th>Icono</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo ucwords($val['nombre_recurso']) ?></td>
                            <td><?php echo ucfirst($val['descripcion_recurso']) ?></td>
                            <td><?php echo ucwords($val['modulos']) ?></td>
                            <td><?php echo $val['url_recurso'] ?></td>
                            <td><?php echo $val['posicion_recurso'] ?></td>
                            <td><?php echo $val['icon_recurso'] ?></td>
                            <td>
                                <?php if($val['estatus_recurso']==1): ?>
                                <a href="<?php echo BASE_URL ?>configuracion/recurso/editar/<?php echo $val['id_recurso'] ?>" >
                                <button class="editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_recurso'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                 <?php if($val['estatus_recurso']==1): ?>
                                     <button class="eliminar" value="<?php echo $val['id_recurso'] ?>" title="Presione aquí para ELIMINAR"><i class="fa fa-trash-o"></i></button>
                                 <?php endif; ?>
                             </td>
                            <td>
                                 <?php if($val['estatus_recurso']==9): ?>
                                     <button class="restaurar" value="<?php echo $val['id_recurso'] ?>" title="Presione aquí para RESTAURAR"><i class="fa fa-recycle"></i></button>
                                 <?php endif; ?>
                             </td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>