<div class="row">
    <div class="col-lg-8 col-md-6">
        <div class="card card-default">                        
            <div class="card-header">
                <a class=""> <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>                  
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="busqueda" maxlength="60" class="form-control alfa_desc" placeholder="Filtrar nombre">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>

                        </div>
                    </div>        
                </div>
            </div>    

            <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr class="bg-secondary color-palette" >
                                <th>Código</th>
                                <th>Descripción</th>
                                <th width="30"></th>
                                <th width="30"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1; ?>    
                            <?php if(isset($this->lista) && count($this->lista)) :?>
                                <?php foreach ($this->lista as $val) :?>
                                <tr>
                                    <td><?php echo $val['id'] ?></td>
                                    <td><?php echo ucwords($val['pregunta']) ?></td>
                                    <td>
                                        <?php if($val['estatus_pregunta']==1): ?>
                                        <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                        <?php endif; ?>
                                    </td>    
                                    <td>
                                        <?php if($val['estatus_pregunta']==1): ?>
                                        <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id'] ?>"><i class="fa fa-trash-o"></i></button>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <?php $i++; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>    
                            </tbody>
                        </table>
                        <hr>
                        <p>
                            <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                        </p>
                    </div>
                
            </div>
        </div>    
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card card-default">
            <div class="card-header">Gestión de Permisos</div>
            <div class="card-body">
            <form name="form_pregunta" id="form_pregunta" method="post" autocomplete="off" action="<?php echo BASE_URL ?>seguridad/pregunta/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>Descripción:</label>
                      <input name="descripcion" disabled="disabled" maxlength="150" type="text" class="form-control alfa_desc" id="descripcion" placeholder="Ingrese descripción de la pregunta" required>
                    </div>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                  </form>    
            </div>
        </div>
    </div>    
</div>
