<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
            <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn">
                        <a  href="<?php echo BASE_URL ?>desarrollo/modulo/agregar/"> <button class="btn btn-default"><i  class="fa fa-plus"></i></button> </a>
                    </div>
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" name="busqueda" class="form-control" placeholder="Filtrar descripción">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr class="bg-light-blue">
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Url</th>
                        <th>Icono</th>
                        <th>Posición</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><a href="<?php echo BASE_URL ?>desarrollo/modulo/archivoModulo/<?php echo $val['id_modulo'] ?>"><?php echo ucwords($val['nombre_modulo']) ?></a></td>
                            <td><?php echo ucwords($val['descripcion_modulo']) ?></td>
                            <td><?php echo $val['url_modulo'] ?></td>
                            <td><?php echo $val['icon_modulo'] ?></td>
                            <td><?php echo $val['posicion_modulo'] ?></td>
                            <td>
                                <?php if($val['estatus_modulo']==1): ?>
                                <a href="<?php echo BASE_URL ?>desarrollo/modulo/editar/<?php echo $val['id_modulo'] ?>" >
                                <button class="buscar btn btn-default editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_modulo'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>                             
                                <?php endif; ?>
                            </td>
                            <td>
                                 <?php if($val['estatus_modulo']==1): ?>
                                <button class="buscar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_modulo'] ?>" ><i class="fa fa-trash-o"></i></button>
                                 <?php endif; ?>
                             </td>
                            <td>
                                <?php if($val['estatus_modulo']==9): ?>
                                <button class="buscar btn btn-default restaurar" title="Presione aquí para RESTAURAR" value="<?php echo $val['id_modulo'] ?>" ><i class="fa fa-recycle"></i></button>
                                <?php endif; ?>
                             </td>                             
                             <td><a href="<?php echo BASE_URL ?>desarrollo/modulo/recurso/<?php echo $val['id_modulo'] ?>" >
                                <button title="Presione aquí para ver los recursos  del modulo " class="buscar btn btn-default"><i class="fa fa-code-fork"></i></button></td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>