<div class="row-fluid">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
            <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="<?php echo BASE_URL ?>desarrollo/modulo/agregar/"> <button  title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                    </div>
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" name="busqueda" class="form-control" placeholder="Filtrar descripción">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
				<ul><li>Raiz</li>	
				<?php if(count($this->lista)): ?>
					<?php foreach($this->lista as $val ): ?>
						<?php if($val['tipo']=='arc'): ?>
							<ul>
								<li><?php echo $val['nombre'] ?></li>
							</ul>
						<?php else: ?>
							<li><?php echo $val['nombre'] ?></li>
						<?php endif ?> 	
					<?php endforeach; ?> 
				<?php endif; ?>
				<ul>
            </div>
          </div>

        </div>
    </div>
        
</div>