<div class="row">
<div class="col-lg-12">
	<form name="form_recepcion_agregar" method="post" id="form_recepcion_agregar" action="<?php echo BASE_URL ?>creditos/liquidacion/agregar/"  >
	
    <input name="guardar" id="guardar" type="hidden" value="1" />
    <input name="totalLiquidar"  type="hidden" id="totalLiquidar" value="0,0"  />
    <input name="totalCosecha" type="hidden" id="totalCosecha"  value="0,0" />
    <input name="montoFinanciado"  type="hidden" id="montoFinanciado" value="0,0" />
    <input name="tasaInteres"  type="hidden" id="tasaInteres" value="0,0" />
    <input name="montoInteres"  type="hidden" id="montoInteres" value="0,0" />
    <input name="boletas"  type="hidden" id="boletas" value="" />
    <input name="documentos"  type="hidden" id="documentos" value="" />

	<div class="card card-secondary card-outline">
		
		<div class="card-body">
			<div class="row">
                <div class="col-lg-6">    
                    <div class="card  card-outline" >
                        <div class="card-body">
                            <div class="row">
								<div class="form-group col-md-6"> 
                                    <label>*Productor:</label>
                                    <select name="productor" id="productor" class="form-control select2">
                                        <option value="-">-Seleccione-</option>
                                        <?php if(count($this->productor)): ?>
                                            <?php foreach($this->productor as $pro): ?>
                                                <option value="<?php echo $pro['idFiscal'] ?>"><?php echo strtoupper($pro['razonSocial']) ?></option>
                                            <?php endforeach;?>
                                        <?php endif; ?>	
                                    </select>   
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <label>*Crédito:</label>
                                    <select class="form-control" name="credito" id="credito">
                                        <option value="0">-Seleccione-</option>        
                                        

                                    </select>

                                </div> 
                                <div class="form-group col-md-4">
									<label>*Prog. Financiamiento:</label>
                                    <input name="prgFinanciamiento" type="text" class="form-control" id="prgFinanciamiento" readonly/> 
								</div>
                                <div class="form-group col-md-5">
									<label>*Finca:</label>
                                    <input name="finca" type="text" class="form-control" id="finca" readonly/> 
								</div>
                                <div class="form-group col-md-3">
									<label>*Fecha:</label>
                                    <input name="fechaLiquidacion" type="date" class="form-control" id="fechaLiquidacion" /> 
								</div>

                            </div>    
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">    
                    <div class="card  card-outline" >
                       
                        <div class="card-body">
                            <div class="row">
           
                                <div class="form-group col-md-4">
									<label>*Ha Aprobadas:</label>
                                    <input name="haAprobadas"  maxlength="10" type="text" class="form-control text-right" id="haAprobadas" readonly/> 
								</div>                                
                                <div class="form-group col-md-4">
									<label>*Ha Cosechadas :</label>
										<input name="haCosechadas"  maxlength="30" type="text" class="form-control text-right" id="haCosechadas" readonly/>  
								</div>
                                <div class="form-group col-md-4">
                                    <label>*Precio X Kg:</label>
                                    <input name="precioLiquidacion"  maxlength="10" type="text" class="form-control text-right" id="precioLiquidacion" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Kg.Cosechados:</label>
                                    <input name="kgCosechados"  maxlength="10" type="text" class="form-control text-right" id="kgCosechados" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Kg. a Descontar :</label>
                                    <input name="kgDescuento"  maxlength="10" type="text" class="form-control text-right" id="kgDescuento" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Kg. a Liquidar :</label>
                                    <input name="kgLiquidar"  maxlength="10" type="text" class="form-control text-right" id="kgLiquidar" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Monto Cosecha :</label>
                                    <input name="monto"  maxlength="10" type="text" class="form-control text-right" id="monto" readonly/> 
                                </div>             

                            </div>
                        </div>
                    </div>
                </div>
            </div>         

		
                <div class="row">                        
                    <div class="col-md-9 mt-1">

                        <div class="card card-primary card-outline card-outline-tabs">
                            <div class="card-header p-0 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                                    <li class="nav-item">
                                    <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true"><i class="fa fa-map-o"></i>  Documentos </a>
                                    </li>
                                    <li class="nav-item">
                                    <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false"><i class="fa  fa-book"></i> Cálculo de Intereses </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-info" role="tab" aria-controls="custom-tabs-four-info" aria-selected="false"><i class="fa  fa-book"></i> Cosecha </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-four-resumen-tab" data-toggle="pill" href="#custom-tabs-four-resumen" role="tab" aria-controls="custom-tabs-four-resumen" aria-selected="false"><i class="fa  fa-book"></i> Resumen </a>
                                    </li>
                                    
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content" id="custom-tabs-four-tabContent">
                                    <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                                        <div class="card ">
                                            <div class="card-header">
                                                Seleccione los documentos para realizar el cálculo de intereses       
                                            </div>
                                            <div class="card-body ">
                                                <div id="tabla-documentos">
                                                
                                                </div>
                                            </div>
                                            <div class="card-footer">
                                                <button type="button" class="btn btn-default" id="calcInteres"  >Cálcular Intereses</button>       
                                            </div>
                                        </div>              
                                    </div>
                                    <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                                        <div class="card ">
                                            <div class="card-header">        
                                            </div>
                                            <div class="card-body">
                                                <div id="tabla-interes">
                                                
                                                </div>
                                            </div>
                                        </div>              
                                    </div>
                                    <div class="tab-pane fade " id="custom-tabs-four-info" role="tabpanel" aria-labelledby="custom-tabs-four-contact-info-tab">
                                        <div class="card ">
                                            <div class="card-header">        
                                            </div>
                                            <div class="card-body">
                                                <div id="tabla-cosecha">

                                                </div>
                                                
                                            </div>
                                        </div>              
                                    </div>
                                    <div class="tab-pane fade " id="custom-tabs-four-resumen" role="tabpanel" aria-labelledby="custom-tabs-four-resumen-tab">
                                        <div class="card ">
                                            <div class="card-header">        
                                            </div>
                                            <div class="card-body ">
                                                <div id="tabla-resumen">
                                                
                                                </div>
                                            </div>
                                        </div>              
                                    </div>

                                </div>
                            </div>                        
                        </div>                            
    
                    </div>
                    <div class="col-md-3">
                        <div class="card "> 
                            <div class="form-group col-md-12">
                                <label>*Comentarios :</label>
                                <textarea name="comentario" type="text" class="form-control" id="comentario" rows="5" ></textarea>  
                            </div>

                        </div>
                    </div>
                        
                </div>	


		    
         
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar" disabled ><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>creditos/liquidacion/index/"><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
  
  </form>		  
</div>
</div>

</div>