<div class="row">
    <div class="col-12">
        <form name="form_despacho_eliminar" method="post" id="form_despacho_eliminar" action="<?php echo BASE_URL ?>creditos/liquidacion/anular/">
        <input name="anular" id="anular" type="hidden" value="3" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))? $this->datos[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Anulación de Liquidacion de Credito</h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta seguro de ! Anular ! el registro de Liquidacion de Credito:</h3>
                        

                        <dl class="row">
                            <dt class="col-sm-4">Correlativo  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['correlativo']))?$this->datos[0]['correlativo']:"" ?></dd>
                            <dt class="col-sm-4">Fecha  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['fecha']))?$this->datos[0]['fecha']:"" ?></dd>
                            <dt class="col-sm-4">Productor :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['RazonSocial']))?$this->datos[0]['RazonSocial']:"" ?></dd>
                            <dt class="col-sm-4">Concepto :</dt>
                            <dd class="col-sm-8">Credito #<?php echo $this->datos[0]['idCredito'] ?> | <?php echo  (isset($this->datos[0]['ProgFinanc']))?$this->datos[0]['ProgFinanc'].' | Finca:'.$this->datos[0]['fincas_nombre']:"" ?></dd>
                            <dt class="col-sm-4">Monto Financiado :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['montoFinanciado']))?$this->datos[0]['montoFinanciado']:"" ?></dd>
                                   
                        </dl>
                        

                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>*Fecha de Anulación:</label>
                        <input type="date" class="form-control"  name="fechaAnulacion" id="fechaAnulacion"   />
                    </div>
                    <div class="form-group col-md-6">
                        <label>*Comentario:</label>
                        <input type="text" class="form-control"  name="comentario" id="comentario"   />
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>creditos/liquidacion/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
