<div class="row">
<div class="col-lg-12">
<div class="col-12">
<?php if(strtoupper($this->datos[0]['estado'])=='ANULADO'): ?>
    <div class="ribbon-wrapper ribbon-xl" bis_skin_checked="1">
        <div class="ribbon bg-danger text-xl" bis_skin_checked="1"> ANULADO</div>
    </div>
<?php else: ?>
    <?php if($this->datos[0]['saldoFinal']>0): ?>
        <div class="ribbon-wrapper ribbon-xl" bis_skin_checked="1">
            <div class="ribbon bg-warning text-xl" bis_skin_checked="1"> LIQUIDADO</div>
        </div>
    <?php else: ?>
        <div class="ribbon-wrapper ribbon-xl" bis_skin_checked="1">
            <div class="ribbon bg-success text-xl" bis_skin_checked="1"> LIQUIDADO</div>
        </div>
    <?php endif ?>    
<?php endif ?>  
</div>   
	<form name="form_recepcion_agregar" method="post" id="form_recepcion_agregar" action="<?php echo BASE_URL ?>creditos/liquidacion/agregar/"  >
	
    <input name="guardar" id="guardar" type="hidden" value="1" />
    <input name="totalLiquidar"  type="hidden" id="totalLiquidar" value="0,0"  />
    <input name="totalCosecha" type="hidden" id="totalCosecha"  value="0,0" />
    <input name="montoFinanciado"  type="hidden" id="montoFinanciado" value="0,0" />
    <input name="tasaInteres"  type="hidden" id="tasaInteres" value="0,0" />
    <input name="montoInteres"  type="hidden" id="montoInteres" value="0,0" />
    <input name="boletas"  type="hidden" id="boletas" value="" />
    <input name="documentos"  type="hidden" id="documentos" value="" />

	<div class="card card-secondary card-outline">
		
		<div class="card-body">
			<div class="row">
                <div class="col-lg-6">    
                    <div class="card  card-outline" >
                        <div class="card-body">
                            <div class="row">
								<div class="form-group col-md-6"> 
                                    <label>*Productor:</label>
                                    <select name="productor" id="productor" class="form-control select2" disabled>
                                        <option value="-">-Seleccione-</option>
                                        <?php if(count($this->productor)): ?>
                                            <?php foreach($this->productor as $pro): ?>
                                                <?php if($this->datos[0]['idFiscalProductor'] == $pro['idFiscal']) :?>
                                                    <option value="<?php echo $pro['idFiscal'] ?>" selected><?php echo strtoupper($pro['razonSocial']) ?></option>
                                                <?php else: ?>    
                                                    <option value="<?php echo $pro['idFiscal'] ?>"><?php echo strtoupper($pro['razonSocial']) ?></option>
                                                <?php endif ?>    
                                            <?php endforeach;?>
                                        <?php endif; ?>	
                                    </select>   
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <label>*Credito:</label>
                                    <input name="credito" type="text" class="form-control" id="credito" value="<?php echo(!empty($this->credito[0]['ProgFinanc']))?$this->credito[0]['ProgFinanc'].'| Finca:'.$this->credito[0]['fincas_nombre']:"" ?>" readonly/> 

                                </div> 
                                <div class="form-group col-md-4">
									<label>*Prog. Financiamiento:</label>
                                    <input name="prgFinanciamiento" type="text" class="form-control" id="prgFinanciamiento" value="<?php echo(!empty($this->datos[0]['ProgFinanc']))?$this->datos[0]['ProgFinanc']:"" ?>" readonly/> 
								</div>
                                <div class="form-group col-md-5">
									<label>*Finca:</label>
                                    <input name="finca" type="text" class="form-control" id="finca" value="<?php echo(!empty($this->datos[0]['fincas_nombre']))?$this->datos[0]['fincas_nombre']:"" ?>" readonly/> 
								</div>
                                <div class="form-group col-md-3">
									<label>*Fecha:</label>
                                    <input name="fechaLiquidacion" type="date" class="form-control" id="fechaLiquidacion" value="<?php echo(!empty($this->datos[0]['fecha']))?$this->datos[0]['fecha']:"" ?>" readonly /> 
								</div>

                            </div>    
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">    
                    <div class="card  card-outline" >
                       
                        <div class="card-body">
                            <div class="row">
           
                                <div class="form-group col-md-4">
									<label>*Ha Aprobadas:</label>
                                    <input name="haAprobadas"  maxlength="10" type="text" class="form-control text-right" id="haAprobadas" value="<?php echo(!empty($this->datos[0]['hasAprobadas']))?$this->datos[0]['hasAprobadas']:"" ?>" readonly/> 
								</div>                                
                                <div class="form-group col-md-4">
									<label>*Ha Cosechadas :</label>
										<input name="haCosechadas"  maxlength="30" type="text" class="form-control text-right" id="haCosechadas" value="<?php echo(!empty($this->datos[0]['hasEfectivas']))?$this->datos[0]['hasEfectivas']:"" ?>" readonly/>  
								</div>
                                <div class="form-group col-md-4">
                                    <label>*Precio X Kg:</label>
                                    <input name="precioLiquidacion"  maxlength="10" type="text" class="form-control text-right" id="precioLiquidacion" value="<?php echo(!empty($this->datos[0]['precioKg']))?$this->datos[0]['precioKg']:"" ?>" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Kg.Cosechados:</label>
                                    <input name="kgCosechados"  maxlength="10" type="text" class="form-control text-right" id="kgCosechados" value="<?php echo(!empty($this->datos[0]['kgCosecha']))?$this->datos[0]['kgCosecha']:"" ?>" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Monto Cosecha :</label>
                                    <input name="monto"  maxlength="10" type="text" class="form-control text-right" id="monto" value="<?php echo(!empty($this->datos[0]['montoCosecha']))?$this->datos[0]['montoCosecha']:"" ?>" readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Monto Financiado  :</label>
                                    <input name="montoFinanciado"  maxlength="10" type="text" class="form-control text-right" id="montoFinanciado" value="<?php echo(!empty($this->datos[0]['montoFinanciado']))?$this->datos[0]['montoFinanciado']:"" ?>"readonly/> 
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Intereses :</label>
                                    <input name="montoIntereses"  maxlength="10" type="text" class="form-control text-right" id="montoInereses" value="<?php echo(!empty($this->datos[0]['intereses']))?$this->datos[0]['intereses']:"" ?>" readonly/> 
                                </div>
                                             

                            </div>
                        </div>
                    </div>
                </div>
            </div>         

		
                <div class="row">                        
                    <div class="col-md-9 mt-1">

                        <div class="card card-primary card-outline card-outline-tabs">
                            <div class="card-header p-0 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                                    
                                    <li class="nav-item ">
                                    <a class="nav-link active" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false"><i class="fa  fa-book"></i> Calculo de Intereses </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-info" role="tab" aria-controls="custom-tabs-four-info" aria-selected="false"><i class="fa  fa-book"></i> Cosecha </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-four-resumen-tab" data-toggle="pill" href="#custom-tabs-four-resumen" role="tab" aria-controls="custom-tabs-four-resumen" aria-selected="false"><i class="fa  fa-book"></i> Resumen </a>
                                    </li>
                                    
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content" id="custom-tabs-four-tabContent">
                                    
                                    <div class="tab-pane fade show active " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                                        <div class="card ">
                                            <div class="card-header">        
                                            </div>
                                            <div class="card-body">
                                                <div id="tabla-interes">
                                                    <?php echo (!empty($this->datos[0]['htmlCalInt']))?$this->datos[0]['htmlCalInt']:"" ?>
                                                </div>
                                            </div>
                                        </div>              
                                    </div>
                                    <div class="tab-pane fade " id="custom-tabs-four-info" role="tabpanel" aria-labelledby="custom-tabs-four-contact-info-tab">
                                        <div class="card ">
                                            <div class="card-header">        
                                            </div>
                                            <div class="card-body">
                                                <div id="tabla-cosecha">
                                                    <?php echo (!empty($this->datos[0]['htmlRecCose']))?$this->datos[0]['htmlRecCose']:"" ?>
                                                </div>
                                                
                                            </div>
                                        </div>              
                                    </div>
                                    <div class="tab-pane fade " id="custom-tabs-four-resumen" role="tabpanel" aria-labelledby="custom-tabs-four-resumen-tab">
                                        <div class="card ">
                                            <div class="card-header">        
                                            </div>
                                            <div class="card-body ">
                                                <div id="tabla-resumen">
                                                <?php echo (!empty($this->datos[0]['htmlResumenLiq']))?$this->datos[0]['htmlResumenLiq']:"" ?>
                                                </div>
                                            </div>
                                        </div>              
                                    </div>

                                </div>
                            </div>                        
                        </div>                            
    
                    </div>
                    <div class="col-md-3">
                        <div class="card "> 
                            <div class="form-group col-md-12">
                                <label>*Comentarios :</label>
                                <textarea name="comentario" type="text" class="form-control" id="comentario" rows="5" ><?php echo (!empty($this->datos[0]['comentario']))?$this->datos[0]['comentario']:"" ?></textarea>  
                            </div>

                        </div>
                    </div>
                        
                </div>	


		    
         
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar" disabled ><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>creditos/liquidacion/index/"><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
  
  </form>		  
</div>
</div>

</div>