<div class="row">
    <div class="col-12">
        <div class="card">
			
			    <div class="card-header">
				    <a  href="<?php echo BASE_URL ?>creditos/liquidacion/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
			    </div>
 
          <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Fecha</th>
                        <th>Id Fiscal</th>
                        <th>Productor</th>
                        <th>Programa de Financiamiento</th>
                        <th>Ha. Efectivas </th>
                        <th>Kg Producidos</th>
                        <th>Monto a Liquidar</th>
                        <th>Monto Pagado</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo date('d-m-Y',strtotime($val['fecha'])) ?></td>
                            <td><?php echo $val['idFiscalProductor'] ?></td>
                            
                            <td><?php echo strtoupper(utf8_encode($val['RazonSocial'])) ?></td>
                  
                            <td><?php echo strtoupper($val['ProgFinanc']) ?></td>
                            <td><?php echo number_format($val['hasEfectivas'],2,".",",") ?></td>
                            <td><?php echo number_format($val['kgCosecha'],2,".",",") ?></td>
                            <td>
                                <?php echo number_format(abs($val['saldoFinal']),2,".",",") ?>
                            </td>
                            <td><?php echo strtoupper($val['totalPagado']) ?></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>creditos/liquidacion/editar/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button>
                            </td>
                            <td>
                                <?php if($val['estado']=='ANULADO'): ?>
                                    <button class="btn btn-default btn-sm" title="Registro ya esta Anulado" type="button" disabled> <i class="fa fa-trash"></i></button></td>
                                <?php else: ?>
                                    <a href="<?php echo BASE_URL ?>creditos/liquidacion/anular/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-sm btn-danger" title="Presione aquí para eliminar registro"> <i class="fa fa-trash"></i></button></td></a>
                                <?php endif; ?>
                            </td>    
                            <td>
                                <?php if($val['estado']!='PAGADO' && $val['estado']!='ANULADO'): ?>
                                    <a href="<?php echo BASE_URL ?>creditos/liquidacion/pagar/<?php echo $val['id'] ?>" >
                                        <button class="btn btn-info  btn-sm imprimir" title="Presione aquí para pagar Liquidacion" value="<?php echo $val['id'] ?>" ><i class="fa-solid fa-credit-card"></i></button></a>
                                <?php else: ?>
                                    <?php if($val['estado']=='ANULADO'): ?>
                                            <button class="btn btn-info " title="Presione aquí para pagar Liquidacion" disabled ><i class="fa-solid fa-credit-card"></i></button>
                                        <?php else: ?>    
                                            <button class="btn btn-default  btn-sm imprimir" title="Presione para imprimir recibo de pago" value="<?php echo $val['id'] ?>" data-toggle="modal" data-target="#modal-xl"  ><i class="fa-solid fa-print"></i></button>
                                    <?php endif; ?>    
                                <?php endif; ?>     
                            </td>        
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                <p>
                        <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            
          </div>

        </div>
    </div>
        
</div>
<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div id="nota" ></div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
               
                <button type="button" class="btn btn-primary" id="imprimir"><i class="fa fa-print"></i></button>
            </div>
        </div>

    </div>

</div>