<div class="row">
  <div class="col-12">
    <form name="form-liquidar-pagar" id="form-liquidar-pagar" method="post" action="<?php echo BASE_URL ?>/creditos/liquidacion/pagar">
    <input name="guardar" id="guardar" type="hidden" value="1"  />
    <input name="idLiquidacion" id="idLiquidacion" type="hidden" value="<?php echo $this->datos[0]['id'] ?>"  />
    <input name="idCredito" id="idCredito" type="hidden" value="<?php echo $this->datos[0]['idCredito'] ?>"  />    
    <!-- Main content -->
    <div class="invoice p-3 mb-3">
              <!-- title row -->
              <div class="row">
                <div class="col-12">
                  
                </div>
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  
                  <address>
                    <strong><?php echo $this->configEmp['razon social'] ?></strong><br>
                    <small><?php echo $this->configEmp['IdFiscal'] ?></small><br>
                    <small><?php echo $this->configEmp['domicilio fiscal'] ?></small><br>
                   
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <b>Productor:</b><?php echo(isset($this->productor[0]['razonSocial'])?$this->productor[0]['razonSocial']:"") ?>
                    <input name="productor" id="productor" type="hidden" class="form-control" value="<?php echo(isset($this->productor[0]['id'])?$this->productor[0]['id']:"") ?>" />
                  <address>
                    <strong>Dirección : </strong><small><span id="direccion"><?php echo(isset($this->productor[0]['direccion'])?$this->productor[0]['direccion']:"") ?></span></small><br>
                    <small>Phone: <span class="telefono"><?php echo(isset($this->productor[0]['tlfPersonal1'])?$this->productor[0]['tlfPersonal1']:"") ?></span></small><br>
                    <small>Email: <span class="correo"><?php echo(isset($this->productor[0]['correoPersonal1'])?$this->productor[0]['correoPersonal1']:"") ?></span></small>
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  <b>Crédito: </b>
                  <?php echo(isset($this->datos[0]['idCredito'])?$this->datos[0]['idCredito'].' - '.$this->datos[0]['ProgFinanc']:"") ?>
                  <br>
                  <b>Fecha:</b>
                  <div class="form-group col-md-12">
                    <input name="fecha" id="fecha" type="date" class="form-control form-control" value="<?php echo date('Y-m-d') ?>" />
                  </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
 
              <!-- Table row -->
              <div class="row">
              <div class="col-md-4" style="padding-left: 10px;">    
                    <small>
                      <div class="card card-info" id="visor">    
                        
                          <?php echo $this->datos[0]['htmlResumenLiq'] ?>
                        
                        </div>
                      </small>
                   </div>  
                <div class="col-md-8 ">
                    <div class="card card-secondary card-outline">
                        <div class="card-header"><span class="card-title">Introduzca la información del Pago</span></div>
                        <div class="card-body">
                            
                            <div class="row">
                            <div class="form-group col-md-3">
                                  <label>*Forma de Pago:</label>
                                    <select class="form-control" name="forma" id="forma">
                                        <option value="0">Seleccionar</option>
                                        <option value="efectivoUsd">Efectivo Usd</option>
                                        <option value="transferenciaBs">Transferencia Bs.</option>
                                        <option value="transferenciaUsd">Transferencia Usd.</option>
                                        <option value="pagomovil">Pago Movil</option>
                                    </select>
                                </div>

                                <div class="form-group col-md-3">
                                  <label>*Orien de Fondos:</label>
                                    <select class="form-control" name="origen_fondos" id="origen_fondos">
                                    <?php foreach($this->bancos as $bnc): ?>    
                                        <option ><?php echo $bnc['Nombre'] ?></option>
                                    <?php endforeach ?>
                                    </select>
                                </div>

                                
                                <div class="form-group col-md-6">
                                  <label>*Destino de Fondos:</label>
                                    <select class="form-control" name="destino_fondos" id="destino_fondos">
                                        <option value="0">Seleccionar</option>
                                        <?php foreach($this->bancos as $bnc): ?>    
                                            <option ><?php echo $bnc['Nombre'] ?></option>
                                        <?php endforeach ?>        
                                        </select>
                                    </select>
                                </div>
                                <div class="form-group col-md-4">
                                  <label>*Nro. Cuenta</label>
                                    <input type="text"  maxlength="100" class="form-control text-right totalizar"  name="cuenta" id="cuenta"  value="0"  />
                                </div>
                                <div class="form-group col-md-4">
                                  <label>*Referencia:</label>
                                    <input type="text"  maxlength="100" class="form-control text-right totalizar"  name="referencia" id="referencia"  value="0"  />
                                </div>
                                <div class="form-group col-md-4">
                                  <label>*Monto:</label>
                                    <input type="text"  maxlength="100" class="form-control text-right totalizar"  name="monto_pago" id="monto_pago"  value="<?php echo $this->totalLiquidar ?>"  />
                                </div>   
                            </div>

                        </div>
                          
                    </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <div class="row ">
                <!-- accepted payments column -->
                <div class="col-sm-12">
                  <div class="row">
                    
                    <div class="col-md-4">
                      <div class="card card-default">
                        <div class="card-body">
                          <label class="">Comentario: </label>
                          <textarea name="comentario" id="comentario" class="form-control form-control-border" rows="2"></textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                </div>
                
                <!-- /.col -->
                
                
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- this row will not appear when printing -->
              <div class="row no-print">
                <div class="col-12">
                  <a href="<?php echo BASE_URL ?>creditos/liquidacion/index" class="btn btn-danger float-right" ><i class="fa fa-undo"></i> Cancelar</a>
                  <button type="button" class="btn btn-success float-right" style="margin-right: 5px;" id="agregar2"><i class="fa fa-floppy-o"></i> Grabar</button>
                </div>
              </div>
    </div>
    </form>            <!-- /.invoice -->
  </div><!-- /.col -->
</div><!-- /.row -->

