<?php //print_r($_layoutParams['argumentos']) ?>
<div class="row">
        <div class="col-lg-8 col-md-6">
		<ul class="nav nav-tabs">	
                    <li role="presentation"><a href="<?php echo  BASE_URL ?>almacen/clasificacion/index/">Clasificaciones</a></li>
                    <li role="presentation" class="active" ><a href="#">Grupos</a></li>
                    <li role="presentation"><a href="<?php echo  BASE_URL ?>almacen/presentacion/index/">Presentaciones</a></li>
                    <li role="presentation"><a href="<?php echo  BASE_URL ?>almacen/marca/index/">Marcas</a></li>
                    <li role="presentation"><a href="<?php echo  BASE_URL ?>configuracion/unidadmedida/index/">Unidad Medida</a></li>			
		</ul>
        <div class="panel panel-default">
        <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn">
			<a > <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                        <a  target="_blank" href="<?php echo BASE_URL ?>reporte/index/catRubrosProd/" title="Imprimir Catálogo"><button class="btn btn-default"><i class="fa fa-print"></i></button></a>
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" maxlength="100" name="busqueda" class="form-control" placeholder="Filtrar nombre">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
        </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-light-blue-active">
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Comentario</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr >
                            <td><?php echo $val['id_grupo'] ?></td>
                            <td><?php echo $val['nombre_grupo'] ?></td>
                            <td><?php echo $val['comentario_grupo'] ?></td>
                            
                            <td>
                                <?php if($val['estatus_grupo']==1): ?>
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_grupo'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>    
                            <td>
                                <?php if($val['estatus_grupo']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_grupo'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                
            </div>
          </div>
		  <div class="panel-footer" >
            <p>
                <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
            </p>
    	  </div>	
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Grupos de Producto</div>
            <div class="panel-body">
                <form name="rubro" id="rubro" method="post" autocomplete="off" action="<?php echo BASE_URL ?>almacen/grupo/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>Casificacion:</label>
                      <select name="clasificacion" id="clasificacion" class="form-control" disabled="true"> 
					  <option value="">-Seleccione-</option>
					  <?php if(isset($this->clasificacion) and count($this->clasificacion)): ?>
					  <?php foreach($this->clasificacion as $val):?>
						<option value="<?php echo $val['id_clasificacion'] ?>"><?php echo $val['nombre_clasificacion'] ?></option>	
					  <?php endforeach?>
					  <?php endif; ?>
					  </select>
                    </div>
					<div class="form-group">
                      <label>***Nombre:</label>
                      <input name="descripcion" maxlength="100" type="text" class="form-control" id="descripcion" required placeholder="Ingrese nombre del rubro" disabled="true" >
                    </div>
                    <div class="form-group">
                      <label>Comentario:</label>
                      <textarea name="comentario" maxlength="150" cols="1" rows="5" type="text" multiple="1" class="form-control" id="comentario" disabled="true"  placeholder="Ingrese un comentario"></textarea>
                    </div>
					
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>