<div class="row">
<div class="col-lg-12">
	<form name="form_recepcion_agregar" method="post" id="form_recepcion_agregar" action="<?php echo BASE_URL ?>creditos/recepcion/agregar/"  >
	<input name="guardar" id="guardar" type="hidden" value="1" />
	
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Nueva Recepción</span>
		</div>
		<div class="card-body">
			<div class="row">
            <div class="col-md-6">
                <div class="card card-secondary">
                    <div class="card-header">
                        <span class="card-title">Información del Productor</span>
                    </div>
                    <div class="card-body"> 
                        <div class="row">

                            <div class="form-group col-md-12">
                                <label>*Nombre del Productor :</label>
                                <select class="form-control select2" style="width: 100%;" name="idFiscal" id="idFiscal" >
                                    <option value="0">-SELECCIONE UNA OPCION-</option>
                                    <option value="9999999">-AGREGAR NUEVO PRODUCTOR-</option>
                                    <?php if(isset($this->productor) && count($this->productor)): ?>
                                    <?php foreach ($this->productor as $val): ?>
                                    
                                    <option value="<?php echo $val['idFiscal']  ?>"><?php echo strtoupper($val['razonSocial'])  ?></option>
                                    
                                    <?php endforeach; ?>
                                    <?php endif; ?>

                                </select>
                                <input name="idProductor" id="id_productor" type="hidden"  />
                            </div>
                            <div class="form-group col-md-12">
                                <label>*Dirección:</label>
                                <input type="text"  maxlength="100" class="form-control "  name="direccion" id="direccion"  disabled />
                            </div>
                            <div class="form-group col-md-6">
                                <label>*teléfono:</label>
                                <input type="text"  maxlength="100" class="form-control "  name="telefono" id="telefono"  disabled />
                            </div>
                            <div class="form-group col-md-6">
                                <label>*Correo Electrónico:</label>
                                <input type="email"  maxlength="100" class="form-control "  name="correo" id="correo"  disabled />
                            </div>
                        </div>
                    </div>
                </div>
      
                </div>
                <div class="col-md-6">
                        <div class="card card-secondary">
                            <div class="card-header">
                                <span class="card-title">Información de Recepción</span>
		                    </div>
                            <div class="card-body"> 
                                <div class="row">
                                    <div class="form-group col-md-4">
                                        <div class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox" id="customCheckbox2" name="aplicar_cupo" value="1">
                                            <label for="customCheckbox2" class="custom-control-label">Relacionar a Credito MetaAgricola</label>
                                        </div>
                                    </div>        
                                    <div class="form-group col-md-8">
                                        <label>*Crédito :</label>
                                        <select name="credito" id="credito" class="form-control" disabled>
                                            <option value="0">-Seleccione-</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>*Almacenadora:</label>
                                        <select name="almacenadora" id="almacenadora" class="form-control" disabled >
                                            <option value="0">-Seleccione-</option>
                                            <?php if(isset($this->proveedor) && count($this->proveedor)): ?>
                                            <?php foreach ($this->proveedor as $val): ?>
                                            <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['razonSocial'])  ?></option>
                                            <?php endforeach; ?>
                                            <?php endif; ?> 
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>*Centro de Recepción:</label>
                                        <select name="planta" id="planta" class="form-control" disabled >
                                            <option value="0">-Seleccione-</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>*Rubro:</label>
                                        <select name="rubro" id="rubro" class="form-control" >
                                        <option value="0">-Seleccione-</option>
                                        <?php if(isset($this->vrubro) && count($this->vrubro)): ?>
                                        <?php foreach ($this->vrubro as $val): ?>
                                        <?php if($val['rubro']==$this->datos[0]['rubro']): ?>
                                        <option value="<?php echo $val['rubro']  ?>" selected><?php echo strtoupper($val['rubro'])  ?></option>
                                        <?php else:  ?>
                                        <option value="<?php echo $val['rubro']  ?>"><?php echo strtoupper($val['rubro'])  ?></option>
                                        <?php endif; ?>
                                        <?php endforeach; ?>
                                        <?php endif; ?>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>*Fecha:</label>
                                        <input type="date"  class="form-control "  name="fechaRecepcion" id="fechaRecepcion" disabled  />
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>*Nro Voleta:</label>
                                        <input type="text"  maxlength="30" class="form-control "  name="nroVoleta" id="nroVoleta" disabled  />
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>*Ticket Ent:</label>
                                        <input type="text"  maxlength="30" class="form-control "  name="ticEntrada" id="ticEntrada" disabled  />
                                    </div>
                                </div>
                            </div>
                        </div>
    
                </div>
			</div>
            </br>
            <div class="card card-secondary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true">Pesaje en Romana</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false">Otra Informacion</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="row">
                                
                                <div class="col-md-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="row">    
                                                <div class="form-group col-md-8">
                                                    <label>*Conductor:</label>
                                                    <input name="conductor"  maxlength="100" type="text" class="form-control form-control-sm" id="conductor" value="" disabled />  
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label>*Id Fiscal:</label>
                                                    <input name="idFiscalConductor"  maxlength="100" type="text" class="form-control form-control-sm" id="idFiscalConductor" value="" disabled />  
                                                </div>
                                    
                                                <div class="form-group col-md-8">
                                                    <label>*Modelo de Transporte:</label>
                                                    <input name="transporte"  maxlength="100" type="text" class="form-control form-control-sm" id="transporte" value="" disabled />  
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label>*Placa:</label>
                                                    <input name="placa"  maxlength="100" type="text" class="form-control form-control-sm" id="placa" value="" disabled />  
                                                </div>

                                            </div>    
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-5">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="row">    
                                                <div class="form-group col-md-4">
                                                    <label>*Peso Entrada:</label>
                                                    <input name="pesoEntrada"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="pesoEntrada" value="0" disabled />  
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label>*Peso Salida:</label>
                                                    <input name="pesoSalida"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="pesoSalida" value="0" disabled />  
                                                </div>
                                    
                                                <div class="form-group col-md-4">
                                                    <label>*Peso Neto:</label>
                                                    <input type="text"  required maxlength="100" class="form-control form-control-sm text-right"  name="pesoNeto" id="pesoNeto" placeholder="" value="0" disabled />
                                                </div>
                                                <div class="form-group col-md-2">
                                                    <label>Hum.%</label>
                                                    <input name="porcHum"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="porcHum" value="0" disabled />  
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label>Hum. Kg:</label>
                                                    <input name="humedad"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="humedad" value="0" disabled />  
                                                </div>
                                                <div class="form-group col-md-2">
                                                    <label>*Imp. %</label>
                                                    <input name="porcImp"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="porcImp" value="0" disabled />  
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label>*Imp Kg.</label>
                                                    <input name="impureza"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="impureza" value="0" disabled />  
                                                </div>
                                               
                                                <div class="form-group col-md-4">
                                                    <label>*Acondicionado:</label>
                                                    <input type="text"  required maxlength="100" class="form-control form-control-sm text-right"  name="acondicionado" id="acondicionado" placeholder="" value="0" disabled />
                                                </div>
                                            </div>    
                                        </div>
                                    </div>
                                </div> 
                                
                                <div class="col-md-3">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="form-group col-md-12">
                                                    <label>*Infestación:</label>
                                                    <input name="infestacion"  maxlength="100" type="text" class="form-control form-control-sm text-right" id="infestacion" value="" disabled />  
                                                </div> 
                                                <div class="form-group col-md-12">
                                                    <label>*Convenio:</label>
                                                    <select name="convenio_recepcion" id="convenio_recepcion" class="form-control form-control-sm" disabled >
                                                        <option value="0">-Seleccione-</option>
                                                        <?php if(isset($this->convenio) && count($this->convenio)): ?>
                                                        <?php foreach ($this->convenio as $val): ?>
                                                        <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['nombre'])  ?></option>
                                                        <?php endforeach; ?>
                                                        <?php endif; ?> 
                                                    </select>
                                                </div>     
                                                <div class="form-group col-md-12">
                                                    <label>*Comentarios:</label>
                                                    <textarea name="comentario" id="comentario" class="form-control" rows="2" disabled></textarea>  
                                                </div>
                                        
                                            </div>    
                                        </div>
                                    </div>
                                </div> 
                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title"></span></div>
                                <div class="card-body">
                                    
                                    <div class="row">
                                   
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                        
                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>creditos/recepcion/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>



</form>
</div>

<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title">Nuevo Productor</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
            <form  name="form_cliente_agregar" id="form_cliente_agregar" method="POST" action="" autocomplete="off"  >    
                <div class="card card-secondary card-outline">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-3">
                                <label>*Tipo Persona:</label>
                                <select name="tipo" id="tipo" class="form-control">
                                    <option value="0">-Seleccione-</option>
                                    <option value="J">Juridico</option>
                                    <option value="N">Natural</option>
                                </select> 
                            </div>
                            <div class="form-group col-md-3">
                                <label>*Nro Fiscal :</label>
                                <input name="idFiscalProd"  maxlength="100" type="text" class="form-control valid_productor" id="idFiscalProd"  />  
                            </div>
                            <div class="form-group col-md-6">
                                <label>*Razon Social:</label>
                                <input type="text"  maxlength="100" class="form-control alfa_desc"  name="razon_social" id="razon_social" readonly="true"  />
                            </div>
                        
                        </div>
                        <div class="row">
                                <div class="form-group col-md-3">
                                    <label>*Estado:</label>
                                    <select name="estado" id="estado" class="form-control form-control-sm" readonly="true">
                                        <option value="">-Seleccione-</option>
                                        <?php if(isset($this->estado) && count($this->estado)): ?>
                                        <?php foreach ($this->estado as $val): ?>
                                        <?php if($val['estatus_estado']==1): ?>
                                        <option value="<?php echo $val['id_estado']  ?>"><?php echo strtoupper($val['descripcion_estado'])  ?></option>
                                        <?php endif; ?>
                                        <?php endforeach; ?>
                                        <?php endif; ?>
                                    </select>  
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Municipio:</label>
                                    <select name="municipio" id="municipio" class="form-control form-control-sm" readonly="true">
                                        <option value="">-Seleccione-</option>

                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Parroquia:</label>
                                    <select name="parroquia" id="parroquia" class="form-control form-control-sm" readonly="true">
                                        <option value="">-Seleccione-</option>

                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label>*Sector:</label>
                                    <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="sector" id="sector" placeholder="" readonly="true" />
                                </div>
                                <div class="form-group col-md-4">
                                    <label>*Direccion:</label>
                                    <input type="text"  required maxlength="100" class="form-control form-control-sm alfa_dir"  name="direccion" id="direccion" placeholder="" readonly="true" />
                                </div> 
                                <div class="form-group col-md-2">
                                    <label>*Av.</label>
                                    <input type="text"  required maxlength="100" class="form-control form-control-sm alfa_dir"  name="av" id="av" placeholder="" readonly="true" />
                                </div>
                                <div class="form-group col-md-2">
                                    <label>*Calle:</label>
                                    <input type="text"  required maxlength="100" class="form-control form-control-sm alfa_dir"   name="calle" id="calle" placeholder="" readonly="true" />
                                </div>
                                <div class="form-group col-md-2">
                                    <label>*Tipo de Vivienda:</label>
                                    <select name="tipo_vivienda" id="tipo_vivienda" class="form-control form-control-sm" readonly="true">
                                        <option value="">-Seleccione-</option>
                                        <option value="CASA">-CASA-</option>
                                        <option value="APARTAMENTO">-APARTAMENTO-</option>    
                                    </select>
                                </div>
                                <div class="form-group col-md-1">
                                    <label>*Nro.</label>
                                    <input type="number"  required maxlength="100" class="form-control form-control-sm num_entero"  name="nro" id="nro" placeholder="Ej.: 12-50" readonly="true" />
                                </div>
                                <div class="form-group col-md-1">
                                    <label>*Codigo Postal.</label>
                                    <input type="number"  required maxlength="100" class="form-control form-control-sm num_entero"  name="codigo_postal" id="codigo_postal" placeholder="Ej.: 3301"  readonly="true" />
                                </div>
                                    
                        </div>
                        <div class="row">
                                        
                            <div class="form-group col-md-2">
                                <label>*Telefono personal 1:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                    </div>
                                    <input type="text" name="tlf_prod1" class="form-control form-control-sm num_tel"  id="tlf_prod1"  readonly="true"  placeholder="___ ________">
                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-2">
                                <label>*Telefono personal 2:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                    </div>
                                    <input type="text" name="tlf_prod2" class="form-control form-control-sm num_tel"  id="tlf_prod2"  readonly="true"  placeholder="___ ________">
                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-2">
                                <label>*Telefono Oficina:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                    </div>
                                    <input type="text" name="tlf_oficina" id="tlf_oficina" class="form-control form-control-sm num_tel"    readonly="true"  placeholder="___ ________">
                                </div>
                                <!-- /.input group -->
                            </div>
                            
                            <div class="form-group col-md-3">
                                <label>Whatsapp Personal:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-commenting"></i></span>
                                    </div>
                                    <input type="text" name="tlf_wsp" id="tlf_wsp" class="form-control form-control-sm num_tel"    readonly="true"  placeholder="___ ________">
                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-3">
                                <label>Whatsapp Oficina:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-commenting"></i></span>
                                    </div>
                                    <input type="text" name="tlf_wso" id="tlf_wso" class="form-control form-control-sm num_tel"    readonly="true" placeholder="___ ________">
                                </div>
                                <!-- /.input group -->
                            </div>
                            
                            <div class="form-group col-md-4">
                                <label>Correo Personal 1:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                    </div>
                                    <input type="email" name="correo_prod1" id="correo_prod1"  class="form-control form-control-sm alfa_correo"    readonly="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                                </div>
                                <!-- /.input group -->
                            </div>        
                            
                            <div class="form-group col-md-4">
                                <label>Correo Personal 2:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                    </div>
                                    <input type="email" name="correo_prod2" id="correo_prod2"  class="form-control form-control-sm alfa_correo"    readonly="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                                </div>
                                <!-- /.input group -->
                            </div>

                            <div class="form-group col-md-4">
                                <label>Correo Empresa:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                    </div>
                                    <input type="email" name="correo_empresa" id="correo_empresa"  class="form-control form-control-sm alfa_correo"    readonly="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                                </div>
                                <!-- /.input group -->
                            </div>
                            
                                
                        </div>                    
                    </div>

                </div>                                

            </form>                                    

            </div>
            <p id="anim" style="visibility: hidden;">Procesando ......</p>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
                <button type="button" class="btn btn-xs btn-app " id="agregar_productor"><i class="fa fa-floppy-o"></i>Grabar</button>
			    <button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" data-dismiss="modal" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button>
            </div>
        </div>

    </div>

</div>

