<div class="row">
    <div class="col-12">
        <div class="card">	
			    <div class="card-header">
				    <a  href="<?php echo BASE_URL ?>almacen/movimiento/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
			    </div>
          <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Codigo</th>
                        <th>Cod-Alterno</th>
                        <th>Grupo</th>
                        <th>Sub-Grupo</th>
                        <th>Descripcion</th>
                        <th>Existencia</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['codigo'] ?></td>          
                            <td><?php echo $val['codigoAlterno'] ?></td>
                  
                            <td><?php echo $val['grupo'] ?></td>
                            <td><?php echo strtoupper($val['subGrupo']) ?></td>
                            <td><?php echo strtoupper($val['descripcion']) ?></td>
                            <td><?php echo $val['ExistenciaTotal'] ?></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>almacen/producto/editar/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>almacen/producto/eliminar/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para eliminar registro"> <i class="fa fa-trash"></i></button></td>
                            <td>
                                <a href="" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para enviar correo"> <i class="fa fa-envelope"></i></button></td>    
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                <p>
                        <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            
          </div>

        </div>
    </div>
        
</div>
