<div class="row">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header navbar-btn">
                            <a > <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>      
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" maxlength="100" class="form-control alfa_desc" placeholder="Filtrar nombre">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>
                        </form>    
                    </div>
                </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-light-blue-active">
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Acción</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>

                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        
                        <tr>
                            <td><?php echo $val['id_tipo_movimiento'] ?></td>
                            <td><?php echo ucwords($val['nombre_tipo_movimiento']) ?></td>
                            <td><?php echo strtoupper(($val['accion']=='R')?'RESTA':'SUMA') ?></td>
                            <td>
                                <?php if($val['estatus_tipo_movimiento']==1): ?>
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_tipo_movimiento'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_tipo_movimiento']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_tipo_movimiento'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_tipo_movimiento']==9): ?>
                                <button class="restaurar btn btn-default" title="Presione aquí para RESTAURAR" value="<?php echo $val['id_tipo_movimiento'] ?>"><i class="fa fa-recycle"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Tipo Movimiento</div>
            <div class="panel-body">
                <form name="form_tipoMovimiento" id="form_tipoMovimiento" method="post" autocomplete="off" action="<?php echo BASE_URL ?>configuracion/tipoMovimiento/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="1" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">               
                    <div class="form-group">
                      <label>*Nombre:</label>
                      <input name="nombre" type="text" maxlength="60" class="form-control alfa_desc" id="nombre" placeholder="Ingrese nombre del Tipo de Movimiento" required disabled="disabled" />
                    </div>
                    <div class="form-group">
                      <label>*Acción:</label>
                      <select name="accion" id="accion" class="form-control" disabled="disabled" required >
                          <option value="0">-Seleccione-</option>
                          <option value="S">SUMA</option>
                          <option value="R">RESTA</option>                
                      </select>
                    </div>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>       
                </form>    
            </div>
        </div>
    </div>    
</div>
