<div class="row">
    <div class="col-lg-8 col-md-6">
        <div class="card card-default">                        
            <div class="card-header">
                <a class=""> <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>                  
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="busqueda" maxlength="60" class="form-control alfa_desc" placeholder="Filtrar nombre">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>

                        </div>
                    </div>        
                </div>
            </div>    

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr class="bg-secondary color-palette" >
                            <th>Código</td>                     
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Clave</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; ?>    
                        <?php if(isset($this->lista) && count($this->lista)) :?>
                            <?php foreach ($this->lista as $val) :?>
                            <tr>
                                <td><?php echo $val['id'] ?></td>
                                <td><?php echo ucwords($val['nombre_permiso']) ?></td>
                                <td><?php echo ucfirst($val['descripcion_permiso']) ?></td>
                                <td><?php echo $val['clave'] ?></td>
                                <td>
                                    <?php if($val['estatus_permiso']==1): ?>
                                    <button  class="editar btn btn-default"   title="Presione aquí para EDITAR" value="<?php echo $val['id'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                    <?php endif; ?>
                                </td>   
                                <td>
                                    <?php if($val['estatus_permiso']==1): ?>
                                    <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id'] ?>"><i class="fa fa-trash-o"></i></button>
                                    <?php endif; ?>
                                </td> 
                            </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                    </table>
                    <hr>
                    <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                    </p>
                </div>
            </div>
        </div>    
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card card-default">
            <div class="card-header">Gestión de Permisos</div>
            <div class="card-body">
                <form name="form_permiso" id="form_permiso" method="post" autocomplete="off" action="<?php echo BASE_URL ?>seguridad/permiso/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>*Nombre:</label>
                      <input name="nombre" type="text" maxlength="20" disabled="disabled" class="form-control alfa_desc" id="nombre" placeholder="Ingrese nombre del permiso" required>
                    </div>
                    <div class="form-group">
                      <label>*Descripción:</label>
                      <input name="descripcion" type="text" maxlength="100" class="form-control alfa_desc" id="descripcion" disabled="disabled" placeholder="Ingrese descripción del permiso" required>
                    </div>
                    <div class="form-group">
                      <label>*Clave:</label>
                      <input name="clave" type="text" maxlength="20" disabled="disabled" class="form-control alfa_desc" id="clave" placeholder="Ingrese clave del permiso" required>
                    </div>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>
