<?php if($this->msj['status']=="success"): ?>
    <div class="callout callout-success">
        <h2 class="headline text-success"><i class="fa fa-thumbs-o-up"></i></h2>
        <div class="error-content">
            <h3><?php echo $this->msj['status'] ?></h3>
            <p><?php echo $this->msj['response'] ?>
                <a href="<?php echo BASE_URL ?><?php echo $this->modulo ?>/<?php echo $this->controlador ?>/"> Retornar </a>
            </p>
            <p>
                Para crear un nuevo registro presione el siguiente link
                <a href="<?php echo BASE_URL ?><?php echo $this->modulo ?>/<?php echo $this->controlador ?>/agregar/"> Nuevo Registro </a>
            </p>
        </div>
    </div>
<?php endif ?>
<?php if($this->msj['status']=="fail"): ?>    
    <div class="callout callout-warning">
        <h2 class="headline text-warning"></h2>
        <div class="error-content">
            <h3><i class="fas fa-exclamation-triangle text-warning"></i><?php echo $this->msj['status'] ?></h3>
            <p><?php echo $this->msj['response'] ?>
                 <a href="<?php echo BASE_URL ?><?php echo $this->modulo ?>/<?php echo $this->controlador ?>/"> Retornar </a>
            </p>

        </div>
    </div>
<?php endif ?>    