<div class="row">
    <div class="col-lg-8 col-md-6">
        <div class="card card-default">        
                
            <div class="card-header">
                <a class=""> <button class="nuevo btn btn-default btn-sm" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>                  
                
            </div>    

            <div class="card-body">
                
                    <table class="table table-bordered table-striped" id="example1" >
                        <thead>
                            <tr class="bg-secondary color-palette" >
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Sigla</td>
                            <th>Estado</td>
                            <th>Numerador</td>
                            <th>Plantilla</td> 
                            <th width="30" ></th>
                            <th width="30"></th>
                            <th width="30"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; ?>    
                        <?php if(isset($this->lista) && count($this->lista)) :?>
                            <?php foreach ($this->lista as $val) :?>
                            <tr>
                                <td><?php echo $val['id'] ?></td>
                                <td><?php echo ucwords($val['nombre']) ?></td>
                                <td><?php echo $val['sigla'] ?></td>
                                <td><?php echo $val['estado'] ?></td>
                                <td><?php echo $val['contador'] ?></td>
                                <td><?php echo $val['plantilla'] ?></td>
                                <td>
                                    
                                    <button class="editar btn btn-default btn-sm" title="Presione aquí para EDITAR" value="<?php echo $val['id'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                    
                                </td>    
                                <td>
                                    
                                    <button class="eliminar btn btn-default btn-sm" title="Presione aquí para ELIMINAR" value="<?php echo $val['id'] ?>"><i class="fa fa-trash-o"></i></button>
                                    
                                </td>
                                <td>
                                    <button class="btn btn-default btn-sm plantilla" value="<?php echo $val['plantilla'] ?>" data-toggle="modal" data-target="#modal-xl"> <i class="fa fa-folder-open-o"></i></button>
                                </td>
                            </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                        <tfoot>
                      
                        </tfoot>
                    </table>
                    <hr>
                    
                
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card card-default">
            <div class="card-header">Registro de Documentos</div>
            <div class="card-body">
                <form name="form_documento" id="form_documento" method="post" autocomplete="off" action="<?php echo BASE_URL ?>configuracion/documento/agregar/">
                    <input name="guardar"  type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">                    
                    
                    <div class="form-group">
                        <label>Nombre :</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="nombre" id="nombre"  class="form-control"    disabled="true"  placeholder=""/>
                        </div>
                        <!-- /.input group -->
                    </div>
                    <div class="form-group ">
                        <label>*Descripcion:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                            </div>
                            <input type="text" name="descripcion" class="form-control "  id="descripcion"  disabled="true" >
                        </div>
                        <!-- /.input group -->
                    </div>
                    <div class="form-group">
                        <label>Siglas:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                            </div>
                            <input type="text" name="sigla" id="sigla"  class="form-control alfa_correo"    disabled="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                        </div>
                        <!-- /.input group -->
                    </div> 
                    <div class="form-group">
                        <label>Contador :</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-barcode"></i></span>
                            </div>
                            <select  name="contador" id="contador"  class="form-control" disabled="true"  placeholder="">
                                <option value="0">Seleccione</option>
                                <?php if(isset($this->numeradores) && count($this->numeradores)) :?>
                                    <?php foreach ($this->numeradores as $key =>$val) :?>
                                        <option value="<?php echo $key ?>"><?php echo $key .' ->'.$val ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>    
                        </div>
                        <!-- /.input group -->
                    </div>
                    <div class="form-group">
                        <label>Plantilla :</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa-solid fa-paint-roller"></i></span>
                            </div>
                            <select  name="plantilla" id="plantilla"  class="form-control" disabled="true"  placeholder="">
                                <option value="0">Seleccione</option>
                                <?php if(isset($this->plantilla) && count($this->plantilla)) :?>
                                    <?php foreach ($this->plantilla as $plan) :?>
                                        <option value="<?php echo $plan['nombre'] ?>"><?php echo $plan['nombre'] ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>    
                        </div>
                        <!-- /.input group -->
                    </div>
                    <hr>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-xs btn-app"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-xs btn-app bg-danger color-palette"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>

<div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title ">Informacion del Documento</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Ult. Numero Generado :</label>
                                <div class="input-group col-md-6">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-solid fa-hashtag"></i></span>
                                    </div>
                                    <input  type="text" name="numerador" id="numerador"  class="form-control"    disabled="true"  placeholder=""/>   
                                </div>
                            <!-- /.input group -->
                            </div>
                            <div class="form-group">
                                <label>Usuario Generador :</label>
                                <div class="input-group col-md-6">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-barcode"></i></span>
                                    </div>
                                    <input  type="text" name="numerador" id="numerador"  class="form-control"    disabled="true"  placeholder=""/>   
                                </div>
                            <!-- /.input group -->
                            </div>
                        
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Cambiar Numerador de Documento :</label>
                                <div class="input-group  col-md-6">
                                    <input type="text" class="form-control">
                                    <span class="input-group-append">
                                        <button type="button" class="btn btn-info btn-flat"><i class="fa-solid fa-file-pen"></i></button>
                                    </span>
                                </div>            
                            </div>            
                          <hr> 
                        
                            <div class="form-group">
                                <button type="button" class="btn btn-default " id="" title="Actualiza los precios de las notas generadas con los precios actuales del Inventario " value="" ><i  class="fa fa-eye"></i> Actualizar Precios en Notas Generadas</button>
                            </div>


                        </div>
                    </div>    
                </div>
            </div>    

            <div class="card card-default">
                    <div class="card-header"><span>Vista Previa</span>
                    </div> 
                    <div class="card-body">
                        <div class="col-md-12">
                            <div id="nota" style="overflow-x: auto; overflow-y: auto;width: 100%;" ></div>   
                        </div>
                    </div> 
                </div>                
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
               
                <button type="button" class="btn btn-primary" id="imprimir"><i class="fa fa-print"></i></button>
            </div>
        </div>

    </div>

</div>
