<div class="row">
<div class="col-lg-12">
	<form name="form_finca_agregar" method="post" id="form_finca_agregar" action="<?php echo BASE_URL ?>productores/finca/agregar/"  >
	<input name="guardar" id="guardar" type="hidden" value="1" />
	
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Ingrese la informacion para el nuevo registro </span>
		</div>
		<div class="card-body">
			<div class="row">
					<div class="form-group col-md-4">
						<label>*Nombre de la Unidad:</label>
						<input type="text"  maxlength="100" class="form-control "  name="nomUnidad" id="nomUnidad"   />
					</div>
                    <div class="form-group col-md-4">
						<label>*Nombre del Propietario:</label>
						<input type="text"  maxlength="100" class="form-control "  name="nomPropietario" id="nomPropietario"   />
					</div>
					<div class="form-group col-md-4">
						<label>*Id Fiscal Propietario:</label>
						<input type="text"  maxlength="100" class="form-control "  name="idFiscal" id="idFiscal"   />
					</div>
                    <div class="form-group col-md-3">
						<label>*Superficie (Ha):</label>
						<input type="number"  maxlength="100" class="form-control "  name="superfUnidad" id="superfUnidad"   />
					</div>
                    <div class="form-group col-md-3">
						<label>*Tipo de Suelo:</label>
						<input type="text"  maxlength="100" class="form-control "  name="tipoSuelo" id="tipoSuelo"   />
					</div>
                    <div class="form-group col-md-3">
						<label>*Tenencia de Tierra:</label>
						<textarea   class="form-control "  name="tenenciaTierra" id="tenenciaTierra"   ></textarea>
					</div>
                    <div class="form-group col-md-3">
						<label>*Comentarios:</label>
						<textarea   class="form-control "  name="comentario" id="comentario"   ></textarea>
					</div>

			</div>
            </br>
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true"><i class="fa fa-map-o"></i> Direccion</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false"><i class="fa  fa-book"></i> Contactos</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-lote-tab" data-toggle="pill" href="#custom-tabs-four-lote" role="tab" aria-controls="custom-tabs-four-lote" aria-selected="false"><i class="fa   fa-map-marker"></i> Lotes</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue mediao de contactos para de la Unidad de Produccion</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-3">
                                            <label>*Estado:</label>
                                            <select name="estado" id="estado" class="form-control form-control-sm" >
                                                <option value="">-Seleccione-</option>
                                                <?php if(isset($this->estado) && count($this->estado)): ?>
                                                <?php foreach ($this->estado as $val): ?>
                                                <?php if($val['estatus_estado']==1): ?>
                                                <option value="<?php echo $val['id_estado']  ?>"><?php echo strtoupper($val['descripcion_estado'])  ?></option>
                                                <?php endif; ?>
                                                <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>  
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Municipio:</label>
                                            <select name="municipio" id="municipio" class="form-control form-control-sm" >
                                                <option value="">-Seleccione-</option>

                                            </select>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Parroquia:</label>
                                            <select name="parroquia" id="parroquia" class="form-control form-control-sm" >
                                                <option value="">-Seleccione-</option>

                                            </select>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Sector:</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="sector" id="sector" placeholder=""  />
                                        </div>
                                        <div class="form-group col-md-8">
                                            <label>*Direccion</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="direccion" id="direccion" placeholder=""  />
                                        </div> 
                                        <div class="form-group col-md-4">
                                            <label>*Coordenadas.</label>
                                            
                                            <div class="input-group ">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fa fa-map-marker"></i></span>
                                                </div>
                                                <input type="text" class="form-control" placeholder="Lat:" name="latitudFinca" id="latitudFinca" disabled/>
                                            </div>
                                            <div class="input-group ">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fa fa-map-marker"></i></span>
                                                </div>
                                                <input type="text" class="form-control" placeholder="Lon:"  name="longitudFinca" id="longitudFinca" disabled>
                                            </div>
                                        </div>
                                                                                   
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para contactar al productor</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-4">
                                            <label>*Telefono propietario:</label>
                                            <input name="tlf_propietario"  maxlength="100" type="tel" class="form-control form-control-sm" id="tlf_propietario"   />  
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Telefono Finca:</label>
                                            <input name="tlf_finca"  maxlength="100" type="tel" class="form-control form-control-sm" id="tlf_finca"  />  
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Telefono Encargado:</label>
                                            <input type="tel"  required maxlength="20" class="form-control form-control-sm"  name="tlf_encargado" id="tlf_encargado"   />
                                        </div>
                                         
                                        <div class="form-group col-md-4">
                                            <label>*Correo Propietario</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_propietario" id="correo_propietario" placeholder="Ej.: micorreo@hotmail.com"  />
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Correo Finca</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_finca" id="correo_finca" placeholder="Ej.: micorreo@hotmail.com"   />
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Correo Encargado</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_encargado" id="correo_encargado" placeholder="Ej.: micorreo@hotmail.com"  />
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-lote" role="tabpanel" aria-labelledby="custom-tabs-four-lote-tab">
                            <div class="card">
                                <div class="card-header"><button class="btn btn-default btn-sm" type="button" id="add_lotes" title="Agregar servicio a cliente"><i class="fa fa-plus"></i></button><span class="card-title">Agregue informacion de lotes </span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <table class="table table-bordered" id="tabla_servicios">
                                                <thead>
                                                    <tr>
                                                        <th width="80">Nro</th>
                                                        <th width="200">Superficie (Ha).</th>
                                                        <th width="200">Coordenadas</th>
                                                        <th width="120">Estado</th>
                                                        <th width="30"></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                </tbody>
                                            </table>
                                        </div>             
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                        
                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>productores/finca/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
