<div class="row">
<div class="col-lg-12">
	<form name="form_finca_agregar" method="post" id="form_finca_agregar" action="<?php echo BASE_URL ?>productores/finca/editar/"  >
	<input name="guardar" id="guardar" type="hidden" value="2" />
	<input name="id" id="id" type="hidden"  value="<?php echo (!empty($this->datos[0]['id']))?$this->datos[0]['id']:"" ?>" />
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Editar Unidad de Produccion</span>
		</div>
		<div class="card-body">
			<div class="row">
										
					<div class="form-group col-md-4">
						<label>*Nombre de la Unidad:</label>
						<input type="text"  maxlength="100" class="form-control "  name="nomUnidad" id="nomUnidad"  value="<?php echo (!empty($this->datos[0]['nombre']))?$this->datos[0]['nombre']:"" ?>" />
					</div>
                    <div class="form-group col-md-4">
						<label>*Nombre del Propietario:</label>
						<input type="text"  maxlength="100" class="form-control "  name="nomPropietario" id="nomPropietario" value="<?php echo (!empty($this->datos[0]['nombrePropietario']))?$this->datos[0]['nombrePropietario']:"" ?>"  />
					</div>
					<div class="form-group col-md-4">
						<label>*Id Fiscal Propietario:</label>
						<input type="text"  maxlength="100" class="form-control "  name="idFiscal" id="idFiscal" value="<?php echo (!empty($this->datos[0]['idFiscalPropietario']))?$this->datos[0]['idFiscalPropietario']:"" ?>"  />
					</div>
                    <div class="form-group col-md-3">
						<label>*Superficie (Ha):</label>
						<input type="text"  maxlength="100" class="form-control "  name="superfUnidad" id="superfUnidad" value="<?php echo (!empty($this->datos[0]['superficie']))?$this->datos[0]['superficie']:"" ?>"  />
					</div>
                    <div class="form-group col-md-3">
						<label>*Tipo de Suelo:</label>
						<input type="text"  maxlength="100" class="form-control "  name="tipoSuelo" id="tipoSuelo" value="<?php echo (!empty($this->datos[0]['tipoSuelos']))?$this->datos[0]['tipoSuelos']:"" ?>"  />
					</div>
                    <div class="form-group col-md-3">
						<label>*Tenencia de Tierra:</label>
						<textarea   class="form-control "  name="tenenciaTierra" id="tenenciaTierra"   ><?php echo (!empty($this->datos[0]['teneciaTierra']))?$this->datos[0]['teneciaTierra']:"" ?></textarea>
					</div>
                    <div class="form-group col-md-3">
						<label>*Comentarios:</label>
						<textarea   class="form-control "  name="comentario" id="comentario"   ><?php echo (!empty($this->datos[0]['comentarios']))?$this->datos[0]['comentarios']:"" ?></textarea>
					</div>

			</div>
            </br>
            <div class="card card-secondary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true">Direccion</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false">Contactos</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-lote-tab" data-toggle="pill" href="#custom-tabs-four-lote" role="tab" aria-controls="custom-tabs-four-lote" aria-selected="false">Lotes</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue mediao de contactos para de la Unidad de Produccion</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-3">
                                            <label>*Estado:</label>
                                            <select name="estado" id="estado" class="form-control form-control-sm" >
                                            <option value="">-Seleccione-</option>
                                                <?php if(isset($this->estado) && count($this->estado)): ?>
                                                <?php foreach ($this->estado as $val): ?>
                                                <?php if($val['id_estado']==$this->datos[0]['estado']): ?>
                                                <option value="<?php echo $val['id_estado']  ?>" selected><?php echo strtoupper($val['descripcion_estado'])  ?></option>
                                                <?php else:  ?>
                                                <option value="<?php echo $val['id_estado']  ?>"><?php echo strtoupper($val['descripcion_estado'])  ?></option>
                                                <?php endif; ?>
                                                <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>  
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Municipio:</label>
                                            <select name="municipio" id="municipio" class="form-control form-control-sm" >
                                                <option value="">-Seleccione-</option>
                                                <?php if(isset($this->municipio) && count($this->municipio)): ?>
                                                <?php foreach ($this->municipio as $val): ?>
                                                <?php if($val['id_municipio']==$this->datos[0]['municipio']): ?>
                                                <option value="<?php echo $val['id_municipio']  ?>" selected><?php echo strtoupper($val['descripcion_municipio'])  ?></option>
                                                <?php else:  ?>
                                                <option value="<?php echo $val['id_municipio']  ?>"><?php echo strtoupper($val['descripcion_municipio'])  ?></option>
                                                <?php endif; ?>
                                                <?php endforeach; ?>
                                                <?php endif; ?>    
                                            </select>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Parroquia:</label>
                                            <select name="parroquia" id="parroquia" class="form-control form-control-sm" >
                                                <option value="">-Seleccione-</option>
                                                    <?php if(isset($this->parroquia) && count($this->parroquia)): ?>
                                                    <?php foreach ($this->parroquia as $val): ?>
                                                    <?php if($val['id_parroquia']==$this->datos[0]['parroquia']): ?>
                                                    <option value="<?php echo $val['id_parroquia']  ?>" selected><?php echo strtoupper($val['descripcion_parroquia'])  ?></option>
                                                    <?php else:  ?>
                                                    <option value="<?php echo $val['id_parroquia']  ?>"><?php echo strtoupper($val['descripcion_parroquia'])  ?></option>
                                                    <?php endif; ?>
                                                    <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Sector:</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="sector" id="sector" placeholder="" value="<?php echo (!empty($this->datos[0]['dirSector']))? $this->datos[0]['dirSector']:''  ?>" />
                                        </div>
                                        <div class="form-group col-md-8">
                                            <label>*Direccion</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="direccion" id="direccion" placeholder=""  value="<?php echo (!empty($this->datos[0]['direccion']))? $this->datos[0]['direccion']:''  ?>" />
                                        </div> 
                                        <div class="form-group col-md-4">
                                            <label>*Coordenadas.</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="coordUnidad" id="coordUnidad" placeholder="" value="<?php echo (!empty($this->datos[0]['geoloc']))? $this->datos[0]['geoloc']:''  ?>" />
                                        </div>
                                        
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para contactar al productor</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-4">
                                            <label>*Telefono propietario:</label>
                                            <input name="tlf_propietario"  maxlength="100" type="text" class="form-control form-control-sm" id="tlf_propietario" value="<?php echo (!empty($this->datos[0]['telefonosPropietario']))? $this->datos[0]['telefonosPropietario']:''  ?>"  />  
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Telefono Finca:</label>
                                            <input name="tlf_finca"  maxlength="100" type="text" class="form-control form-control-sm" id="tlf_finca" value="<?php echo (!empty($this->datos[0]['telefonosFinca']))? $this->datos[0]['telefonosFinca']:''  ?>" />  
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Telefono Encargado:</label>
                                            <input type="text"  required maxlength="20" class="form-control form-control-sm"  name="tlf_encargado" id="tlf_encargado"  value="<?php echo (!empty($this->datos[0]['telefonosEncargado']))? $this->datos[0]['telefonosEncargado']:''  ?>" />
                                        </div>
                                         
                                        <div class="form-group col-md-4">
                                            <label>*Correo Propietario</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_propietario" id="correo_propietario" placeholder="Ej.: micorreo@hotmail.com" value="<?php echo (!empty($this->datos[0]['correosPropietario']))? $this->datos[0]['correosPropietario']:''  ?>" />
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Correo Finca</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_finca" id="correo_finca" placeholder="Ej.: micorreo@hotmail.com" value="<?php echo (!empty($this->datos[0]['correosFinca']))? $this->datos[0]['correosFinca']:''  ?>"  />
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Correo Encargado</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_encargado" id="correo_encargado" placeholder="Ej.: micorreo@hotmail.com" value="<?php echo (!empty($this->datos[0]['correosEncargado']))? $this->datos[0]['correosEncargado']:''  ?>" />
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-lote" role="tabpanel" aria-labelledby="custom-tabs-four-lote-tab">
                            <div class="card">
                                <div class="card-header"><button class="btn btn-default btn-sm" type="button" id="add_lotes" title="Agregar servicio a cliente"><i class="fa fa-plus"></i></button><span class="card-title">Agregue informacion de lotes </span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <table class="table table-bordered" id="tabla_servicios">
                                                <thead>
                                                    <tr>
                                                        <th width="80">Nro</th>
                                                        <th width="200">Superficie (Ha).</th>
                                                        <th width="200">Coordenadas</th>
                                                        <th width="120">Estado</th>
                                                        <th width="30"></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php 
                                                    
                                                    if(isset($this->lotes)):  ?>
                                                     <?php foreach($this->lotes as $val): ?>
                                                        <tr>
                                                        <th ><?php echo $val['nro'] ?></th>
                                                        <th ><?php echo $val['superficie'] ?></th>
                                                        <th >Coordenadas</th>
                                                        <th ><?php echo $val['estado'] ?></th>
                                                        <th ></th>
                                                        <tr>
                                                     <?php endforeach ?>   
                                                     <?php ?>       
                                                   <?php endif ?>     
                                                </tbody>
                                            </table>
                                        </div>             
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                        
                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>productores/finca/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
