<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="card">
			
			    <div class="card-header">
				    <a  href="<?php echo BASE_URL ?>administracion/cliente/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>
				        <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                      </button>
                    </div>
                  </div>
                </div>
			    </div>
 
          <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Usuario</th>
                        <th>Teléfono</th>
                        <th>Correo Electrónico</th>
                        <th>Condición</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo ucwords($val['alias_usuario']) ?></td>
                            
                            <td><?php echo $val['telefono_usuario'] ?></td>
                  
                            <td><?php echo $val['correo_usuario'] ?></td>
                            <td><?php echo strtoupper($val['condicion_usuario']) ?></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>seguridad/usuario/editar/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para EDITAR"> <i class="fa fa-pencil-square"></i></button>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>seguridad/usuario/permisoUsuario/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para AGREGAR PERMISOS para el usuario"> <i class="fa fa-shield"></i></button></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>seguridad/usuario/mantenimientoUsuario/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para el mantenimiento del usuario"> <i class="fa fa-wrench"></i></button></td>    
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>
