<div class="row">
        <div class="col-lg-8 col-md-6">
        	<ul class="nav nav-tabs">
				<li role="presentation" ><a href="<?php echo  BASE_URL ?>configuracion/estado/index">Estados</a></li>
				<li role="presentation" ><a href="<?php echo  BASE_URL ?>configuracion/municipio/index/">Municipios</a></li>
				<li role="presentation" class="active"><a href="<?php echo  BASE_URL ?>configuracion/sector/index/">Sectores</a></li>
			</ul>
        <div class="panel panel-default">

        <div class="">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header navbar-btn">
                    <a class=""> <button class="nuevo btn btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                </div>
                <form class="navbar-form navbar-right" role="search" action="" method="post">
                    <div class="form-group">
                        <input type="text" name="busqueda" class="form-control" placeholder="Filtrar descripción">
                    </div>
                    <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>
                </form>
            </div>
        </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-light-blue-active">
                        <th>Código</th>
                        <th>Descripción</th>
                        <th>Parroquia</th>
                        <th>Creación</td>
                        <th>Estatus</th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>

                        <tr>
                            <td><?php echo $val['id_sector'] ?></td>
                            <td><?php echo ucfirst($val['descripcion_sector']) ?></td>
                            <td><?php echo ucfirst($val['medida']) ?></td>
                            <td><?php echo date('d-m-Y',strtotime($val['fecha_creacion'])) ?></td>
                            <td><?php echo ($val['estatus_sector']==1)?'Activo':'Inactivo' ?></td>
                            <td>
                                <?php if($val['estatus_sector']==1): ?>
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_sector'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_sector']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_sector'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion;  ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Sector</div>
            <div class="panel-body">
                <form name="sector" id="sector" method="post" autocomplete="off" action="<?php echo BASE_URL ?>configuracion/sector/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="" id="aux">
					          <div class="form-group">
                      <label>Estado:</label>
                      <select name="estado" id="estado" class="form-control" disabled="true">
                          <option>-Seleccione-</option>
                          <?php if(isset($this->estado) && count($this->estado)): ?>
                                <?php foreach ($this->estado as $val): ?>
                                    <?php if($val['estatus_estado']==1): ?>
                                    <option value="<?php echo $val['id_estado']  ?>"><?php echo strtoupper($val['descripcion_estado'])  ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                          <?php endif; ?>
                      </select>
                    </div>
					          <div class="form-group">
                      <label>Municipio:</label>
                      <select name="municipio" id="municipio" class="form-control" disabled="true">
                          <option>-Seleccione-</option>

                      </select>
                    </div>
					          <div class="form-group">
                      <label>Nombre Sector:</label>
                      <input name="descripcion" type="text" class="form-control" id="descripcion" placeholder="Ingrese nombre del sector" required disabled="true" />
                    </div>

                    <button type="button" disabled="true" title="Presione aquí para Guardar el registro" name="agregar" id="agregar" class="btn btn-primary" ><i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="true" name="cancelar" title="Presione aquí para VACIAR el formulario" id="cancelar" class="btn btn-danger"><i class="fa fa-undo"></i> Cancelar</button>
                </form>
            </div>
        </div>
    </div>
</div>
