<div class="row">
<div class="col-lg-12">
	<form name="form_recepcion_agregar" method="post" id="form_recepcion_agregar" action="<?php echo BASE_URL ?>almacen/recepcion/agregar/"  >
	<input name="guardar" id="guardar" type="hidden" value="1" />
	
	<div class="card card-secondary card-outline">
		
		<div class="card-body">
			<div class="row">
                <div class="col-lg-6">    
                    <div class="card  card-outline" >
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label>*Origen de Recepción:</label>
                                    <div class="custom-control custom-radio" bis_skin_checked="1">
                                        <input class="custom-control-input custom-control-input-danger custom-control-input-outline" type="radio" checked id="customRadio5" name="tipo" value="proveedor" >
                                        <label for="customRadio5" class="custom-control-label">Proveedor</label>
                                    </div>
                                    <div class="custom-control custom-radio" bis_skin_checked="1">
                                        <input class="custom-control-input custom-control-input-danger custom-control-input-outline" type="radio" id="customRadio6" name="tipo" value="productor">
                                        <label for="customRadio6" class="custom-control-label">Productor</label>
                                    </div>
                                </div>     
								<div class="form-group col-md-6">
                                    <div id="visor-destino">
                                        <label>*Proveedor:</label>
                                        <select name="destino" id="dsp_destino" class="form-control select2">
                                            <option value="-">-Seleccione-</option>
                                            <?php if(count($this->proveedor)): ?>
                                                <?php foreach($this->proveedor as $pro): ?>
                                                    <option value="<?php echo $pro['id'] ?>"><?php echo strtoupper($pro['razonSocial']) ?></option>
                                                <?php endforeach;?>
                                            <?php endif; ?>	
                                        </select>
                                    </div>
                                </div>
                                
                            </div>    
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">    
                    <div class="card  card-outline" >
                       
                        <div class="card-body">
                            <div class="row">
           
                                <div class="form-group col-md-6">
									<label>*Almacen de recepción:</label>
									<select name="almacen_id" id="almacen_id" class="form-control">
										<option value="-">-Seleccione-</option>
										<?php if(count($this->almacen)): ?>
											<?php foreach($this->almacen as $val): ?>
												<option value="<?php echo $val['id'] ?>"><?php echo strtoupper($val['nombre']) ?></option>
											<?php endforeach;?>
										<?php endif; ?>										
									</select> 
								</div>
								<div class="form-group col-md-3">
                                    <label>*Documento:</label>
                                    <select name="tipoDocumento" id="tipoDocumento" class="form-control">
                                        <option value="-">-Seleccione-</option>
                                        <option value="FAC">FACTURA</option>
                                        <option value="NE">NOTA DE ENTREGA</option>
                                        <option value="DOD">DOC. DE DONACION</option>
                                        <option value="N-A">NO APLICA</option>
                                    </select> 
                                </div>
                                
                                <div class="form-group col-md-3">
									<label>*Correlatio :</label>
										<input name="correlativo"  maxlength="30" type="text" class="form-control" id="correlativo" readonly/>  
									</div>
                                <div class="form-group col-md-3">
                                    <label>*Fecha Emision :</label>
                                    <input name="emision"  type="date" class="form-control" id="emision"  />  
                                </div>
								<div class="form-group col-md-3">
                                    <label>*Fecha Vencimiento :</label>
                                    <input name="vencimiento"  type="date" class="form-control" id="vencimiento"  />  
                                </div>
                                <div class="form-group col-md-6">
                                    <label>*Comentario :</label>
                                    <textarea name="comentario"  class="form-control" id="comentario" rows="2" ></textarea>  
                                </div>
								
                            </div>
                        </div>
                    </div>
                </div>
            </div>         
	
            </br>
		
            <div class="row">				
                <div class="col-md-9">
                    <div class="card ">
                        <div class="card-header">
                            
                        <button type="button" class="btn btn-default" id="add_producto" ><i class="fa fa-cubes"></i><span class="h6"> Agregar Producto </span></button>	
                            
                        </div>
                        <div class="card-body">
                            <table class="table table-sm" id="productos">
                                <thead>
                                <tr class="bg-secondary color-palette">                            
                                <th style="width: 170px;" >Codigo</th>
                                <th style="width: 470px;">Description</th>
                                <th style="width: 120px;">Cantidad</th>
                                <th style="width: 150px;">Pvp</th>
                                <th style="width: 260px;">Alamacen de Recepcion</th>            
                                <th style="width: 32px;"></th>
                                </tr>
                                </thead>
                                <tbody>
                                            
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card ">
                        <div class="form-group col-md-12">
                            <label>*SubTotal :</label>
                            <input name="subtotalDoc"  maxlength="30" type="text" class="form-control" id="subtotalDoc" value="0,0"  />  
                        </div> 
                        <div class="form-group col-md-12">
                            <label>*Total :</label>
                            <input name="totalDoc"  maxlength="30" type="text" class="form-control" id="totalDoc" value="0,0"  />  
                        </div>                          

                    </div>
                </div>
                        
            </div>	


		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar" ><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>almacen/recepcion/index/"><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
  
  </form>		  
</div>


<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="myModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">    
        <div class="modal-body">
            <div class="card">
                <div class="card-header">
                    <h3></h3>
                    <div class="card-title">
                        <div class="input-group input-group-sm">
                            <input type="text" id="search_producto" name="search_producto" class="form-control float-right " size="50" />
                            <div class="input-group-append">
                                <button type="button" name="search" id="search" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                            <input name="fila" id="fila" type="hidden" value="0" />
                        </div>
                    </div>
                </div>                      
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap" id="tabla">
                        <thead>
                            <tr class="bg-light-blue-active" >
                                
                                <th width='400'>Descripcion</th>
                                <th width='150'>Presentacion</th>
                                <th width='150'>Almacen</th>
                                <th width='150'>Exist</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>          
                </div>
                <div class="card-footer">
                    
               </div> 
            </div>
        </div>
    </div>
    </div>
</div>




</div>

