<div class="row">
    <div class="col-12">
        <form name="form_recepcion_eliminar" method="post" id="form_recepcion_eliminar" action="<?php echo BASE_URL ?>almacen/recepcion/anular/">
        <input name="anular" id="anular" type="hidden" value="3" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->mov[0]['id']))? $this->mov[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Anulación de Despacho</h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta seguro de ! Anular ! el registro de Recepción:</h3>
                        

                        <dl class="row">
                            <dt class="col-sm-4">Correlativo  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->mov[0]['id']))?$this->mov[0]['id']:"" ?></dd>
                            <dt class="col-sm-4">Fecha de Recepción :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->mov[0]['fechas_fecCargaReg']))?$this->mov[0]['fechas_fecCargaReg']:"" ?></dd>
                            <dt class="col-sm-4">Proveedor :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->mov[0]['nombreProveedor']))?$this->mov[0]['nombreProveedor']:"" ?></dd>
                            <dt class="col-sm-4">Documento :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->mov[0]['origen_TipDoc']))?$this->mov[0]['origen_TipDoc'].'-'.$this->mov[0]['origen_NroDoc']:"" ?></dd>
                            <dt class="col-sm-4">Almacén de Recepción  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->mov[0]['nombreAlmacen']))?$this->mov[0]['nombreAlmacen']:"" ?></dd>
                                   
                        </dl>
                        

                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>*Fecha de Anulación:</label>
                        <input type="date" class="form-control"  name="fechaAnulacion" id="fechaAnulacion"  value="<?php echo date('Y-m-d') ?>" />
                    </div>
                    <div class="form-group col-md-6">
                        <label>*Comentario:</label>
                        <input type="text" class="form-control"  name="comentario" id="comentario"   />
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>almacen/recepcion/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
