<div class="row">
<div class="col-lg-12">
	<form name="form_programa_editar" method="post" id="form_programa_editar" action="<?php echo BASE_URL ?>financiamiento/programa/editar/"  >
	<input name="guardar" id="guardar" type="hidden" value="2" />
	<input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))?$this->datos[0]['id']:"" ?>" />
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Editar Programa de Financiamiento</span>
		</div>
		<div class="card-body">
			<div class="row">
                    <div class="form-group col-md-2">
						<label>*Inicio del Programa:</label>
						<input type="date"  class="form-control "  name="fechaInicio" id="fechaInicio" value="<?php echo (!empty($this->datos[0]['fechaInicio']))?$this->datos[0]['fechaInicio']:"" ?>" />
					</div>
                    <div class="form-group col-md-2">
						<label>*Final del Programa:</label>
						<input type="date" class="form-control "  name="fechaFinal" id="fechaFinal"  value="<?php echo (!empty($this->datos[0]['fechaFinal']))?$this->datos[0]['fechaFinal']:"" ?>"  />
					</div>
					<div class="form-group col-md-2">
						<label>*Rubro:</label>
						<select name="rubro" id="rubro" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->vrubro) && count($this->vrubro)): ?>
                            <?php foreach ($this->vrubro as $val): ?>
                            <?php if($val['rubro']==$this->datos[0]['rubro']): ?>
                            <option value="<?php echo $val['rubro']  ?>" selected><?php echo strtoupper($val['rubro'])  ?></option>
                            <?php else:  ?>
                            <option value="<?php echo $val['rubro']  ?>"><?php echo strtoupper($val['rubro'])  ?></option>
                            <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </select> 
					</div>
					<div class="form-group col-md-2">
						<label>*Ciclo :</label>
						<select name="ciclo" id="ciclo" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->vciclo) && count($this->vciclo)): ?>
                            <?php foreach ($this->vciclo as $val): ?>
                            <?php if($val['ciclo']==$this->datos[0]['ciclo']): ?>
                            <option value="<?php echo $val['ciclo']  ?>" selected><?php echo strtoupper($val['ciclo'])  ?></option>
                            <?php else:  ?>
                            <option value="<?php echo $val['ciclo']  ?>"><?php echo strtoupper($val['ciclo'])  ?></option>
                            <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </select>  
					</div>
                    <div class="form-group col-md-2">
						<label>*Moneda :</label>
						<select name="moneda" id="moneda" class="form-control" >
                            <option value="0">-Seleccione-</option>
                            <?php if(isset($this->vmoneda) && count($this->vmoneda)): ?>
                            <?php foreach ($this->vmoneda as $val): ?>
                            <?php if($val['moneda']==$this->datos[0]['moneda']): ?>
                            <option value="<?php echo $val['moneda']  ?>" selected><?php echo strtoupper($val['moneda'])  ?></option>
                            <?php else:  ?>
                            <option value="<?php echo $val['moneda']  ?>"><?php echo strtoupper($val['moneda'])  ?></option>
                            <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                         
                        </select>  
					</div>
                    <div class="form-group col-md-2">
						<label>*Tasa Interes:</label>
						<input type="number"   class="form-control "  name="tasaInteres" id="tasaInteres" value="<?php echo (!empty($this->datos[0]['tasaInteres']))?$this->datos[0]['tasaInteres']:"" ?>"  />
					</div>
					<div class="form-group col-md-2">
						<label>*HA Minimas:</label>
						<input type="number"   class="form-control "  name="haMin" id="haMin" value="<?php echo (!empty($this->datos[0]['hectMin']))?$this->datos[0]['hectMin']:"" ?>"  />
					</div>
                    <div class="form-group col-md-2">
						<label>*HA Maximas:</label>
						<input type="number"   class="form-control "  name="haMax" id="haMax" value="<?php echo (!empty($this->datos[0]['hectMax']))?$this->datos[0]['hectMax']:"" ?>" />
					</div>
					<div class="form-group col-md-2">
						<label>*HA Captadas:</label>
						<input type="number"   class="form-control "  name="haCapt" id="haCapt" value="<?php echo (!empty($this->datos[0]['hectCaptadas']))?$this->datos[0]['hectCaptadas']:"" ?>" readonly="true" />
					</div>
                    <div class="form-group col-md-2">
						<label>*HA Aprobadas:</label>
						<input type="number"   class="form-control "  name="haAprob" id="haAprob"  value="<?php echo (!empty($this->datos[0]['hectAprobadas']))?$this->datos[0]['hectAprobadas']:"" ?>" readonly="true" />
					</div>
                    <div class="form-group col-md-2">
						<label>*HA Financiadas:</label>
						<input type="number"   class="form-control "  name="haFinanc" id="haFinanc"  value="<?php echo (!empty($this->datos[0]['hectFinanciad']))?$this->datos[0]['hectFinanciad']:"" ?>" readonly="true" />
					</div>
                    <div class="form-group col-md-2">
						<label>*Estado:</label>
						<select name="estado" id="estado" class="form-control" > 
                            <option value="0">-Seleccione-</option>
                            
                            <option value="ACTIVO" <?php echo ($this->datos['0']['estado']=='ACTIVO')?'selected':"" ?> >ACTIVO</option>
                            
                            <option value="INACTIVO" <?php echo ($this->datos['0']['estado']=='INACTIVO')?'selected':"" ?> >INACTIVO</option>
                           
                        </select> 
					</div>
                    <div class="form-group col-md-2">
						<label>*Precio de Liquidacion:</label>
						<input type="number"   class="form-control text-right"  name="precioLiquidacion" id="precioprecioLiquidacion"  value="<?php echo (!empty($this->datos[0]['produccion_costoKg']))?$this->datos[0]['produccion_costoKg']:"" ?>" />
					</div>
                    <div class="form-group col-md-2">
						<label>*Cto. Asistencia Técnica x Ha. :</label>
						<input type="number"  class="form-control text-right"  name="ctoAsistTec" id="ctoAsistTec"  value="<?php echo (!empty($this->datos[0]['mtoAsisTecHa']))?$this->datos[0]['mtoAsisTecHa']:"" ?>" />
					</div>
                    <div class="form-group col-md-2">
						<label>*Rendimiento Estimado x Ha. :</label>
						<input type="number"  class="form-control text-right"  name="rendimientoEstimado" id="rendimientoEstimado"  value="<?php echo (!empty($this->datos[0]['rendimiento_rendEstimHa']))?$this->datos[0]['rendimiento_rendEstimHa']:"0" ?>" />
					</div>
                    <div class="form-group col-md-2">
						<label>*Rendimiento Real x Ha. :</label>
						<input type="number"  class="form-control text-right"  name="rendimientoReal" id="rendimientoReal"  value="0.00" disabled />
					</div>
                    <div class="form-group col-md-2">
						<label>*Produccion Total Mto. :</label>
						<input type="number"  class="form-control text-right"  name="prodTotalMto" id="prodTotalMto"  value="0.00" disabled />
					</div>
                    <div class="form-group col-md-2">
						<label>*Produccion Total Kg. :</label>
						<input type="number"  class="form-control text-right"  name="prodTotalKg" id="prodTotalKg"  value="0.00" disabled />
					</div>

			</div>
            </br>
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-prep-tab" data-toggle="pill" href="#custom-tabs-four-prep" role="tab" aria-controls="custom-tabs-four-prep" aria-selected="true">Fase de Preparacion</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-siemb-tab" data-toggle="pill" href="#custom-tabs-four-siemb" role="tab" aria-controls="custom-tabs-four-siemb" aria-selected="false">Fase de Siembra</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-mant-tab" data-toggle="pill" href="#custom-tabs-four-mant" role="tab" aria-controls="custom-tabs-four-mant" aria-selected="false">Fase de Mantenimiento</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-cosec-tab" data-toggle="pill" href="#custom-tabs-four-cosec" role="tab" aria-controls="custom-tabs-four-cosec" aria-selected="false">Fase Cosecha</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-prep" role="tabpanel" aria-labelledby="custom-tabs-four-prep-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para la fase de preparacion </span></div>
                                <div class="card-body">
                                    <div class="row">  
                                        <div class="form-group col-md-2">
                                            <label>*Visitas Programadas</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="prepVisitas" id="prepVisitas" placeholder="Ej.:10" value="<?php echo (!empty($this->datos[0]['prep_visitas']))?$this->datos[0]['prep_visitas']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Duracion de Fase(Dias)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="prepDias" id="prepDias" placeholder="Ej.: 10" value="<?php echo (!empty($this->datos[0]['prep_dias']))?$this->datos[0]['prep_dias']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Lt.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="prepCombustible" id="prepCombustible" value="<?php echo (!empty($this->datos[0]['prep_lt_combustible']))?$this->datos[0]['prep_lt_combustible']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(MTO.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="prepCombustibleMto" id="prepCombustibleMto" value="<?php echo (!empty($this->datos[0]['prep_mto_combustible']))?$this->datos[0]['prep_mto_combustible']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Otros Gastos x Ha.</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="prepOtros" id="prepOtros" value="<?php echo (!empty($this->datos[0]['prep_mto_otros']))?$this->datos[0]['prep_mto_otros']:"" ?>"  />
                                        </div>   
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-siemb" role="tabpanel" aria-labelledby="custom-tabs-four-siemb-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para la fase de siembra</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-2">
                                            <label>*Visitas Programadas</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="siembVisitas" id="siembVisitas" placeholder="Ej.:10" value="<?php echo (!empty($this->datos[0]['siembra_visitas']))?$this->datos[0]['siembra_visitas']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Duracion de Fase(Dias)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembDias" id="siembDias" placeholder="Ej.: 10"  value="<?php echo (!empty($this->datos[0]['siembra_dias']))?$this->datos[0]['siembra_dias']:"" ?>" />
                                        </div>
                                        
                                        <div class="form-group col-md-2">
                                            <label>*Semillas X Ha(Mto.).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="siembSemillasMto" id="siembSemillasMto" value="<?php echo (!empty($this->datos[0]['siembra_mto_semillas']))?$this->datos[0]['siembra_mto_semillas']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Semillas X Ha(Kg).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="siembSemillas" id="siembSemillas"  value="<?php echo (!empty($this->datos[0]['siembra_kg_semillas']))?$this->datos[0]['siembra_kg_semillas']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Lt.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembCombustible" id="siembCombustible" value="<?php echo (!empty($this->datos[0]['siembra_lt_combustible']))?$this->datos[0]['siembra_lt_combustible']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Mto.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembCombustibleMto" id="siembCombustibleMto"  value="<?php echo (!empty($this->datos[0]['siembra_mto_combustible']))?$this->datos[0]['siembra_mto_combustible']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Otros Gastos x Ha.</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembOtros" id="siembOtros" value="<?php echo (!empty($this->datos[0]['siembra_mto_otros']))?$this->datos[0]['siembra_mto_otros']:"" ?>"  />
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                        <div class="tab-pane fade " id="custom-tabs-four-mant" role="tabpanel" aria-labelledby="custom-tabs-four-mant-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para la fase de mantenimiento.</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-2">
                                            <label>*Visitas Programadas</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="mantVisitas" id="mantVisitas" placeholder="Ej.:10"  value="<?php echo (!empty($this->datos[0]['mantenimiento_visitas']))?$this->datos[0]['mantenimiento_visitas']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Duracion de Fase(Dias)</label> 
                                            <input type="number"  required class="form-control form-control-sm"  name="mantDias" id="mantDias" placeholder="Ej.: 10" value="<?php echo (!empty($this->datos[0]['mantenimiento_dias']))?$this->datos[0]['mantenimiento_dias']:"" ?>"/>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Lt.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="mantCombustible" id="mantCombustible"  value="<?php echo (!empty($this->datos[0]['mantenimiento_lt_combustible']))?$this->datos[0]['mantenimiento_lt_combustible']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Mto.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="mantCombustibleMto" id="mantCombustibleMto"  value="<?php echo (!empty($this->datos[0]['mantenimiento_mto_combustible']))?$this->datos[0]['mantenimiento_mto_combustible']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Fertilizante X Ha(Kg).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="mantFertilizante" id="mantFertilizante" value="<?php echo (!empty($this->datos[0]['mantenimiento_kg_fertilizante']))?$this->datos[0]['mantenimiento_kg_fertilizante']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Fertilizante X Ha(Mto.).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="mantFertilizanteMto" id="mantFertilizanteMto" value="<?php echo (!empty($this->datos[0]['mantenimiento_mto_fertilizante']))?$this->datos[0]['mantenimiento_mto_fertilizante']:"" ?>"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Monto Agroquimicos X Ha.</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="mantMontoagroq" id="mantMontoagroq"  value="<?php echo (!empty($this->datos[0]['mantenimiento_mto_agroquimicos']))?$this->datos[0]['mantenimiento_mto_agroquimicos']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Monto Labores X Ha.</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="mantLabores" id="mantLabores"  value="<?php echo (!empty($this->datos[0]['mantenimiento_mto_labores']))?$this->datos[0]['mantenimiento_mto_labores']:"" ?>" />
                                        </div>
                                        
                                        <div class="form-group col-md-2">
                                            <label>*Otros Gastos x Ha.</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="mantOtros" id="mantOtros"  value="<?php echo (!empty($this->datos[0]['mantenimiento_mto_otros']))?$this->datos[0]['mantenimiento_mto_otros']:"" ?>" />
                                        </div>   
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                        <div class="tab-pane fade " id="custom-tabs-four-cosec" role="tabpanel" aria-labelledby="custom-tabs-four-cosec-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para contactar al productor</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-2">
                                            <label>*Visitas Programadas</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="cosecVisitas" id="cosecVisitas" placeholder="Ej.:10" value="<?php echo (!empty($this->datos[0]['cosecha_visitas']))?$this->datos[0]['cosecha_visitas']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Duracion de Fase(Dias)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="cosecDias" id="cosecDias" placeholder="Ej.: 10" value="<?php echo (!empty($this->datos[0]['cosecha_dias']))?$this->datos[0]['cosecha_dias']:"" ?>"/>
                                        </div>
                                        
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Mto.)</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="cosecCombustibleMto" id="cosecCombustibleMto"  value="<?php echo (!empty($this->datos[0]['cosecha_mto_combustible']))?$this->datos[0]['cosecha_mto_combustible']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Lt.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="cosecCombustible" id="cosecCombustible"  value="<?php echo (!empty($this->datos[0]['cosecha_lt_combustible']))?$this->datos[0]['cosecha_lt_combustible']:"" ?>" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Transporte X Ha(Mto.).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="cosecTransporte" id="cosecTransporte"  value="<?php echo (!empty($this->datos[0]['cosecha_mto_transporte']))?$this->datos[0]['cosecha_mto_transporte']:"" ?>" />
                                        </div>
                                        
                                        <div class="form-group col-md-2">
                                            <label>*Otros Gastos x Ha.</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="cosecOtros" id="cosecOtros"  value="<?php echo (!empty($this->datos[0]['cosecha_mto_otros']))?$this->datos[0]['cosecha_mto_otros']:"" ?>" />
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>                            

                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>financiamiento/programa/index/"><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
