<div class="row">
    <div class="col-12">
        <form name="form_programa_eliminar" method="post" id="form_programa_eliminar" action="<?php echo BASE_URL ?>financiamiento/programa/eliminar/">
        <input name="eliminar" id="eliminar" type="hidden" value="1" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))? $this->datos[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Eliminacion de Programa de Financiamiento</h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta seguro de eliminar el registro de Programa de Financiamiento:</h3>
                        <dl class="row">
                            <dt class="col-sm-4">Fecha de Inicio :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['fechaInicio']))?$this->datos[0]['fechaInicio']:"" ?></dd>
                            <dt class="col-sm-4">Fecha Finalizacion :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['fechaFinal']))?$this->datos[0]['fechaFinal']:"" ?></dd>
                            <dt class="col-sm-4">Rubro  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['rubro']))?$this->datos[0]['rubro']:"" ?></dd>
                            <dt class="col-sm-4">Ciclo  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['ciclo']))?$this->datos[0]['ciclo']:"" ?></dd>
                            <dt class="col-sm-4">Hectareas Minimas :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['hectMin']))?$this->datos[0]['hectMin']:"" ?></dd>
                            <dt class="col-sm-4">Hectareas Maximas :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->datos[0]['hectMax']))?$this->datos[0]['hectMax']:"" ?></dd>
                        </dl>
                </div>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>financiamiento/programa/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
