<div class="row">
    <div class="col-12">
        <div class="card">
			
			    <div class="card-header">
				    <a  href="<?php echo BASE_URL ?>financiamiento/programa/agregar/" title="Presione aquí para AGREGAR un nuevo Programa de Financiamiento"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
			    </div>
 
          <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Rubro</th>
                        <th>Ciclo</th>
                        <th>Inicio</th>
                        <th>Final</th>
                        <th>Prod. Kg</th>
                        <th>Rend.x Ha</th>
                        <th>Estado</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['nombre'] ?></td>
                            <td><?php echo $val['ciclo'] ?></td>
                            <td><?php echo $val['fechaInicio'] ?></td>
                            <td><?php echo $val['fechaFinal'] ?></td>
                            <td class="text-right"><?php echo number_format($val['produccion_prodTotalKg'],2,".",",") ?></td>
                            <td class="text-right"><?php echo number_format($val['rendimiento_rendRealHa'],2,".",",") ?></td>
                            <td><?php echo $val['estado'] ?></td>
                            
                            <td>
                                <?php if($val['estado']=='ACTIVO'): ?>
                                <a href="<?php echo BASE_URL ?>financiamiento/programa/editar/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button></a>
                                <?php else: ?>    
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro" disabled> <i class="fa fa-edit"></i></button>
                                <?php endif; ?>     
                            </td>
                            <td>
                               <?php if($val['estado']=='ACTIVO'): ?>
                                <a href="<?php echo BASE_URL ?>financiamiento/programa/eliminar/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para eliminar registro"> <i class="fa fa-trash"></i></button></a>
                                <?php else: ?>
                                    <button class="btn btn-default btn-sm" title="Presione aquí para eliminar registro" disabled> <i class="fa fa-trash"></i></button>
                                <?php endif; ?> 
                            </td>       
                            <td>    
                            <?php if($val['estado']=='ACTIVO'): ?>
                                <a href="<?php echo BASE_URL ?>financiamiento/programa/operaciones/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione para realizar operaciones adicionales"> <i class="fa-solid fa-gear"></i></button> </a>   
                             <?php else: ?>
                                <button class="btn btn-default btn-sm" title="Presione para realizar operaciones adicionales" disabled> <i class="fa-solid fa-gear"></i></button>                                         
                            <?php endif; ?>
                            </td>
                            <td>    
                            <?php if($val['estado']=='ACTIVO'): ?>
                                <a href="" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para enviar correo"> <i class="fa fa-envelope"></i></button> </a>   
                             <?php else: ?>
                                <button class="btn btn-default btn-sm" title="Presione aquí para enviar correo" disabled> <i class="fa fa-envelope"></i></button>                                         
                            <?php endif; ?>
                            </td>    
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                <p>
                        <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            
          </div>

        </div>
    </div>
        
</div>
