<div class="row">
<div class="col-lg-12">
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Operaciones Globales para el Programa de Financiamiento</span>
		</div>
		<div class="card-body">

            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-prep-tab" data-toggle="pill" href="#custom-tabs-four-prep" role="tab" aria-controls="custom-tabs-four-prep" aria-selected="true">Gestion Tecnico Administrativa</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-siemb-tab" data-toggle="pill" href="#custom-tabs-four-siemb" role="tab" aria-controls="custom-tabs-four-siemb" aria-selected="false"></a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-mant-tab" data-toggle="pill" href="#custom-tabs-four-mant" role="tab" aria-controls="custom-tabs-four-mant" aria-selected="false">Cierre de Programa</a>
                        </li>  
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-prep" role="tabpanel" aria-labelledby="custom-tabs-four-prep-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue información para la fase de preparación </span></div>
                                <div class="card-body">
                                    <div class="row">  
                                                
                                        <div class="col-md-3" bis_skin_checked="1">

                                            <div class="card card-secondary card-outline" bis_skin_checked="1">
                                                <div class="card-body box-profile" bis_skin_checked="1">
                                                    <div class="row">
                                                        <form name="form_programa_cuotas" method="post" id="form_programa_cuotas" action="<?php echo BASE_URL ?>financiamiento/programa/operaciones/"  >
                                                        <input name="guardar" id="guardar" type="hidden" value="3" />
                                                        <div class="form-group col-md-12">
                                                            <label>*Prograsma de Financiamiento :</label>
                                                            <select name="programa" id="programa" class="form-control" >
                                                                <option value="0">-Seleccione-</option>
                                                                <?php foreach ($this->lista as $val): ?>
                                                                <?php if($val['id']==$this->pfActual[0]['id']): ?>
                                                                <option value="<?php echo $val['id']  ?>" selected><?php echo strtoupper($val['nombre'])  ?></option>
                                                                <?php else:  ?>
                                                                <option value="<?php echo $val['id']  ?>"><?php echo strtoupper($val['nombre'])  ?></option>
                                                                <?php endif; ?>
                                                                <?php endforeach; ?>
                                                                
                                                            </select>   
                                                        </div>

                                                            <div class="form-group col-md-12">
                                                            <label>*Estado:</label>
                                                            <input type="text"  class="form-control"  name="estado" id="estado"  value="<?php if(isset($this->pfActual[0]['estado'])) echo $this->pfActual[0]['estado'] ?>" />
                                                        </div>           
                                                        <div class="form-group col-md-12">
                                                            <button type="button" id="agregar-cuota" name="agregar-cuota" class="btn btn-default" >Generar Cuotas Tecnico Administrativa</button>

                                                        </div>
                                                        </form>            
                                                    </div>
                                                </div>

                                            </div>
                                            
                                        </div>
                                        <div class="col-md-9">
                                            <div class="card card-primary card-outline card-outline-tabs">
                                                
                                                <div class="card-body">

                                                    <table class="table table-bordered table-hover" id="tabla-cuotas">
                                                        <thead>
                                                            <tr class="bg-secondary color-palette">
                                                            <th>Cxc</th>
                                                            <th width="110">Fecha</th>
                                                            <th>Productor</th>
                                                            <th>Concepto</th>
                                                            <th>Monto</th>
                                                            <th>Saldo</th>
                                                            <th>Estado</th>
                                                            <th>Credito</th>
                                                            <th>Genera Interes %</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php if(count($this->datos)>0):  ?>
                                                                <?php $i = 1; ?>    
                                                                <?php foreach($this->datos as $cre): ?>
                                                            
                                                                <tr data-widget="expandable-table" class="tcred"  aria-expanded="false" id="<?php echo $i ?>" data-id="<?php echo $cre['id'] ?>">
                                                                <td><?php echo $cre['id'] ?></td>
                                                                <td><?php echo $cre['emision'] ?></td>
                                                                <td><?php echo strtoupper($cre['RazonSocial']) ?></td>
                                                                <td><?php echo $cre['concepto'] ?></td>
                                                                <td><?php echo $cre['monto'] ?></td>
                                                                <td><?php echo $cre['saldo'] ?></td>
                                                                <td><?php echo $cre['estado'] ?></td>
                                                                <td><?php echo $cre['idCredito'] ?></td>
                                                                <td><?php echo $cre['genInteres'] ?></td>
                                                                
                                                                <?php $i ++; ?>
                                                                <?php endforeach ?>
                                                            <?php endif ?>    
                                                                                        
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>             
                                    </div>   
                                </div>
                            </div>    

                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-siemb" role="tabpanel" aria-labelledby="custom-tabs-four-siemb-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue información para la fase de siembra</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-2">
                                            <label>*Visitas Programadas</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="siembVisitas" id="siembVisitas" placeholder="Ej.:10"  />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Duración de Fase(Días)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembDias" id="siembDias" placeholder="Ej.: 10"/>
                                        </div>
                                        
                                        <div class="form-group col-md-2">
                                            <label>*Semillas X Ha(Mto.).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="siembSemillasMto" id="siembSemillasMto"   />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Semillas X Ha(Kg).</label>
                                            <input type="number"  required  class="form-control form-control-sm"  name="siembSemillasKg" id="siembSemillasKg"   />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Lt.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembCombustible" id="siembCombustible"   />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Combustible X Ha(Mto.)</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembCombustibleMto" id="siembCombustibleMto"   />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Otros Gastos x Ha.</label>
                                            <input type="number"  required class="form-control form-control-sm"  name="siembOtros" id="siembOtros"   />
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        
                    </div>
                </div>
                    
            </div>

         </div>
			
	</div>
       
</div>

</div>
