<div class="row">
<div class="col-lg-12">
	<form name="form_cliente_agregar" method="post" id="form_cliente_agregar" action="<?php echo BASE_URL ?>productores/productor/agregar/"  >
	<input name="guardar" id="guardar" type="hidden" value="1" />
	
	<div class="card card-secondary card-outline">
		<div class="card-header">
            <span class="card-title">Nuevo Productor</span>
		</div>
		<div class="card-body">
			<div class="row">
                <div class="form-group col-md-3">
                    <label>*Tipo Persona:</label>
                    <select name="tipo" id="tipo" class="form-control">
                        <option value="0">-Seleccione-</option>
                        <option value="J">Juridico</option>
                        <option value="N">Natural</option>
                    </select> 
                </div>
                <div class="form-group col-md-3">
                    <label>*Nro Fiscal :</label>
                    <input name="idFiscal"  maxlength="100" type="text" class="form-control valid_productor" id="idFiscal"  />  
                </div>
                <div class="form-group col-md-6">
                    <label>*Razon Social:</label>
                    <input type="text"  maxlength="100" class="form-control alfa_desc"  name="razon_social" id="razon_social" readonly="true"  />
                </div>
                <div class="form-group col-md-12">
						<label>*Comentarios:</label>
						<input type="text"  maxlength="100" class="form-control alfa_desc"  name="comentario" id="comentario" value=""  />
					</div>
					
			</div>
            </br>
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true"><i class="fa fa-map-o"></i>  Direccion del Productor</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false"><i class="fa  fa-book"></i>  Contactos del Productor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-info" role="tab" aria-controls="custom-tabs-four-info" aria-selected="false"><i class="fa  fa-book"></i> Otra Información</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue direccion para del productor</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-3">
                                            <label>*Estado:</label>
                                            <select name="estado" id="estado" class="form-control form-control-sm" readonly="true">
                                                <option value="">-Seleccione-</option>
                                                <?php if(isset($this->estado) && count($this->estado)): ?>
                                                <?php foreach ($this->estado as $val): ?>
                                                <?php if($val['estatus_estado']==1): ?>
                                                <option value="<?php echo $val['id_estado']  ?>"><?php echo strtoupper($val['descripcion_estado'])  ?></option>
                                                <?php endif; ?>
                                                <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>  
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Municipio:</label>
                                            <select name="municipio" id="municipio" class="form-control form-control-sm" readonly="true">
                                                <option value="">-Seleccione-</option>

                                            </select>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Parroquia:</label>
                                            <select name="parroquia" id="parroquia" class="form-control form-control-sm" readonly="true">
                                                <option value="">-Seleccione-</option>

                                            </select>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Sector:</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="sector" id="sector" placeholder="" readonly="true" />
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Direccion</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm alfa_dir"  name="direccion" id="direccion" placeholder="" readonly="true" />
                                        </div> 
                                        <div class="form-group col-md-2">
                                            <label>*Av.</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm alfa_dir"  name="av" id="av" placeholder="" readonly="true" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Calle</label>
                                            <input type="text"  required maxlength="100" class="form-control form-control-sm alfa_dir"   name="calle" id="calle" placeholder="" readonly="true" />
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Tipo de Vivienda:</label>
                                            <select name="tipo_vivienda" id="tipo_vivienda" class="form-control form-control-sm" readonly="true">
                                                <option value="">-Seleccione-</option>
                                                <option value="CASA">-CASA-</option>
                                                <option value="APARTAMENTO">-APARTAMENTO-</option>    
                                            </select>
                                        </div>
                                        <div class="form-group col-md-1">
                                            <label>*Nro.</label>
                                            <input type="number"  required maxlength="100" class="form-control form-control-sm num_entero"  name="nro" id="nro" placeholder="Ej.: 12-50" readonly="true" />
                                        </div>
                                        <div class="form-group col-md-1">
                                            <label>*Codigo Postal.</label>
                                            <input type="number"  required maxlength="100" class="form-control form-control-sm num_entero"  name="codigo_postal" id="codigo_postal" placeholder="Ej.: 3301"  readonly="true" />
                                        </div>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para contactar al productor</span></div>
                                <div class="card-body">
                                    <div class="row">
                                        
                                        <div class="form-group col-md-2">
                                            <label>*Telefono personal 1:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                                </div>
                                                <input type="text" name="tlf_prod1" class="form-control form-control-sm num_tel"  id="tlf_prod1"  readonly="true"  placeholder="___ ________">
                                            </div>
                                            <!-- /.input group -->
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Telefono personal 2:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                                </div>
                                                <input type="text" name="tlf_prod2" class="form-control form-control-sm num_tel"  id="tlf_prod2"  readonly="true"  placeholder="___ ________">
                                            </div>
                                            <!-- /.input group -->
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label>*Telefono Oficina:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                                </div>
                                                <input type="text" name="tlf_oficina" id="tlf_oficina" class="form-control form-control-sm num_tel"    readonly="true"  placeholder="___ ________">
                                            </div>
                                            <!-- /.input group -->
                                        </div>
                                        
                                        <div class="form-group col-md-3">
                                            <label>Whatsapp Personal:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-commenting"></i></span>
                                                </div>
                                                <input type="text" name="tlf_wsp" id="tlf_wsp" class="form-control form-control-sm num_tel"    readonly="true"  placeholder="___ ________">
                                            </div>
                                            <!-- /.input group -->
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>Whatsapp Oficina:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-commenting"></i></span>
                                                </div>
                                                <input type="text" name="tlf_wso" id="tlf_wso" class="form-control form-control-sm num_tel"    readonly="true" placeholder="___ ________">
                                            </div>
                                            <!-- /.input group -->
                                        </div>
                                       
                                        <div class="form-group col-md-4">
                                            <label>Correo Personal 1:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                                </div>
                                                <input type="email" name="correo_prod1" id="correo_prod1"  class="form-control form-control-sm alfa_correo"    readonly="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                                            </div>
                                            <!-- /.input group -->
                                        </div>        
                                        
                                        <div class="form-group col-md-4">
                                            <label>Correo Personal 2:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                                </div>
                                                <input type="email" name="correo_prod2" id="correo_prod2"  class="form-control form-control-sm alfa_correo"    readonly="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                                            </div>
                                            <!-- /.input group -->
                                        </div>

                                        <div class="form-group col-md-4">
                                            <label>Correo Empresa:</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                                </div>
                                                <input type="email" name="correo_empresa" id="correo_empresa"  class="form-control form-control-sm alfa_correo"    readonly="true"  placeholder="Ej.: micorreo@hotmail.com"/>
                                            </div>
                                            <!-- /.input group -->
                                        </div>
                                        
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-info" role="tabpanel" aria-labelledby="custom-tabs-four-contact-info">
                        <div class="card">
                            <div class="card-header"><span class="card-title">Agregue informacion </span></div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-md-4">
                                        <label>*RUNOPPA:</label>
                                        <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="runoppa" id="runoppa" placeholder=""  value="<?php echo (!empty($this->datos[0]['runoppa']))? $this->datos[0]['runoppa']:''  ?>" />
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label>*Usuario (SIGESAI):</label>
                                        <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="usuario_sigesai" id="usuario_sigesai" placeholder=""  value="<?php echo (!empty($this->datos[0]['runoppa']))? $this->datos[0]['runoppa']:''  ?>" />
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label>*Clave (SIGESAI):</label>
                                        <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="clave_sigesai" id="clave_sigesai" placeholder=""  value="<?php echo (!empty($this->datos[0]['runoppa']))? $this->datos[0]['runoppa']:''  ?>" />
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label>*Usuario (SUNAGRO):</label>
                                        <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="usuario_sunagro" id="usuario_sunagro" placeholder=""  value="<?php echo (!empty($this->datos[0]['runoppa']))? $this->datos[0]['runoppa']:''  ?>" />
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label>*Clave (SUNAGRO):</label>
                                        <input type="text"  required maxlength="100" class="form-control form-control-sm"  name="clave_sunagro" id="clave_sunagro" placeholder=""  value="<?php echo (!empty($this->datos[0]['runoppa']))? $this->datos[0]['runoppa']:''  ?>" />
                                    </div>
                                    <hr>

                                    <div class="card" id="">
                                        <table class="table-bordered" >
                                            <thead>
                                                <tr class="bg-secondary color-palette">
                                                    <th style="width: 500px;">Titular</th>
                                                    <th style="width: 350px;">Nro de Cuenta</th>
                                                    <th style="width: 300px;">Banco</th>
                                                    <th width="30"></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php for($i=0;$i < 3;$i++): ?>
                                                 <tr>   
                                                    <td><input name="titular[]" id="titular<?php echo $i+1 ?>" class="form-control " type="text" /></td>
                                                    <td><input name="cuenta[]" id="cuenta<?php echo $i+1 ?>" class="form-control " type="text" /></td>
                                                    <td><select name="banco[]" id="banco<?php echo $i+1 ?>" class="form-control" ><option value="">-Seleccione-</option>
                                                    <?php foreach($this->bancos as $bnc): ?>    
                                                        <option ><?php echo $bnc['Nombre'] ?></option>
                                                    <?php endforeach ?>        
                                                </select></td>
                                                    <td><button class="btn btn-danger"><i class="fa-regular fa-trash-can"></i></button></td>
                                                 </tr>   
                                                <?php endfor; ?>    
                                            </tbody>
                                        </table>
                                    </div>


                                </div> 
                            </div>
                        </div>                       
                    
                        </div>
                        
                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app " id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>productores/productor/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
