<div class="row" bis_skin_checked="1">    
    <div class="col-md-3" bis_skin_checked="1">

        <div class="card card-secondary card-outline" bis_skin_checked="1">
            <div class="card-body box-profile" bis_skin_checked="1">
                <div class="text-center" bis_skin_checked="1">
                    
                </div>
                <h3 class="profile-username text-center"><?php echo $this->productor[0]['razonSocial'] ?></h3>
                <p class="text-muted text-center">Productor</p>
                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b>Creditos aprobados</b> <button class="btn btn-secondary imprimir-despacho float-right" data-toggle="modal" data-target="#modal-xl-desp" value="1" > 1  <i class="fa-regular fa-file"></i></button>
                    </li>
                    <li class="list-group-item">
                        <b>Creditos Rechazados</b><button class="btn btn-secondary imprimir-recepcion float-right" data-toggle="modal" data-target="#modal-xl-desp" value="1" > 1  <i class="fa-regular fa-file"></i></button>
                    </li>
                    
                </ul>
                
                <h4 class="h4">Estatus del Productor  </h4>
                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b><?php if(isset($this->productor[0]['statusProductor'])) echo $this->productor[0]['statusProductor'] ?></b> <a class="float-right"></a>
                    </li>
                    <li class="list-group-item">
                        <b>Inspecciones Técnicas</b> <a class="float-right"></a>
                    </li>
                    
                </ul>

                <a href="#" class="btn btn-secondary" data-toggle="modal" data-target="#modal-lg-ext" title="Agregar solicitud de extencion de credito"><i class="fa-solid fa-layer-group"></i></a>
            </div>

        </div>   
        <div class="card card-secondary" bis_skin_checked="1">
        <div class="card-header" bis_skin_checked="1">
            <h3 class="card-title"><i class="fa  fa-sitemap"></i> Informacion de contacto</h3>
        </div>

        <div class="card-body" bis_skin_checked="1">
                 <strong><i class="fas fa-map-marker-alt mr-1"></i> Locación</strong>
            <p class="text-muted"><?php if(isset($this->productor[0]['direccion']))echo $this->productor[0]['direccion'].' - '.$this->productor[0]['sector'] ?></p>
            <hr>
            <strong><i class="fa-solid fa-phone-volume"></i> Telefonos:</strong>
            <p class="text-muted"><?php if(isset($this->productor[0]['tlfPersonal1'])) echo $this->productor[0]['tlfPersonal1'] .' - '.$this->productor[0]['tlfPersonal2'] ?></p>
            <hr>
            <strong><i class="fa-solid fa-envelope"></i> Correos:</strong>
            <p class="text-muted"><?php if(isset($this->Productor[0]['correoPersonal1'])) echo $this->finca[0]['correoPersonal1'] .' - '.$this->finca[0]['correoPersonal2'] ?></p>
            <hr>
            
            <strong><i class="far fa-file-alt mr-1"></i> Comentario </strong >
            <p class="text-muted"><?php if(isset($this->productor[0]['comentario'])) echo $this->productor[0]['comentario'] ?></p>
        </div>

</div>
        

</div>


    <div class="col-md-9">
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true"><i class="fa fa-map-o"></i> Despachos de Creditos </a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false"><i class="fa  fa-book"></i>Mov. de Almacen del Productor </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-info" role="tab" aria-controls="custom-tabs-four-info" aria-selected="false"><i class="fa  fa-book"></i> Estadistica del Productor </a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title"></span></div>
                                <div class="card-body">
                                    <div class="row">
                                    <table class="table table-bordered table-hover">
                                        <thead>
                                            <tr class="bg-secondary color-palette">
                                            <th>Crédito</th>
                                            <th width="110">Fecha</th>
                                            <th>Programa Financ.</th>
                                            <th>Estado</th>
                                            <th>Ha. Aprob</th>
                                            <th>Ha. Cosech</th>
                                            <th>Saldo Actual</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if(count($this->creditos)>0):  ?>
                                                <?php $i = 1; ?>    
                                                <?php foreach($this->creditos as $cre): ?>
                                               
                                                <tr data-widget="expandable-table" class="tcred"  aria-expanded="false" id="<?php echo $i ?>" data-id="<?php echo $cre['id'] ?>">
                                                <td><?php echo $cre['id'] ?></td>
                                                <td><?php echo $cre['creditos_fechaAprobacion'] ?></td>
                                                <td><?php echo $cre['ProgFinanc'] ?></td>
                                                <td><?php echo $cre['estado'] ?></td>
                                                <td><?php echo $cre['creditos_superficieAprobada'] ?></td>
                                                
                                                <td><?php echo $cre['creditos_superficieCosechada'] ?></td>
                                                <td><?php echo $cre['saldoActual'] ?></td>
                                                </tr>
                                                <tr class="expandable-body d-none">
                                                <td colspan="7">
                                                    <div style="display: none;" id="tabla<?php echo $i ?>">
                                                        
                                                    </div>
                                                </td>
                                                <?php $i ++; ?>
                                                <?php endforeach ?>
                                            <?php endif ?>    
                                                </tr>                        
                                        </tbody>
                                        </table>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header">
                                    <span class="card-title"></span>                
                                    <div class="card-tools">
                                         <button class="btn btn-default imprimir" data-toggle="modal" data-target="#modal-xl-desp" value="<?php echo $this->productor[0]['id'] ?>"><i class="fa-solid fa-print"></i></button>           
                                    </div>               
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                    <table class="table table-bordered table-hover">
                                        <thead>
                                            <tr class="bg-secondary color-palette">
                                            <th>Mov. #</th>
                                            <th width="110">Fecha</th>
                                            <th>Tipo</th>
                                            <th>Almacen</th>
                                            <th>Concepto</th>
                                            <th>Estado</th>
                                           
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if(count($this->movimientos)>0):  ?>
                                                <?php $j = 1; ?>    
                                                <?php foreach($this->movimientos as $mov): ?>
                                                <?php $detalle = json_decode($mov['producto'],true); ?>    
                                                <tr data-widget="expandable-table"class="tmov" aria-expanded="false" id="<?php echo $j ?>" data-id="<?php echo $mov['id'] ?>">
                                                <td><?php echo $mov['id'] ?></td>
                                                <td><?php echo $mov['fechas_fecEmision'] ?></td>
                                                <td><?php echo $mov['tipo'] ?></td>
                                                <td><?php echo $mov['nombreAlmacen'] ?></td>
                                                <td><?php echo $mov['comentario'] ?></td>
                                                
                                                <td><?php echo $mov['estado'] ?></td>
                                                
                                                </tr>
                                                <tr class="expandable-body d-none">
                                                <td colspan="6">
                                                    <div style="display: none;" id="tabla-mov<?php echo $j ?>">
                                                        <table>
                                                            <thead>
                                                                <tr class="bg-olive disabled color-palette">
                                                                <th width="150">Codigo</th>
                                                                <th width="410">Descripcion</th>
                                                                <th width="110">Cantidad</th>
                                                                <th width="110">Precio</th>
                                                                <th width="110">Monto</th>
                                                                </tr>    
                                                            </thead>
                                                            <tbody>
                                                                <?php foreach($detalle as $det): ?>
                                                                <tr>
                                                                    <td><?php echo $det['codigo'] ?></td>
                                                                    <td><?php echo $det['descripcion'] ?></td>
                                                                <?php if(isset($det['cantDevolucion']) && $det['cantDevolucion']>0 ): ?>
                                                                    <td><?php echo $det['cantDevolucion'] ?></td>
                                                                <?php else: ?>    
                                                                    <td><?php echo $det['cantidad'] ?></td>
                                                                <?php endif  ?>    
                                                                    <td><?php echo $det['pvp'] ?></td>
                                                                    <td><?php echo (isset($det['cantDevolucion']) && $det['cantDevolucion']>0)?($det['pvp']*$det['cantDevolucion']):($det['pvp']*$det['cantidad']) ?></td>
                                                                </tr>
                                                                <?php endforeach ?>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </td>
                                                <?php $i ++; ?>
                                                <?php endforeach ?>
                                            <?php endif ?>    
                                                </tr>                        
                                        </tbody>
                                        </table>
                                           
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-info" role="tabpanel" aria-labelledby="custom-tabs-four-contact-info">
                        <div class="card">
                            <div class="card-header"><span class="card-title">Agregue información </span></div>
                            <div class="card-body">
                                <div class="row">
                                    


                                </div> 
                            </div>
                        </div>                       
                    
                        </div>
                        
                    </div>
                </div>

            </div>

            
        </div>   
        
        <div class="row">
           
        </div>

    </div>      
        
</div>



<div class="modal fade" id="modal-xl-desp" bis_skin_checked="1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" bis_skin_checked="1">
        <div class="modal-content" bis_skin_checked="1">
            <div class="modal-header" bis_skin_checked="1">
                <h4 class="modal-title"> <button type="button" class="btn btn-primary" id="imprimir" title="Click para Imprimir" ><i class="fa fa-print"></i></button></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" bis_skin_checked="1">
                <div id="nota" ></div>
            </div>
            <div class="modal-footer justify-content-between" bis_skin_checked="1">
               
                <button type="button" class="btn btn-primary" id="imprimir" title="Click para Imprimir"><i class="fa fa-print"></i></button>
            </div>
        </div>

    </div>

</div>
