<div class="row">
    <div class="col-12">
        <form name="form_productor_eliminar" method="post" id="form_productor_eliminar" action="<?php echo BASE_URL ?>productores/productor/eliminar/">
        <input name="eliminar" id="eliminar" type="hidden" value="1" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))? $this->datos[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Eliminar Productor</h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta se guro de eliminar el registro del Productor:</h3>
                        <pre>
                        <?php print_r($this->datos) ?> 
                        </pre>
                        

                </div>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>productores/productor/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
