<div class="row">
    <div class="col-12">
        <form name="form_compra_eliminar" method="post" id="form_compra_eliminar" action="<?php echo BASE_URL ?>compras/compra/anular/">
        <input name="anular" id="anular" type="hidden" value="3" />
        <input name="id" id="id" type="hidden" value="<?php echo (!empty($this->orden[0]['id']))? $this->orden[0]['id']:''  ?>"/>
        <div class="card">	
			    <div class="card-header">
				    <h4>Anulación de <?php echo ($this->orden[0]['tipo']=='ord-cpra')?'Orden de Compra':'Compras' ?></h4>
			    </div>
          <div class="card-body">
                
          <div class="callout callout-warning">
                <h2 class="headline text-warning">Alerta. </h2>
                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Esta seguro de ! Anular ! el registro de :</h3>
                        

                        <dl class="row">
                            <dt class="col-sm-4">Correlativo  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->orden[0]['referencia']))?$this->orden[0]['referencia']:"" ?></dd>
                            <dt class="col-sm-4">Fecha de Emision :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->orden[0]['emision']))?$this->orden[0]['emision']:"" ?></dd>
                            
                            <dt class="col-sm-4">Proveedor:</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->orden[0]['razonSocial']))?$this->orden[0]['razonSocial']:"" ?></dd>
                            <dt class="col-sm-4">Direccion :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->orden[0]['domicilioFiscal']))?$this->orden[0]['domicilioFiscal']:"" ?></dd>
                            <dt class="col-sm-4">Monto  :</dt>
                            <dd class="col-sm-8"><?php echo (isset($this->orden[0]['montoTotal']))?$this->orden[0]['montoTotal']:"" ?></dd>
                                   
                        </dl>
                        

                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>*Fecha de Anulación:</label>
                        <input type="date" class="form-control"  name="fechaAnulacion" id="fechaAnulacion"  value="<?php echo date('Y-m-d') ?>" />
                    </div>
                    <div class="form-group col-md-6">
                        <label>*Comentario:</label>
                        <input type="text" class="form-control"  name="comentario" id="comentario"   />
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-xs btn-app btn btn-app bg-success " id="eliminar"><i class="fa  fa-arrow-right"></i>Continuar</button>
			    <a href="<?php echo BASE_URL ?>compras/compra/index/"><button type="button" class="btn btn-xs btn-app btn btn-app bg-warning" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
            </div>

          </div>

        </div>
        </form>
    </div>
        
</div>
