<div class="row">
    <div class="col-12">
        <div class="card">
			
			    <div class="card-header">
				  <p><i class="fa-solid fa-triangle-exclamation"></i> Para agregar una compra u orden de compra dirijase al apartado <a  href="<?php echo BASE_URL ?>compras/proveedor/index/" > Proveedores</a></p>  
			    </div>
 
          <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        
                    </tr>
                        <th width="120">Fecha</th>
                        <th width="100">Tipo</th>
                        <th width="120">Correlativo</th>
                        <th>Proveedor</th>
                        <th width="120">Monto</th>
                        <th width="100">Estado</th>
                        <th>Comentario</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->compras) && count($this->compras)) :?>
                        <?php foreach ($this->compras as $val) :?>
                        <tr>
                            <td><?php echo date('d-m-Y',strtotime($val['emision'])) ?></td>
   
                            <td><?php echo $val['tipo']?></td>
                            
                            <td><?php echo $val['referencia'] ?></td>
                  
                            <td><?php echo strtoupper($val['razonSocial']) ?></td>
                            <td><?php echo $val['montoTotal'] ?></td>
                            <td><?php echo strtoupper($val['estado']) ?></td>
                            <td><span title="<?php echo strtoupper($val['comentarios']) ?>"><?php echo substr(strtoupper($val['comentarios']),0,30) ?></span></td>
                            <td>
                                <?php if($val['tipo']=='compra') : ?>
                                    <a href="<?php echo BASE_URL ?>compras/compra/editar/<?php echo $val['id'] ?>" >
                                        <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button>
                                <?php else: ?>
                                    <a href="#" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button>
                                    
                                <?php endif ?>    
                            </td>
                            <td>
                                <?php if($val['estado']=='ANULADO') : ?>        
                                        <button class="btn btn-default btn-sm" title="Presione aquí para anular registro" disabled> <i class="fa fa-trash"></i></button></td>
                                <?php else: ?>
                                    <a href="<?php echo BASE_URL ?>compras/compra/anular/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para anular registro"> <i class="fa fa-trash"></i></button></td>    
                                <?php endif ?>    
                            <td>
                                <?php if($val['estado']=='ANULADO') : ?>
                                    <button class="btn btn-default btn-sm" title="Presione aquí para crear Compras desde Oreden de Compra" disabled> <i class="fa-solid fa-recycle"></i></button>
                                <?php else: ?>    
                                    <?php  if($val['tipo']=='ord-cpra'):?>
                                        <a href="<?php echo BASE_URL ?>compras/compra/agregar/<?php echo $val['id'] ?>" >
                                        <button class="btn btn-default btn-sm" title="Presione aquí para crear Compras desde Oreden de Compra"> <i class="fa-solid fa-recycle"></i></button>
                                    <?php else: ?>
                                        <a href="<?php echo BASE_URL ?>compras/compra/agregar/<?php echo $val['id'] ?>" >
                                        <button class="btn btn-default btn-sm" title="Opción desabilitada" disabled>  <i class="fa-solid fa-recycle"></i></button>
                                    <?php endif; ?>
                                <?php endif ?>        
                            </td>   
                            <td>
                                <button class="btn btn-default btn-sm imprimir" title="Presione aquí para imprimir Orden de Compra" value="<?php echo $val['id'] ?>" data-toggle="modal" data-target="#modal-xl"> <i class="fa fa-print"></i></button>
                            </td>   
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                <p>
                        <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            
          </div>

        </div>
    </div>
    <div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-xl" bis_skin_checked="1">
            <div class="modal-content" bis_skin_checked="1">
                <div class="modal-header" bis_skin_checked="1">
                    <div class="card-tools">
                    <button type="button" class="btn btn-primary" id="imprimir" title="Imprimir Documento"><i class="fa fa-print"></i></button> <button type="button" class="btn btn-secondary" id="enviar" title="Enviar Documento por Correo Electrónico"><i class="fa-solid fa-envelopes-bulk"></i></button><div id="resmail"></div>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" bis_skin_checked="1">
                    <div id="nota" ></div>
                </div>
                <div class="modal-footer justify-content-between" bis_skin_checked="1">
                
                <div class="card-tools">
                    <button type="button" class="btn btn-primary" id="imprimir"><i class="fa fa-print"></i></button> <button type="button" class="btn btn-secondary" id="enviar"><i class="fa-solid fa-envelopes-bulk"></i></button>
                    </div>
                </div>
            </div>

        </div>

    </div>
        
</div>
