<div class="row-fluid">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="<?php echo BASE_URL ?>archivo/unidad/index/" title="Regresar ..."><button ><i class="fa fa-undo"></i></button></a>
                            <span class="navbar-brand" id="agregar"  title="Agregar deposito "><button ><i class="fa fa-plus"></i></button></span>  
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" maxlength="100" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Nro</th>
                        <th>Fecha</th>
                        <th>Nombre Deposio</th>
                        <th>Ubicacion</th>
						<th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id_relacion_unidad'] ?></td>
                            <td><?php echo date('d-m-Y',strtotime($val['fecha_creacion'])) ?></td>
                            <td><?php echo strtoupper($val['nombre_deposito']) ?></td>                            
							<td><?php echo strtoupper($val['ubicacion_deposito'].' '.$val['ubicacion_deposito']) ?></td>                            
                            <td>
                                <?php if($val['estatus_relacion']==1): ?>
                                <a href="<?php echo BASE_URL ?>archivo/unidad/desactivarDepositoUnidad/<?php echo $val['id_relacion_unidad'] ?>/<?php echo $this->unidad ?>" >   
                                    <button class="eliminar" title="Presione aquí para Desactivar" ><i class="fa fa-toggle-on"></i></button>
                                </a>
                                <?php else: ?>
                                <a href="<?php echo BASE_URL ?>archivo/unidad/activarDepositoUnidad/<?php echo $val['id_relacion_unidad'] ?>/<?php echo $this->unidad ?>" >    
                                    <button class="eliminar" title="Presione aquí para Activar" ><i class="fa fa-toggle-off"></i></button>
                                </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Agregar Deposito</div>
            <div class="panel-body">
                <form name="relacion" id="relacion" method="post" autocomplete="off" action="">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="unidad" type="hidden" value="<?php echo $this->unidad ?>" id="unidad">
                    <div class="form-group">
                        <label>***Nombre:</label>
                        <select name="deposito" id="deposito" class="form-control" disabled="true" >
                            <option value=""> Seleccione </option>
                            <?php if(count($this->noDeposito)): ?>
                                <?php foreach ($this->noDeposito as $val): ?>
                                    <option value="<?php echo $val['id_deposito'] ?>"><?php echo strtoupper($val['nombre_deposito']) ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>    
                    </div>
                    <button type="submit" class="btn btn-primary" disabled="true" id="enviar"><i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="reset" class="btn btn-danger" disabled="true" id="cancelar"><i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>