<div class="row">
    <div class="col-lg-8 col-md-6">
        <div class="card card-default">        
                
            <div class="card-header">
                <a class=""> <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>                  
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="busqueda" maxlength="60" class="form-control alfa_desc" placeholder="Filtrar nombre">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>

                        </div>
                    </div>        
                </div>
            </div>    

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="bg-secondary color-palette" >
                            <th>Código</th>
                            <th>Nombre</th>
                            <th>Descripción</td> 
                            <th width="30" ></th>
                            <th width="30"></th>
                            <th width="30"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; ?>    
                        <?php if(isset($this->lista) && count($this->lista)) :?>
                            <?php foreach ($this->lista as $val) :?>
                            <tr>
                                <td><?php echo $val['id'] ?></td>
                                <td><?php echo ucwords($val['nombre_role']) ?></td>
                                <td><?php echo ucfirst($val['descripcion_role']) ?></td>
                                <td>
                                    <?php if($val['estatus_role']==1): ?>
                                    <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                    <?php endif; ?>
                                </td>    
                                <td>
                                    <?php if($val['estatus_role']==1): ?>
                                    <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id'] ?>"><i class="fa fa-trash-o"></i></button>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL ?>seguridad/role/permisoRoles/<?php echo $val['id'] ?>" title="Presione aquí para agregar Recursos al Rol" >
                                        <button class="btn btn-default"> <i class="fa fa-shield"></i></button>
                                </td>
                            </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                    </table>
                    <hr>
                    <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card card-default">
            <div class="card-header">Pruebas de mensajes</div>
            <div class="card-body">
                <form name="form_rol" id="form_rol" method="post" autocomplete="off" action="<?php echo BASE_URL ?>mensajeria/whapi/prueba/">
                    <input name="guardar"  type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">                    
                    <div class="form-group">
                      <label>*Tipo de mensaje:</label>
                      <select class="form-control"  name="tipo" id="tipo" title="Seleccione el Rol del Usuario" required >
						  <option value="0">-Seleccione-</option>
						  <?php if(isset($this->tipo) && count($this->tipo)):  ?>
						  <?php foreach($this->tipo as $rl): ?>
							  <?php if($rl['estatus']==1): ?><i class="fa fa-floppy-o">
							  <option value="<?php echo $rl['id']  ?>"><?php echo $rl['nombre'] ?></option>
							  <?php endif; ?>
						  <?php endforeach; ?>
						  <?php endif; ?>
					  </select>
                    </div>
                    <div class="form-group">
                      <label>*Receptor:</label>
                      <select class="form-control"  name="receptor" id="receptor" title="Seleccione el Rol del Usuario" required >
						  <option value="0">-Seleccione-</option>
						  <?php if(isset($this->receptor) && count($this->receptor)):  ?>
						  <?php foreach($this->receptor as $rl): ?>
							  <?php if($rl['estatus']==1): ?><i class="fa fa-floppy-o">
							  <option value="<?php echo $rl['id']  ?>"><?php echo $rl['nombre'] ?></option>
							  <?php endif; ?>
						  <?php endforeach; ?>
						  <?php endif; ?>
					  </select>
                    </div>
                    <div class="form-group">
                      <label>*Mensaje:</label>
                      <input name="descripcion" type="text" maxlength="150" class="form-control alfa_desc" id="descripcion"  required>
                    </div>
                    <hr>
                    <button type="button"  name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-xs btn-app"> <i class="fa fa-floppy-o"></i> Enviar Formulario</button>
                    <button type="button"  name="agregar" id="saludo" title="Presione aquí para GUARDAR el registro"  class="btn btn-xs btn-app"> <i class="fa fa-floppy-o"></i> Enviar Saludo</button>
                    <button type="button"  name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-xs btn-app"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>
