<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="card card-default">   
            <div class="card-header">
                <a  href="<?php echo BASE_URL ?>almacen/despacho/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
            </div>  
            <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                    <tr class="bg-secondary color-palette">
                        <th>Código</th>
                        <th>Emisión</th>
                        <th>Documento</th>
                        <th>Destino del Despacho</th>
                        <th>Almacén de Despacho</th>
                        <th>Estado</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id'] ?></td>
                            <td><?php echo date('d-m-Y',strtotime($val['fechas_fecEmision'])) ?></td>
                            <td><?php echo $val['destino_TipDoc'].'-'.$val['destino_NroDoc'] ?></td>
                            <td><?php echo strtoupper($val['nombreDestino']) ?></td>
                            <td><?php echo $val['nombreAlmacen'] ?></td>
                            <td><?php echo $val['estado'] ?></td>
                            <?php if($val['estado']!='ANULADO'): ?>
                                <td><a href="<?php echo BASE_URL ?>almacen/despacho/detalle/<?php echo $val['id'] ?>" >
                                    <button class="editar btn btn-default btn-sm" title="Presione aquí para Ver detalle" value="<?php echo $val['id'] ?>" ><i class="fa-solid fa-eye"></i></button></a>
                                </td>
                                <td><a href="<?php echo BASE_URL ?>almacen/despacho/anular/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para Cancelar Registro"> <i class="fa fa-undo"></i></button></a>
                                </td>
                                <td>
                                    <button class="btn btn-default btn-sm imprimir" title="Presione aquí para imprimir Despacho" value="<?php echo $val['id'] ?>" data-toggle="modal" data-target="#modal-xl"> <i class="fa fa-print"></i></button>
                                </td>
                            <?php else: ?>
                                <td></td>
                                <td></td>
                                <td></td>   
                            <?php endif; ?>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                
            
          </div>

        </div>
    </div>
        

    <div class="modal fade" id="modal-xl" bis_skin_checked="1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-xl" bis_skin_checked="1">
            <div class="modal-content" bis_skin_checked="1">
                <div class="modal-header" bis_skin_checked="1">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" bis_skin_checked="1">
                    <div id="nota" ></div>
                </div>
                <div class="modal-footer justify-content-between" bis_skin_checked="1">
                
                    <button type="button" class="btn btn-primary" id="imprimir"><i class="fa fa-print"></i></button>
                </div>
            </div>

        </div>

    </div>                            

</div>
