<div class="row">
<div class="col-lg-12">
	<form name="form_proveedor_editar" method="post" id="form_proveedor_editar" action="<?php echo BASE_URL ?>compras/proveedor/editar/"  >
	<input name="guardar" id="guardar" type="hidden" value="2" />
	<input name="id" id="id" type="hidden" value="<?php echo (!empty($this->datos[0]['id']))?$this->datos[0]['id']:"" ?>" />
	<div class="card card-default">
		<div class="card-header">
            <span class="card-title">Informacion para registro de Proveedor</span>
		</div>
		<div class="card-body">
			<div class="row">
					<div class="form-group col-md-1">
						<label>*Tipo Persona:</label>
						<select name="tipo" id="tipo" class="form-control">
                            <option value="0">-Seleccione-</option>
                            <option value="J">Juridico</option>
                            <option value="V">Natural</option>
                        </select> 
					</div>
					<div class="form-group col-md-2">
						<label>*Nro Fiscal :</label>
						<input name="idFiscal"  maxlength="100" type="text" class="form-control valid_productor" id="idFiscal" value="<?php echo (!empty($this->datos[0]['idFiscal']))?$this->datos[0]['idFiscal']:"" ?>"  />  
					</div>
					<div class="form-group col-md-4">
						<label>*Razon Social:</label>
						<input type="text"  maxlength="100" class="form-control "  name="razonSocial" id="razonSocial" value="<?php echo (!empty($this->datos[0]['razonSocial']))?$this->datos[0]['razonSocial']:"" ?>"  />
					</div>
                    <div class="form-group col-md-5">
						<label>*Domicio Fiscal:</label>
						<input type="text"  maxlength="100" class="form-control "  name="domicilioFiscal" id="domicilioFiscal" value="<?php echo (!empty($this->datos[0]['domicilioFiscal']))?$this->datos[0]['domicilioFiscal']:"" ?>"  />
					</div>
					
			</div>
            </br>
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true"> Contactos del Proveedor</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" id="custom-tabs-four-contact-tab" data-toggle="pill" href="#custom-tabs-four-contact" role="tab" aria-controls="custom-tabs-four-contact" aria-selected="false">Otra Informacion</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="custom-tabs-four-tabContent">
                        <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue contactos del proveedor</span></div>
                                <div class="card-body">
                                <div class="row">
                                        <div class="form-group col-md-3">
                                            <label>*Telefono Ventas:</label>
                                            <input name="tlf_ventas"  maxlength="100" type="text" class="form-control form-control-sm" id="tlf_ventas" value="<?php echo (!empty($this->datos[0]['tlfVentas']))?$this->datos[0]['tlfVentas']:"" ?>" />  
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Telefono Administracion:</label>
                                            <input name="tlf_admon"  maxlength="100" type="text" class="form-control form-control-sm" id="tlf_admon" value="<?php echo (!empty($this->datos[0]['tlfAdmon']))?$this->datos[0]['tlfAdmon']:"" ?>"/>  
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Telefono Almacen:</label>
                                            <input type="text"  required maxlength="20" class="form-control form-control-sm"  name="tlf_almacen" id="tlf_almacen"  value="<?php echo (!empty($this->datos[0]['tlfAlmacen']))?$this->datos[0]['tlfAlmacen']:"" ?>"/>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>*Whatsapp</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="tlf_wsp" id="tlf_wsp" placeholder="" value="<?php echo (!empty($this->datos[0]['whatsapp']))?$this->datos[0]['whatsapp']:"" ?>" />
                                        </div>
                                        
                                        <div class="form-group col-md-4">
                                            <label>*Correo Ventas</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_ventas" id="correo_ventas" placeholder="Ej.: micorreo@hotmail.com" value="<?php echo (!empty($this->datos[0]['correoVentas']))?$this->datos[0]['correoVentas']:"" ?>"/>
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Correo Administracion</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_administracion" id="correo_administracion" placeholder="Ej.: micorreo@hotmail.com"  value="<?php echo (!empty($this->datos[0]['correoAdmon']))?$this->datos[0]['correoAdmon']:"" ?>"/>
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>*Correo Almacen</label>
                                            <input type="email"  required maxlength="100" class="form-control form-control-sm"  name="correo_almacen" id="correo_almacen" placeholder="Ej.: micorreo@hotmail.com" value="<?php echo (!empty($this->datos[0]['correoAlmacen']))?$this->datos[0]['correoAlmacen']:"" ?>"/>
                                        </div>
                                       
                                         
                                    </div>
                                </div>    

                            </div>
                        </div>
                        <div class="tab-pane fade " id="custom-tabs-four-contact" role="tabpanel" aria-labelledby="custom-tabs-four-contact-tab">
                            <div class="card">
                                <div class="card-header"><span class="card-title">Agregue informacion para contactar al productor</span></div>
                                <div class="card-body">
                                <div class="row">
                                        <div class="form-group col-md-12">
                                            <label>*Comentarios:</label>
                                            <textarea name="comentario" class="form-control" id="comentario" rows="3">
                                            <?php echo (!empty($this->datos[0]['comentarios']))?$this->datos[0]['comentarios']:"" ?>
                                            </textarea>
                                            
                                        </div>
                                </div>
                                </div>    

                            </div>
                        </div>
                        
                        
                    </div>
                </div>

            </div>
			
		</div>
        <div class="card-footer">
            <button type="button" class="btn btn-xs btn-app" id="agregar"><i class="fa fa-floppy-o"></i>Grabar</button>
			<a href="<?php echo BASE_URL ?>compras/proveedor/index/""><button type="button" class="btn btn-xs btn-app bg-danger disabled color-palette" id="cancelar"><i class="fa fa-undo"></i>Cancelar</button></a>					
        </div>
	</div>
		  
</div>
    
</form>
</div>
