<div class="row">
    <div class="col-12">
        <div class="card">
			
			    <div class="card-header">
				    <a  href="<?php echo BASE_URL ?>compras/proveedor/agregar/" title="Presione aquí para AGREGAR un nuevo registro"><button class="btn btn-default btn-sm" ><i class="fa fa-plus"></i></button></a>  
			    </div>
 
          <div class="card-body">
                <table class="table table-bordered table-striped" id="example1" >
                    <thead>
                        <tr class="bg-secondary color-palette" >
                        <th>Id Fiscal</th>
                        <th>Razón Social</th>
                        <th>Dirección</th>
                        <th>Telefonos</th>
                        <th>Correo Electrónico</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['tipoPersona'].'-'.$val['idFiscal'] ?></td>
                            
                            <td><?php echo strtoupper($val['razonSocial']) ?></td>
                  
                            <td><?php echo strtoupper($val['domicilioFiscal']) ?></td>
                            <td><?php echo $val['tlfVentas'].' - '.$val['tlfAdmon'] ?></td>
                            <td><?php echo $val['correoVentas'] ?></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>compras/proveedor/editar/<?php echo $val['id'] ?>" >
                                    <button class="btn btn-default btn-sm" title="Presione aquí para editar registro"> <i class="fa fa-edit"></i></button>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>compras/proveedor/eliminar/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para eliminar registro"> <i class="fa fa-trash"></i></button>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>compras/proveedor/ordenCompra/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para crear Orden de Compra"><i class="fa-regular fa-file"></i></button>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>compras/proveedor/compra/<?php echo $val['id'] ?>" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para crear Compra Directa  "><i class="fa-solid fa-cart-plus"></i></button>
                            </td>
                            <td>
                                <a href="" >
                                <button class="btn btn-default btn-sm" title="Presione aquí para ver Estado de Cuenta del proveedor"><i class="fa fa-bar-chart"></i></button>
                            </td>

                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                    <tfoot>
                      
                    </tfoot>
                </table>
                <hr>
                <p>
                        <?php //if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            
          </div>

        </div>
    </div>
        
</div>
